### ISSUE TITLE
建议：可否新增点击效果方便用于日期选择

### ISSUE THREAD

**Issue by JiangShuLiang** [huanghaibin-dev/CalendarView#1]
找了很多calendarView，唯独对你这个很满意，做的很漂亮！先给个赞
提个建议：新增点击日期的效果（就是在点中的日期加个圆形的背景），这样用户在选择日期的时候就很直观是点了哪个日期

**Comment by huanghaibin-dev** [comment]
好的，就是日期的选中效果吧，1.0.3版本会加上节假日和选中当前日期效果。

**Comment by JiangShuLiang** [comment]
好！非常棒！非常感谢！！！

**Comment by huanghaibin-dev** [comment]
最新版本已经发布了，终于支持周视图了，感谢支持
