### ISSUE TITLE
setSchemeData

### ISSUE THREAD

**Issue by ExplosiveBattery** [huanghaibin-dev/CalendarView#102]
这个函数的使用需要维持一个List<Calender>, 在数据更改的时候需要对calenderView进行update()
我发现当用户因为将某一天所有的事情删除掉, list变为空, 再update, 日历上那个事情标记并没有被去除.

**Comment by eggyu** [comment]
我也發現一樣的問題

**Comment by huanghaibin-dev** [comment]
需要重新setSchemeData，List引用在内部维持，避免外部其它线程对其修改，否则会异常

**Comment by eggyu** [comment]
@huanghaibin-dev 我用setSchemeData去變更一樣無法達到刪除的效果

**Comment by eggyu** [comment]
我現在把所有日期都加到SchemeList 再用WeekView的onDrawScheme去判斷Type 就有移除效果了

**Comment by Jvr0771** [comment]
添加可以，删除不得

**Comment by zxfnicholas** [comment]
请问，删除的这个bug什么时候可以修复？

**Comment by soul7630** [comment]
删除标记这个功能非常有用，希望作者能够加上

**Comment by huanghaibin-dev** [comment]
我马上修复一下，这段日子太忙，不好意思

**Comment by huanghaibin-dev** [comment]
@ExplosiveBattery @eggyu @Jvr0771 @zxfnicholas @soul7630 已修复

**Comment by Jvr0771** [comment]
大佬就是效率

**Comment by soul7630** [comment]
@huanghaibin-dev 效率效率

**Comment by zxfnicholas** [comment]
十分感谢！
