### ISSUE TITLE
【删除标记】建议添加删除标记功能

### ISSUE THREAD

**Issue by LiHuiDev** [huanghaibin-dev/CalendarView#110]
作者您好，在使用 setSchemeDate 方法添加的标记目前貌似无法删除，建议后续添加该功能，谢谢！！
如果您有解决方案、望告知！
--一只小菜鸟

**Comment by huanghaibin-dev** [comment]
@LiHuiDev 已经修复，请用新版本

**Comment by LiHuiDev** [comment]
十分感谢！嘻嘻
