### ISSUE TITLE
上拉收起动画失效，demo 可复现

### ISSUE THREAD

**Issue by spring-z** [huanghaibin-dev/CalendarView#113]
本月存在动画，可跟随手指，其他月份无动画覆盖，请问是 feature 还是一个 bug

**Comment by spring-z** [comment]
月视图切换为周视图

**Comment by huanghaibin-dev** [comment]
什么意思，可以详细介绍一下吗

**Comment by spring-z** [comment]
您可以看一下 demo 中的 本月和 次月 上拉的时候的区别吗？我很难描述这个，谢谢

**Comment by huanghaibin-dev** [comment]
貌似没发现什么问题，5.0以下的机器是没动画的，没办法

**Comment by spring-z** [comment]
不是 5.0 啊，稍等下，我拍个 gif

**Comment by spring-z** [comment]
![jietu20180329-175837](https://user-images.githubusercontent.com/5770157/38083137-57df53b4-337b-11e8-9f2e-3a50197f1f72.gif)

**Comment by spring-z** [comment]
@huanghaibin-dev 您看下，是 8.0 的 模拟器

**Comment by spring-z** [comment]
哦哦，貌似是我傻逼了，当前已经月底了，切换到其他月份是没有动画的，抱歉

**Comment by huanghaibin-dev** [comment]
模拟器我就无能为力了，不过你的demo貌似没有指定View，这样就会失去动画
