### ISSUE TITLE
怎样隐藏掉农历？ 我的方法就是把农历的字体大小调整为0，但是日期号码没有居中？

### ISSUE THREAD

**Issue by CordyHo** [huanghaibin-dev/CalendarView#114]

**Comment by huanghaibin-dev** [comment]
看README介绍，没有隐藏农历或者新历的说法，简单点说就是要显示什么需要你自己去绘制，你使用SimpleMonthView就是没有农历的，去掉里面过度绘制的API，就不会卡顿，我只是提供demo例子

**Comment by CordyHo** [comment]
对，我用了SimpleMonthView， 的确很卡，那些代码是过度绘制的API ？

private int mRadius;

    public SimpleMonthView(Context context) {
        super(context);
    }

    @Override
    protected void onPreviewHook() {
        mRadius = Math.min(mItemWidth, mItemHeight) / 5 * 2;
        mSchemePaint.setStyle(Paint.Style.STROKE);
        mSchemePaint.setShadowLayer(15, 1, 3, 0xAA333333);
        setLayerType(LAYER_TYPE_SOFTWARE, null);
    }

    @Override
    protected void onLoopStart(int x, int y) {

    }

    @Override
    protected boolean onDrawSelected(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme) {
        int cx = x + mItemWidth / 2;
        int cy = y + mItemHeight / 2;
        canvas.drawCircle(cx, cy, mRadius, mSelectedPaint);
        return false;
    }

    @Override
    protected void onDrawScheme(Canvas canvas, Calendar calendar, int x, int y) {
        int cx = x + mItemWidth / 2;
        int cy = y + mItemHeight / 2;
        canvas.drawCircle(cx, cy, mRadius, mSchemePaint);
    }

    @Override
    protected void onDrawText(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme, boolean isSelected) {
        float baselineY = mTextBaseLine + y;
        int cx = x + mItemWidth / 2;

        if (isSelected) {
            canvas.drawText(String.valueOf(calendar.getDay()),
                    cx,
                    baselineY,
                    mSelectTextPaint);
        } else if (hasScheme) {
            canvas.drawText(String.valueOf(calendar.getDay()),
                    cx,
                    baselineY,
                    calendar.isCurrentDay() ? mCurDayTextPaint :
                            calendar.isCurrentMonth() ? mSchemeTextPaint : mOtherMonthTextPaint);

        } else {
            canvas.drawText(String.valueOf(calendar.getDay()), cx, baselineY,
                    calendar.isCurrentDay() ? mCurDayTextPaint :
                            calendar.isCurrentMonth() ? mCurMonthTextPaint : mOtherMonthTextPaint);
        }
    }
}

**Comment by huanghaibin-dev** [comment]
setShadowLayer  setLayerType这些绘制阴影的都去掉即可
