### ISSUE TITLE
Set the first day of the week

### ISSUE THREAD

**Issue by kerimtorun** [huanghaibin-dev/CalendarView#116]
How do we change the first day of the week to Monday?
(Simple Activity CalenderView)

**Comment by readen** [comment]
please implement  it with custom WeekBar , MonthView and WeekView

**Comment by readen** [comment]
please implement  it with custom WeekBar , MonthView and WeekView

**Comment by kerimtorun** [comment]
How do you make changes to which fields in the MoonView and WeekView classes?

**Comment by huanghaibin-dev** [comment]
Done, Using 3.2.9 Version
