### ISSUE TITLE
只允许使用周视图的设置无效

### ISSUE THREAD

**Issue by hbzkw** [huanghaibin-dev/CalendarView#122]
app:only_week_view="true"   这个只使用周视图设置为true后，下拉还是可以展开月视图，想要只显示月视图的效果

**Comment by huanghaibin-dev** [comment]
app:calendar_show_mode="only_week_view" 用这个，很早去掉了这个attr了，一直没有删除

**Comment by hbzkw** [comment]
问题解决了  非常感谢  有支付宝账号吗？请您喝咖啡☕

**Comment by huanghaibin-dev** [comment]
打赏什么的就不用了，好用就行，谢谢支持

**Comment by hbzkw** [comment]
十分感谢
