### ISSUE TITLE
Custom YearView

### ISSUE THREAD

**Issue by wendyliga** [huanghaibin-dev/CalendarView#124]
how i can customize yearview on  mCalendarView.showYearSelectLayout(mYear)

thanks so much, btw really good library

**Comment by wendyliga** [comment]
i mean how to remove chinese character on it?

**Comment by huanghaibin-dev** [comment]
The current version can not customize for YearView. I will support it as soon as possible.

**Comment by wendyliga** [comment]
thanks so much , really appriciate that

**Comment by huanghaibin-dev** [comment]
Done, Using V3.2.9

**Comment by wendyliga** [comment]
thanks that's really awesome
