### ISSUE TITLE
onDateLongClick also trigger onDateSelected (isClick true)

### ISSUE THREAD

**Issue by wendyliga** [huanghaibin-dev/CalendarView#125]
can i prevent triggering onDateSelected , when i long press on the calender ?

**Comment by huanghaibin-dev** [comment]
I immediately release a new version that supports a lot of new features.

**Comment by wendyliga** [comment]
happy to hear that

**Comment by huanghaibin-dev** [comment]
Done, Using CalendarView.setOnDateLongClickListener(this, true); API

**Comment by wendyliga** [comment]
thanks , it's work
