### ISSUE TITLE
可否增加 "year_view_scrollable" 的 attr?

### ISSUE THREAD

**Issue by shuwnyuantee** [huanghaibin-dev/CalendarView#134]
您好，非常感谢您提供这个超好用的 library，谢谢！

这是我的 app 里，运用您的 CalendarView 的 screenshots:

![1](https://user-images.githubusercontent.com/614382/40434626-51acbde2-5ee1-11e8-9f1a-b4f6eb759923.png)
![2](https://user-images.githubusercontent.com/614382/40434637-572cdfc2-5ee1-11e8-8bb2-804ba65a8e2e.png)

目前，通过以下的 attr, 我已经成功设置 “月视图” 让它不滚动：

     app:month_view_scrollable="false"
    
在 “年视图”里，我需要类似的设置。请问可否增加以下的 attr？

    <attr name="year_view_scrollable" format="boolean" />

如果您同意增加这个 attr，我将义不容辞的提供相关的 Pull Request。请让我知道，谢谢！

**Comment by huanghaibin-dev** [comment]
当然可以，我的规划是：接下来YearView需要重新设计，和MonthView一样支持插拔设计，这样才能随意定义UI

**Comment by shuwnyuantee** [comment]
您好，太好了，谢谢。

目前，我 fork 了您的 CanlendarView Project，自行做了以下的更改，好让 “年视图” 不滚动：

https://github.com/shuwnyuantee/CalendarView/commit/ed771a01fda72d0c0a1489e9216e840680473107

但这是 hardcoded 的方式，只局限于我的 app 的运用。

而且以其 maintain 自己的 fork project，我比较乐于直接运用您的 Project，这样就能随时得到更新。

如果您乐意，我可以做以下的改动 （放心，我不会用以上 hardcoded 的方式），并提供 Pull Request：

- 在 `CalendarViewDelegate` 里，增加 `mYearViewScrollable`
- 在 `attr.xml` 里，增加 `<attr name="year_view_scrollable" format="boolean" />`

请让我知道，谢谢！

**Comment by shuwnyuantee** [comment]
这是我最新的 Pull Request：https://github.com/huanghaibin-dev/CalendarView/pull/135

如果合适，欢迎采纳。如果不合适，也没关系的。谢谢！
