### ISSUE TITLE
设置或删除 Scheme 时，年视图没能同时被更新

### ISSUE THREAD

**Issue by shuwnyuantee** [huanghaibin-dev/CalendarView#143]
您好。

当我们 call 以下 functions 的时候，月视图及周视图会马上被更新。但年视图不被更新。

- calendarView.setSchemeDate()
- calendarView.clearSchemeDate()
- calendarView.removeSchemeDate()

我做了相关改动，在这 Pull Request：https://github.com/huanghaibin-dev/CalendarView/pull/142

请您看是否合适，若合适 feel free to merge，谢谢这么好用的 library!

**Comment by huanghaibin-dev** [comment]
done

**Comment by shuwnyuantee** [comment]
Cool, many thanks! 👍
