### ISSUE TITLE
每月默认第一天选中，是否是Bug?

### ISSUE THREAD

**Issue by xiaobaDev** [huanghaibin-dev/CalendarView#147]
一般都是默认未选吧？
仔细看了issue#72 用静态变量来保存，这个有点不合适吧？还是期望设计的时候就能考虑

**Comment by xiaobaDev** [comment]
这个是我改了之后的代码，在MonthViewPager的pageSelect函数里，作者麻烦看下，有无问题
```
 if (mDelegate.mDateSelectedListener != null && !isUsingScrollToCalendar) {
                    mWeekBar.onDateSelected(mDelegate.mSelectedCalendar, mDelegate.getWeekStart(), false);
                    mDelegate.mDateSelectedListener.onDateSelected(mDelegate.mSelectedCalendar, false);
                }

                MonthView view = findViewWithTag(position);
                if (view != null) {
                    int index = view.getSelectedIndex(mDelegate.mSelectedCalendar);

                    if (index >= 0 && mParentLayout != null) {
                        view.mCurrentItem = index;
                        mParentLayout.setSelectPosition(index);
                    }
                    view.invalidate();
                }
                mWeekPager.updateSelected(calendar, false);
```

**Comment by huanghaibin-dev** [comment]
目前使用的日历：小米、魅族、大多数万年历等都是这样默认选中第一天的，后面的打算是增加各种不同的多项、单选、范围选中视图，issue#72只是一种折中做法

**Comment by xiaobaDev** [comment]
恩，我自己处理吧，好库

**Comment by libin1993** [comment]
@xiaobaDev 这段代码注释掉可以
//                if (mDelegate.mDateSelectedListener != null && !isUsingScrollToCalendar) {
//                    mWeekBar.onDateSelected(mDelegate.mSelectedCalendar, mDelegate.getWeekStart(), false);
//                    mDelegate.mDateSelectedListener.onDateSelected(mDelegate.mSelectedCalendar, false);
//                }

//                MonthView view = (MonthView) findViewWithTag(position);
//                if (view != null) {
//                    int index = view.getSelectedIndex(mDelegate.mSelectedCalendar);
//                    view.mCurrentItem = index;
//                    if (index >= 0 && mParentLayout != null) {
//                        mParentLayout.setSelectPosition(index);
//                    }
//                    view.invalidate();
//                }
//                mWeekPager.updateSelected(mDelegate.mSelectedCalendar, false);
