### ISSUE TITLE
在小手机屏幕，月视图未能完整呈现

### ISSUE THREAD

**Issue by shuwnyuantee** [huanghaibin-dev/CalendarView#148]
您好。

在小的手机屏幕，月视图未能完整的呈现。请问是否能改成 scrollable 的方式，就如年视图？谢谢！

![bbb](https://user-images.githubusercontent.com/614382/40885662-6880af5e-675d-11e8-8d67-d57a283cc48e.png)

**_后记:_**

我们的 Android App - Note+ 今天上架到 Google Play Store 了：https://trello.com/b/egVBdrmN/note-notes-checklists-reminders

这是我们的相关 Trello Board: https://trello.com/b/egVBdrmN/note-notes-checklists-reminders

在我们的 App 里，运用了您非常卓越的 CalendarView。我们的团队衷心感激您的支援，谢谢！

**Comment by shuwnyuantee** [comment]
是的，自行嵌套scrollview 后，问题解决了。谢谢！

**Comment by huanghaibin-dev** [comment]
似乎您的月视图高度太大了，这样不是特别美观，一般的高度46dp足够了，个人见解

**Comment by shuwnyuantee** [comment]
那是之前的 screenshot。在最新版本里，我没在 `xml` 里自行设置 `calendar_height`。所以用的是您的 default setting: `56dp`.

这是最新 screenshots:

- **Nexus 6P**

![nexus_6p](https://user-images.githubusercontent.com/614382/40897713-3f928526-67ef-11e8-9c04-11b526c53e5c.png)


- **Nexus S**

![nexus_s](https://user-images.githubusercontent.com/614382/40897726-56c77fa8-67ef-11e8-9fe1-6c30f95a0b2a.png)
