### ISSUE TITLE
第一进去，上下滑动下面的列表，日历周视图不正确

### ISSUE THREAD

**Issue by caizhibiao** [huanghaibin-dev/CalendarView#15]
第一进去，上下滑动下面的列表，日历月未移动，周视图也不正确

**Comment by huanghaibin-dev** [comment]
@caizhibiao 什么意思？可否详细说明？

**Comment by caizhibiao** [comment]
比如当前是9月14日，在第3行， 然后往上滑动，变成周视图后，显示的是1号那一行的，里面并没有当前日期。（前提条件是打开app，不点击日期，直接往上滑动）

**Comment by huanghaibin-dev** [comment]
@caizhibiao 原来是这个意思啊，我明白了，太谢谢你了，我会把这方面的体验优化好，之前太注重性能提升了

**Comment by huanghaibin-dev** [comment]
全新版本已经开源，可以任意自定义UI了，谢谢支持。
