### ISSUE TITLE
提一些小建议

### ISSUE THREAD

**Issue by huangyanbin** [huanghaibin-dev/CalendarView#156]
您好，我在使用过程中发现一些问题，感觉想设置数据有点困难。我觉得应该把绘制部分完全交给使用者，抽离出draw部分成接口，然后addDrawFromat去动态根据数据绘制。我之前也写了一个日历，和简单的那种，只有月模式，我感觉我在动态绘制还可以，把绘制和数据可以动态结合，但是其他部分你这个功能实在有点强大，有点望其项背。希望你能看下我写的部分。然后结合一下，那就非常棒。[项目地址](https://github.com/huangyanbin/CalendarView)

**Comment by huanghaibin-dev** [comment]
感谢您的支持，这个日历的所有绘制权都是交给使用者的，README已经说明白了，可以通过和自定义Behavior一样的用法设置自定义的各种路径如月视图、周试图等，然后自行在回调绘制里自行绘制；至于为什么设置成抽象类而不是抽象接口的主要原因：抽象类更加开放，可以自行在抽象类里面添加各种自定义的属性，这个接口做不到的。我明天clone你的代码下来研究看看，刚才大概看了一下，发现部分方法代码层次有点深了，可以优化，for循环深度尽量不要超过3个，不然阅读性就不太好

**Comment by huangyanbin** [comment]
不好意思，我刚刚用这个框架，我个人觉得月视图和周视图绘制可能需要和业务逻辑组合一起，比如从网络拉去数据需要动态改变显示，可能需要N种不同效果，和周view和月视图去改变是不是有点太困难了，假设数据从Activity收到数据如何传给月视图和周视图然后去绘制效果？

**Comment by huanghaibin-dev** [comment]
CalendarView.setSchemeDate()添加事务，可以单添加、多添加，这样就会自动回调onDrawScheme这个方法了，事务是可以同一天标记任意数量或者类型的，这样就能适配各种风格，也没什么侵入性

**Comment by huangyanbin** [comment]
我咋感觉只能标记一种啊

**Comment by huanghaibin-dev** [comment]
没有限制的，README中国风格那种，是两种标记的，既有下标一个圆点，也有右上角的文本

**Comment by qianduoduo** [comment]
我们看了表格介绍，感觉功能很强大，想详细了解下，麻烦加下我qq:562317497,如果我们觉得合适，可以付费。
