### ISSUE TITLE
变成周视图后，左右滑动应该是上一周和下周的日期，而不是上一个月和下一个月

### ISSUE THREAD

**Issue by caizhibiao** [huanghaibin-dev/CalendarView#16]

**Comment by huanghaibin-dev** [comment]
@caizhibiao 收缩左右切换这个倒是没有去设计，因为理论上就是月份切换，我参考一下看看如何设计周视图

**Comment by whb7762300** [comment]
@huanghaibin-dev 嗯,的确,作者的这个项目挺好的,就是周视图左右切换是改变月份的,希望作者可以修改修改

**Comment by huanghaibin-dev** [comment]
@whb7762300 谢谢支持，我会尽快改进的

**Comment by Cunese2020** [comment]
老哥   变成周视图后，左右滑动应该是上一周和下周的日期   这个有没有把他优化下

**Comment by huanghaibin-dev** [comment]
@Cunese2020 最新版本已经发布了，终于支持周视图了，感谢支持
