### ISSUE TITLE
收缩之后滑动，能不能一周一周的滑动

### ISSUE THREAD

**Issue by ChenPengHuang** [huanghaibin-dev/CalendarView#165]
像小米那样，滑动viewpager的时候一周一周的显示。目前滑动的时候只能滑动到下一个月的同一周

**Comment by huanghaibin-dev** [comment]
一直都是支持周视图的啊，一周一周滑动的

**Comment by ChenPengHuang** [comment]
是吗。。。为什么目前7月4日。然后我左滑之后就去到8月4日了。。。

**Comment by huanghaibin-dev** [comment]
你clone demo看看吧，看看你用什么版本

**Comment by ChenPengHuang** [comment]
CalendarLayout的default_status属性好像无效。我只要一周一周滑动的。不需要可以收缩或者展开。。。。

**Comment by huanghaibin-dev** [comment]
那个是默认状态，用这个属性app:calendar_show_mode="only_week_view"

**Comment by ChenPengHuang** [comment]
我发现了。。。CalendarLayout必须带calendar_content_view_id属性才能一周一周的滑

**Comment by huanghaibin-dev** [comment]
如果需要收缩功能的话，calendar_content_view_id就是必须的，否则没法平移控件
