### ISSUE TITLE
固定月模式后，下面的list无法向上滑动

### ISSUE THREAD

**Issue by xiaominglee4github** [huanghaibin-dev/CalendarView#166]

**Comment by huanghaibin-dev** [comment]
检查一下calendar_content_view_id对不对

**Comment by huanghaibin-dev** [comment]
如果是嵌套复杂布局的话，FrameLayout实现CalendarScrollView 接口，可自行解决冲突，参考Demo ViewPager风格的布局

**Comment by xiaominglee4github** [comment]
我看了code，向下滑动会判断isScrollTop但是向上滑动不会，所以重写isScrollTop好像对这个问题没有帮助，不过还是谢谢你的及时答复。你人真的很nice~

**Comment by huanghaibin-dev** [comment]
只需要判断isScrollTop就行的，如果是滚动到顶部，下滑会拉下来，如果是上滑，isScrollTop是true的话就不拦截，否则就会拦截收缩

**Comment by xiaominglee4github** [comment]
向上滑动, dy < 0 所以就根本不会进isScrollTop()

if (dy > 0 && mContentView.getTranslationY() == -mContentViewTranslateY
                        && y >= CalendarUtil.dipToPx(getContext(), 98)) {
                    if (!isScrollTop())
                        return false;
                }

**Comment by huanghaibin-dev** [comment]
这是下拉的判断吧，上滑是直接判断月视图是否已经收缩
