### ISSUE TITLE
滑动折叠上滑到顶后，下面的recyvleview不能再滑动，只有日历左右切换下下面的rv才能继续滑动

### ISSUE THREAD

**Issue by HastarWiard** [huanghaibin-dev/CalendarView#17]
滑动折叠上滑到顶后，下面的recyvleview不能再滑动，只有日历左右切换下下面的rv才能继续滑动

**Comment by huanghaibin-dev** [comment]
多谢反馈，我在处理了

**Comment by huanghaibin-dev** [comment]
全新版本已经开源，可以任意自定义UI了，谢谢支持。

**Comment by a1018875550** [comment]
这个bug解决了么？3.0版本还是不行

**Comment by huanghaibin-dev** [comment]
@a1018875550 这个是很奇怪的问题，如果界面还没初始化就加载RecyclerView的数据然后动态设置recyclerViewd的高度，会不能滚动，即使不用日历控件也一样，当然post一下设置数据或者来自网络的数据就正常了
