### ISSUE TITLE
周视图切换到下一周的时候能屏蔽自动选中吗？手动点击才选中

### ISSUE THREAD

**Issue by itzhaokun** [huanghaibin-dev/CalendarView#170]
周视图切换到下一周的时候能屏蔽自动选中吗？手动点击才选中

**Comment by iielse** [comment]
@huanghaibin-dev 想问一下为什么设计 select_mode， 是什么业务场景。  一般都是手动点击选中吧。。

**Comment by huanghaibin-dev** [comment]
@iielse 场景多了去了，至少国内几大手机厂商、各种万年历APP，都是这个默认模式
