### ISSUE TITLE
How to remove chinese subtitles in calendar view?

### ISSUE THREAD

**Issue by lakshyapunhani** [huanghaibin-dev/CalendarView#175]
`<com.haibin.calendarview.CalendarLayout
        android:id="@+id/calendarLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#fff"
        android:orientation="vertical"
        app:default_status="expand"
        app:calendar_content_view_id="@+id/recyclerView">

        <com.haibin.calendarview.CalendarView
            android:id="@+id/calendarView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#fff"
            app:calendar_padding="10dp"
            app:current_month_lunar_text_color="#CFCFCF"
            app:current_month_text_color="#333333"
            app:min_year="2004"
            app:month_view_show_mode="mode_only_current"
            app:other_month_text_color="#e1e1e1"
            app:scheme_lunar_text_color="#ffffff"
            app:scheme_text="q"
            app:scheme_text_color="#fff"
            app:scheme_theme_color="#128c4b"
            app:selected_lunar_text_color="#fff"
            app:selected_text_color="#fff"
            app:selected_theme_color="#108cd4"
            app:week_background="#fff"
            app:week_text_color="#111"
            app:year_view_day_text_color="#333333"
            app:year_view_day_text_size="9sp"
            app:year_view_month_text_color="#ff0000"
            app:year_view_month_text_size="20sp"
            app:year_view_scheme_color="#f17706" />

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </com.haibin.calendarview.CalendarLayout>`

**Comment by huanghaibin-dev** [comment]
Use your custom MonthView and WeekView, look at the demo simple package.
