### ISSUE TITLE
想问一下类似这样的该怎么做？

### ISSUE THREAD

**Issue by androidflying** [huanghaibin-dev/CalendarView#180]
https://github.com/square/android-times-square
就是向ListView一样竖着滑动的日历

**Comment by huanghaibin-dev** [comment]
这个不支持的，这种竖直日历操作方式现在已经不用了，国内各个手机商以及各种日历开发商都不用这种操作方式，这个框架本身不会去支持，请谅解

**Comment by androidflying** [comment]
@huanghaibin-dev 好的，谢谢提醒
