### ISSUE TITLE
月份可以上下滑动吗

### ISSUE THREAD

**Issue by Blizzard-liu** [huanghaibin-dev/CalendarView#191]

**Comment by huanghaibin-dev** [comment]
不支持的，上下滑动的日历，这种操作理念现在除了iphone，国内各个手机商和日历开发商都不采用，因此这个框架也不会提供的

**Comment by Blizzard-liu** [comment]
我们现在有这个需求 我找个好久都没合适  没有农历数据 自己设置滑动会卡顿

**Comment by Blizzard-liu** [comment]
订机票的app好像都是上下滑动的

**Comment by huanghaibin-dev** [comment]
你可以改一下源码，把月视图的MonthViewPager改成垂直状态就可以了，issue有人改成功过，可以看看，或者你google搜一下垂直ViewPager，不难，就改这个MonthViewPager

**Comment by Blizzard-liu** [comment]
我试试

**Comment by Blizzard-liu** [comment]
大神 我用的这个库 但是设置农历会滑动卡顿   有木有好的办法   https://github.com/square/android-times-square

**Comment by huanghaibin-dev** [comment]
没有，ListView或者RecyclerView实现的日历，性能都是特别差的，加一个农历意味着至少需要增加90个TextView，而且从本来没有农历到有农历的过渡，那意味着外层需要再增加一个父布局，那就是至少得增加180个View了，性能特别差

**Comment by Blizzard-liu** [comment]
怪不得会卡  那大神的库支持区间选择日期吗

**Comment by huanghaibin-dev** [comment]
现在在设计区间选择视图和多选视图，后续版本开放吧，目前这个日历可以自己去发挥，但并不是100%适合全部人的，已经做到让UI绘制自由化了

**Comment by Blizzard-liu** [comment]
https://github.com/hosle/HoVerticalCalendarView

大佬看看这个 RecyclerView写的 很溜  kotlin写的   设置农历一点不卡

**Comment by huanghaibin-dev** [comment]
你得看RecyclerView的adapter实现，依然是基于绘制的，那就不会卡，基于布局的，那就会卡

**Comment by Blizzard-liu** [comment]
666
