### ISSUE TITLE
你好，calendar下面的content view中内容可以设置居中显示吗？

### ISSUE THREAD

**Issue by xiaominglee4github** [huanghaibin-dev/CalendarView#193]
我的contentview是一个布局，有listview和empty view，我想要我的empty view居中显示，现在会有问题，因为下面的高度并不是真实的高度，请问这个怎么处理？谢谢

**Comment by huanghaibin-dev** [comment]
ContentView 会被重新计算高度，如果要多重包含的话，ConyentView自行实现CalendarScrollView接口，处理一下就可以，用FrameLayout就可以的

**Comment by xiaominglee4github** [comment]
我想得到的是空白区域的实际的高度，这个和isScrollToTop有什么关系吗？我不太明白你说的

**Comment by xiaominglee4github** [comment]
CalendarScrollView接口应该是滑动的时候判断高度用的，但是我是想list为空时，在居中的位置显示提示信息

**Comment by huanghaibin-dev** [comment]
你说的是月视图展开时ContentView的高度？还是收缩时的实际高度？

**Comment by xiaominglee4github** [comment]
就是我下面显示的是一个layout，里面有listview和textview之类的，listview为空时我想textview的内容是在空白区域是居中显示的。不管是月视图还是周试图~ 这个需要我自己动态计算设置高度？

**Comment by huanghaibin-dev** [comment]
<FrameLayout
        android:id="@+id/customLayout"
        android:background="#eeeeee"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

        <View
            android:id="@+id/emptyView"
            android:layout_gravity="center"
            android:background="#333333"
            android:layout_width="200dp"
            android:layout_height="200dp"/>
    </FrameLayout>
这样子就可以的，然后在activity postCreate回调那里，对emptyView.requestLayout()即可

**Comment by huanghaibin-dev** [comment]
onPostCreate 或者 view.post都可以的，就是为了让子View在父View变换高度后重新测量一下布局

**Comment by xiaominglee4github** [comment]
view.post这里的view指的是contentview吗？

**Comment by huanghaibin-dev** [comment]
任意view都行的

**Comment by xiaominglee4github** [comment]
好的，我试试看，谢谢你

**Comment by xiaominglee4github** [comment]
我刚才尝试了下，似乎不行。我是在onViewChange里去requestLayout的

**Comment by huanghaibin-dev** [comment]
这样吧，你加我QQ吧，1505651581，我看看你是怎么布局的

**Comment by xiaominglee4github** [comment]
OK

**Comment by xiaominglee4github** [comment]
已加，麻烦通过下，谢谢

**Comment by huanghaibin-dev** [comment]
没收到请求。。。检查一下QQ是否写错了

**Comment by xiaominglee4github** [comment]
QQ 还是微信？看信息是你啊，应该没错

**Comment by clxy** [comment]
可以分享下最终的结果吗？
遇到了同样的问题
