### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by liwei49699** [huanghaibin-dev/CalendarView#199]
很不错，各种功能都能很简单的实现，但发现了个小问题 默认选中情况下，切换回当月时选中事件回调的默认为1号，而界面上选中的是今天

**Comment by huanghaibin-dev** [comment]
谢谢支持，这个问题已经修复了，近期发布个新版本

**Comment by liwei49699** [comment]
嗯 作者回复很迅速嘛 还有个疑问 首次进来时 给今天添加的Scheme 在onDateSelected获取不到

**Comment by huanghaibin-dev** [comment]
设置的Listener的适合，没有添加事物，我改正一下

**Comment by huanghaibin-dev** [comment]
设置的Listener的时候，没有为选中的日期添加事物，我改正一下

**Comment by liwei49699** [comment]
嗯 好的 谢谢了

**Comment by huanghaibin-dev** [comment]
done
