### ISSUE TITLE
bug：除了今天以外的日期也会显示红色（两个情况下，有附图）

### ISSUE THREAD

**Issue by JiangShuLiang** [huanghaibin-dev/CalendarView#2]
现在发现主要有以下两个情况会发生这个bug：
情况一：
比如今天是3-25，则我第一次点击的其他日期（比如3-22），这时候再点其他日期（比如3-15），则22会变红色；如下图：
![1](https://cloud.githubusercontent.com/assets/20485764/24320822/24966be4-1178-11e7-9f6d-8c87ba292f41.png)

情况二：
比如今天是3-25，但点击其他日子的时候有一定概率该日子颜色会变红，如下图：
![2](https://cloud.githubusercontent.com/assets/20485764/24320826/63ceab78-1178-11e7-9d5a-6e98a9a9b709.png)

另外，再提个建议哈：如果能设置该日子被选中时的颜色就更棒了！因为比如选中时蓝底黑字就不美观了

**Comment by huanghaibin-dev** [comment]
好吧，这里应该是RecyclerView的bug，局部刷新可能会出现错位的情况，以前也遇到过，马上改进一下策略

**Comment by huanghaibin-dev** [comment]
好吧，这里应该是RecyclerView的bug，局部刷新可能会出现错位的情况，以前也遇到过，马上改进一下策略

**Comment by JiangShuLiang** [comment]
谢谢！

**Comment by huanghaibin-dev** [comment]
@JiangShuLiang 修复了，现在应该满足很多情况的需求了

**Comment by JiangShuLiang** [comment]
看到了！这bug修复速度点个赞！谢谢！

**Comment by huanghaibin-dev** [comment]
@JiangShuLiang 谢谢支持

**Comment by JiangShuLiang** [comment]
如果再设置点击日期的字体颜色就完美了哈，最理想的是点击日期时字体颜色能是白色的。
你看这条issue第一张截图：
1，农历的二十都几乎看不到了；
2，蓝底黑字的日期看着也不是很美观；

之前我貌似提了有点多的issue 你不要介意哈，这次这条只是关于UI上的一点点小小的advice哈

**Comment by huanghaibin-dev** [comment]
@JiangShuLiang 哈哈，求之不得的建议，app:selected_text_color="#333333" 这个特性就是选中的文本颜色啊，什么颜色都可以

**Comment by JiangShuLiang** [comment]
我居然没注意到还有这个属性，666扎心了老铁，很棒的calendarview，就等着你更新节假日整个calenderview就perfect了！
