### ISSUE TITLE
请问发现默认的weekbar与日期纵向不对齐 应该怎么调整weekbar的margin?

### ISSUE THREAD

**Issue by DeveloperHu** [huanghaibin-dev/CalendarView#201]

**Comment by huanghaibin-dev** [comment]
demo没有搞对齐，你可以自行调整WeekBar，例如你对日历设置calendar_padding,而不对周栏设置padding，那就对不齐，demo只是展示用法，提供自定义参考，看一下demo就知道怎么搞了

**Comment by DeveloperHu** [comment]
FrameLayout.LayoutParams weeParams = (FrameLayout.LayoutParams) this.mWeekBar.getLayoutParams();
        weeParams.setMargins(left, top,right, bottom);
        mWeekBar.setLayoutParams(weeParams);

用了个margin的 自己调整就好 谢谢大大的解答

**Comment by huanghaibin-dev** [comment]
自定义WeekBar，xml修改一下就可以了
