### ISSUE TITLE
请问如何多种标志？

### ISSUE THREAD

**Issue by DeveloperHu** [huanghaibin-dev/CalendarView#202]
例如 3号是原点  7号是右下角图片类似这种的

**Comment by huanghaibin-dev** [comment]
看solor包就知道了，或者Calendar类，有添加多事物标记的操作

**Comment by DeveloperHu** [comment]
solor的案例 不是一个日期多个标志吗？   我想123是一个标记 456的是另外的一个标记的话 也是Calendar类里面有吗？

**Comment by huanghaibin-dev** [comment]
随你设置scheme类型的，你像对1号设置什么类型，那完全是你业务该做的事，然后绘制的时候判断一下类型，这样就可以啊

**Comment by DeveloperHu** [comment]
ok
