### ISSUE TITLE
能不能设置日期不可点击

### ISSUE THREAD

**Issue by MrCoderZ** [huanghaibin-dev/CalendarView#203]

**Comment by huanghaibin-dev** [comment]
下个版本加上这个设置

**Comment by liudaohong** [comment]
下个版本 好久出呀

**Comment by huanghaibin-dev** [comment]
@liudaohong 这一两天吧，设计得考虑充分点，目前基本做出来了，待测试

**Comment by huanghaibin-dev** [comment]
已经发布，看单选模式demo

**Comment by liudaohong** [comment]
最新版本支持了 设置日期不可选择是吧

**Comment by huanghaibin-dev** [comment]
是的，仅支持单选模式，public void setOnCalendarInterceptListener(OnCalendarInterceptListener listener);  不支持默认模式的

**Comment by liudaohong** [comment]
那岂不是 我在仿照酒店那样选择范围就不能设置 不可选日期吗

**Comment by MrCoderZ** [comment]
我想设置日期全部不可点击是要返回day==1一直到day==31吗

**Comment by huanghaibin-dev** [comment]
@MrCoderZ return true即可

**Comment by huanghaibin-dev** [comment]
@liudaohong 你是要在多选模式下支持对吧，多选模式计划是在单选模式上扩展，当前还没支持多选模式

**Comment by MrCoderZ** [comment]
好的,,谢谢
