### ISSUE TITLE
月日历--默认选中日期--修改的问题？

### ISSUE THREAD

**Issue by and0202** [huanghaibin-dev/CalendarView#205]
你好，月日历状态，假如我选中了8月5日，我滑动到9月，默认会选中9月5日，这个默认选中的9月5日，有没有办法把它去掉呢？谢谢

**Comment by huanghaibin-dev** [comment]
设置单选模式即可，而且是9月1号

**Comment by and0202** [comment]
有没有办法 实现只选中8月5日，滑动时其他月份没有选中状态。再次点击时，才会变为选中状态呢。

**Comment by and0202** [comment]
谢谢你

**Comment by huanghaibin-dev** [comment]
<attr name="select_mode">
              <enum name="default_mode" value="0" />
              <enum name="single_mode" value="1" />
        </attr>
用这个attr即可，demo也有的

**Comment by and0202** [comment]
用的是这个，搞定了。谢谢
