### ISSUE TITLE
是否有收缩后的周日历滑动上一天和下一天的API

### ISSUE THREAD

**Issue by wang007kai** [huanghaibin-dev/CalendarView#206]
1，是否有收缩后的周日历滑动上一天和下一天的API？如果没有，需要怎么修改？
2，能否添加限制范围到具体某天的API？

**Comment by huanghaibin-dev** [comment]
@wang007kai 滑动上一天下一天，可以通过获取当前选中的日期，得到当前时间戳，然后+-一天的时间戳，得到上下天，调用scrollToCalendar API即可实现，框架目前没有提供这种功能，限制到某天的范围，目前还没提供

**Comment by wang007kai** [comment]
1，用scrollToCalendar在临临界值的时候比较麻烦（如果是1月1日，是不是还得判断上一年和上一年12月份的有多少天）；
2，如果要限制某天需要怎么修改，因为项目中比较急，所以麻烦了。

**Comment by huanghaibin-dev** [comment]
不需要判断啊，通过得到年月日，然后转化为时间戳，然后+-一天的时间：86400000，就可以了，日期计算不需要那么麻烦的，用系统的Calendar类几行代码即可搞定；
要限制某天的话，稍等一下吧，我发布个新版本，可以任意限制日期

**Comment by wang007kai** [comment]
好的，谢谢啦

**Comment by huanghaibin-dev** [comment]
可以了，看新版本单选模式的demo

**Comment by wang007kai** [comment]
好的，太给力了，🙏
