### ISSUE TITLE
你好，请问在 周/月 视图 下 ， 切换下 周/月 有没有对应的监听，返回当前显示的日期范围

### ISSUE THREAD

**Issue by longJJ2016** [huanghaibin-dev/CalendarView#209]

**Comment by longJJ2016** [comment]
我现在在自定义的周月视图里 获取绘制的日期，这样 感觉不太好，希望作者 优化下。。

**Comment by longJJ2016** [comment]
不是切换周月视图，是在 周/月 视图下  ，滚动到上 周/月 的一个监听。
我看到 api里  年 月  有  但周 好像没有

**Comment by longJJ2016** [comment]
还有个就是 获取 当前 视图 显示的日期范围。

**Comment by longJJ2016** [comment]
需求 就是 当 视图 滑动时，数据 跟随 当前显示的日期范围 联动，  
没有选中 某年某月某日

**Comment by huanghaibin-dev** [comment]
新版本支持了

**Comment by BDwuzhou** [comment]
3.6.7版本周视图日期切换监听，返回的一周数据始终都是今天所在的一周数据，而不是当前日历显示的数据
