### ISSUE TITLE
切换到周视图之后点击回到今天，是时间是错误的

### ISSUE THREAD

**Issue by WuMaoQiang** [huanghaibin-dev/CalendarView#213]
你好，在使用控件过程中发现月试图状态下，点击回到今日是正确可以选中今日的，可是在周视图状态下点击回到今日按钮，返回的日期是不正确的

**Comment by huanghaibin-dev** [comment]
什么版本？

**Comment by huanghaibin-dev** [comment]
发现了，由于我的疏忽，把getMinYearDay()当作getMaxYearDay()写了
