### ISSUE TITLE
可以取消联动效果吗？只需要周视图或者月视图，当做普通的view

### ISSUE THREAD

**Issue by YooTrepeat** [huanghaibin-dev/CalendarView#216]
项目中为了日历UI统一，只想引入一个依赖，当只想要周视图或者月视图的时候，取消联动效果，不设置内容id，当做普通的View；当需要联动效果的时候，再打开，并设置内容id。

**Comment by BruseDu** [comment]
我需要周视图就够了 怎么配置  每次都是默认的月视图
