### ISSUE TITLE
可否支援繁体中文

### ISSUE THREAD

**Issue by yccheok** [huanghaibin-dev/CalendarView#220]
在香港，台湾，澳门市场，都是用繁体中文。`calendar.getLunar()` 是否可回返繁体中文？谢谢。

**Comment by huanghaibin-dev** [comment]
可以的，我加上一份繁体配置

**Comment by yccheok** [comment]
谢谢。

**Comment by lhalcyon** [comment]
...这里其实有个建议, 最好是从应用层设置框架的语言 , 因为很多应用语言是自切换不随系统的.
