### ISSUE TITLE
在fragment里使用，调整成最大显示和最大字体，mContentView被导航栏挡住，只显示5行日历，上滑就会滑到顶部不见周视图了

### ISSUE THREAD

**Issue by zswlove** [huanghaibin-dev/CalendarView#221]

**Comment by huanghaibin-dev** [comment]
提供截图看看

**Comment by zswlove** [comment]
![screenshot_20180914-122654](https://user-images.githubusercontent.com/24449586/45010171-ad7e5a00-b03e-11e8-9852-7534072e04cc.png)
这个时候应该显示6行 但是下面挡住了，向上滑的时候就没有周视图了

**Comment by huanghaibin-dev** [comment]
手机屏幕太小啊，自己调日历项高度，嵌套scrollerview之类的

发自我的 iPhone

**Comment by zswlove** [comment]
现在调整的是手机的设置里的显示大小和字体的大小， 正常显示的时候 是没问题的，就是在这种极端设置上出问题了；是在日历控件最外层在套一层scrollerview? 只有这一种方式吗？

**Comment by zswlove** [comment]
调整了每一项的高度，像是正常了，要把日历全显示下后 就正常了
