### ISSUE TITLE
日期背景重复问题

### ISSUE THREAD

**Issue by philadelphia** [huanghaibin-dev/CalendarView#222]
当日历展开时选中的日期背景是有颜色的，但是折叠后当天背景也是有颜色的，但是滑动后，下个页面这个位置背景也是有颜色的，猜测可能是因为view复用造成的。比如10月8号（周一）背景是灰色的。滑动时10月15号（下周一）背景也是灰色的。

**Comment by huanghaibin-dev** [comment]
这是默认模式，切换会自动选择对应的日期，切换为单选模式就不会

**Comment by philadelphia** [comment]
好了，谢谢大神，做完项目后一定把你这个项目好好研究一下。太6了
