### ISSUE TITLE
大神你好，我想把日期下面的农历显示换成自定义文字，但找不到初始化的办法。。

### ISSUE THREAD

**Issue by zyw1995** [huanghaibin-dev/CalendarView#224]
例如，5/初六，能换成5/天气很好 ，这样的显示吗？用setSchemeDate绘制标志也是可以的，但是这样的话数据量太大了，感觉重复了两次数据赋值，想问问您有没有别的建议，感激不尽。

**Comment by huanghaibin-dev** [comment]
绘制都是交给你本身来做的，外来的数据源你要怎么绘制都可以，如果看不懂的话，就clone demo，很快就明白怎么用

**Comment by iielse** [comment]
正遇到一样的需求，正在导入撸主demo，感谢撸主。 撸主 会添加     显示或者不显示 农历的接口吗？ 不然外国人咋用这个？外国农历吗？

**Comment by huanghaibin-dev** [comment]
这个你得看一下demo，就会明白，没有显示或者不显示农历的API这种说法的，简单的说就是：要不要显示农历，你说了算，不是框架决定的

**Comment by panzhoutao** [comment]
下载源码，然后看simpleview的源码就可以

**Comment by iielse** [comment]
跪舔一波大佬， 非常感谢。 挺灵活的~ 基本所有场景全包括了。

**Comment by zksyp** [comment]
> 下载源码，然后看simpleview的源码就可以

我下载了demo，simple中的 农历还是有的。。请问你也是这样的吗？

**Comment by huanghaibin-dev** [comment]
@zksyp 不是说了吗，不要去绘制农历就行啊
