### ISSUE TITLE
请问如何拦截周视图WeekViewPager的滑动

### ISSUE THREAD

**Issue by cymok** [huanghaibin-dev/CalendarView#229]
![截图.png](https://user-images.githubusercontent.com/27819746/45399010-1423f900-b679-11e8-9c5e-83d169b635d8.png)
有没有提供相关api或者简单扩展修改的方法, 不改源码能实现吗

**Comment by huanghaibin-dev** [comment]
<attr name="month_view_scrollable" format="boolean" />
        
        <attr name="week_view_scrollable" format="boolean" />
        
        <attr name="year_view_scrollable" format="boolean" />

**Comment by cymok** [comment]
谢谢,看漏了

**Comment by cymok** [comment]
大哥你好~建议提供动态设置xxViewScrollable的api
现在用反射勉强实现动态修改的需求...
(是不是我没找到提供修改的方法)
