### ISSUE TITLE
周视图滑动时日历显示的数据不对

### ISSUE THREAD

**Issue by jinmei339** [huanghaibin-dev/CalendarView#23]
我们现在项目要用到类似的日历控件，要支持月视图和周视图，现在发现切换为周视图，日历的数据不对，可否知道什么时候可以修复

**Comment by huanghaibin-dev** [comment]
你好，当前版本还没开发周视图功能，下个版本会带上周视图

**Comment by jinmei339** [comment]
下个版本什么时候，我们中旬就要开始用了

**Comment by huanghaibin-dev** [comment]
@jinmei339 最新版本已经发布了，终于支持周视图了，抱歉来晚了，感谢支持
