### ISSUE TITLE
不支持调整大小么？  

### ISSUE THREAD

**Issue by 897902334** [huanghaibin-dev/CalendarView#24]
默认设置warp_content 太大了   但是我这是固定的dp后  底部就看不到了，   另外一种方法  我设置了 warp-content后  我试着设置margin边距让他变小，但是没反应   ， 请问这个怎么设置大小呢 ？   设置了大小底部就显示不全了。

**Comment by 897902334** [comment]
宽度是可以设置的，   就是设置了高度后   底部显示不出来了，

**Comment by huanghaibin-dev** [comment]
calendar_height：日历项高度   day_text_size ：天数文本大小  lunar_text_size：农历文本大小，如果需要完全自定义UI，需要继承BaseCalendarCardView，你可以自定义高度宽度，都可以

**Comment by 897902334** [comment]
@huanghaibin-dev    谢谢你，  这个库挺好得。
