### ISSUE TITLE
混淆打包后，日历不显示了

### ISSUE THREAD

**Issue by jiangqingbo** [huanghaibin-dev/CalendarView#25]
我在混淆打包后，添加和不添加下面的配置，日历页面都不显示
#日历控件
-dontwarn com.haibin.calendarview.**
-keep class com.haibin.calendarview.** {*;}

希望尽快处理下这个问题哈

**Comment by huanghaibin-dev** [comment]
@jiangqingbo 抱歉，忘记在README说明混淆了，加入以下配置即可，其它不需要，
最新3.0.1版本发布了，支持周视图了，谢谢支持
-keepclasseswithmembers class * {
    public <init>(android.content.Context);
}

**Comment by jiangqingbo** [comment]
好的，谢谢
