### ISSUE TITLE
setSchemeDate标记setLunar 无效

### ISSUE THREAD

**Issue by longa30** [huanghaibin-dev/CalendarView#252]
setSchemeDate标记setLunar 自定义无效

**Comment by huanghaibin-dev** [comment]
setSchemeDate是标记事务，只会让日期产生scheme事务，和农历节日什么的不会有关联，而且也不应该侵入到日期的逻辑进去

**Comment by longa30** [comment]
那我想在农历处标记自定义我该如何做。需要我该源码吗？

**Comment by huanghaibin-dev** [comment]
不需要啊，日历界面关键是看你怎么画，框架是不会影响到日历UI的，你可以在scheme自定义一个类型，代表要自定义农历，然后绘制的时候，看看这个scheme是否存在，把农历换掉即可，逻辑都是你自己控制的

**Comment by huanghaibin-dev** [comment]
伪代码解释：canvas.drawText(schemeType == 替换农历？"换成你的文本" : calendar.getLunar());

**Comment by longa30** [comment]
以前setSchemeDate传的是List 现在新版本用的是map,我开始的时候一位key可以随意传值，这样会方便很多，结果显示不出来。排了很久的错，我现在有改回List了

**Comment by huanghaibin-dev** [comment]
框架本身就支持的

**Comment by longa30** [comment]
我目前测试的是calendar_content_view_id与RecyclerView关联可以上下滑动。我目前的思路就是onMonthChange事件和onCalendarSelect事件与RecyclerView进行联动。。

**Comment by huanghaibin-dev** [comment]
你的意思是切换日期，RecyclerView加载不同内容吗？

**Comment by longa30** [comment]
是的。

**Comment by huanghaibin-dev** [comment]
这种需求，只需监听日期切换事件onCalendarSelect即可，框架基本上都满足了各种各样的需求了，就看你想怎么用了

**Comment by longa30** [comment]
我的用法是onMonthChange来修改当前月份setSchemeDate。onCalendarSelect来加载日期的内容。我还碰到一个需求，我用其他方案代替了。就是只能用到1900年。这也是java中的calendar限制了吧
