### ISSUE TITLE
日历集成到自己项目里面，滑动日历卡顿问题

### ISSUE THREAD

**Issue by xyZangGit** [huanghaibin-dev/CalendarView#255]
我只把项目以module 的形式导入自己的项目中使用，然后把日历写到自己的xml文件中，在滑动日历的时候卡顿，提示我在主线程做太多的事情，但是demo就没有这个问题，下面是我引用的代码，我用的是中国风的日历，
![_20181010141217](https://user-images.githubusercontent.com/19574114/46716423-87c81e80-cc96-11e8-9c19-c3f6360574e6.png)
控制台提示我在主线程做太多的事情
![_20181010141409](https://user-images.githubusercontent.com/19574114/46716483-c5c54280-cc96-11e8-93dc-022bace4dbc1.png)
望告知是哪里的问题

**Comment by xyZangGit** [comment]
希望大大可以看一下我这个问题

**Comment by huanghaibin-dev** [comment]
你添加了什么耗时的拦截条件没有，或者使用了过渡绘制的API

**Comment by xyZangGit** [comment]
我只是把源码用module的方式引入就卡顿了，如果不是源码的方式，同样的布局就不会卡顿，上面是我的代码，只是引入方式不一样，demo也会有这个问题

**Comment by huanghaibin-dev** [comment]
卡顿肯定是自己代码的原因，这个得自己排查问题

**Comment by xyZangGit** [comment]
> 卡顿肯定是自己代码的原因，这个得自己排查问题

但是我的布局什么都没有的，只是显示这一个日历控件，我专门只写一个这个日历的demo，源码引入的方式确实卡顿，上面就是我demo的代码，全都是原封不用的，只是引入的方式变为导入源码的方式引入的

**Comment by huanghaibin-dev** [comment]
你周视图的路径写错了
