### ISSUE TITLE
你好CalendarView.java有2行代码顺序有误

### ISSUE THREAD

**Issue by ChenChengle** [huanghaibin-dev/CalendarView#26]
view.setItemHeight(mCalendarItemHeight);
view.setDayTextSize(mDayTextSize, mLunarTextSize);
这两行应该互换顺序。否则会因设置了自定义的文本大小CalendarView_day_text_size而无法计算出正确的文本mTextBaseLine。

**Comment by huanghaibin-dev** [comment]
这个是没有错误的，设置高度建议是在xml设置，最新版本已经发布了，终于支持周视图了，感谢支持
