### ISSUE TITLE
设置标志后getSelectedCalendar.hasScheme为null 

### ISSUE THREAD

**Issue by DeveloperHu** [huanghaibin-dev/CalendarView#268]
大大你好，这是一个很好的库不过我在使用时有点问题，望指导一下。
当我`  mCalendarView.setSchemeDate(map);`设置了标志后，想`mCalendarView.getSelectedCalendar().hasScheme()`。
根据是否有标记来改变我的布局状态。
但是这么获取的Calendar是空的，我应该怎么获取已经标记了的日期，或者说应该怎么查询已经标记的了日期？
@huanghaibin-dev 大大有空帮忙看看，十分感谢🙏

**Comment by huanghaibin-dev** [comment]
如果你用的是多选模式的话，不应该这么取，其他单选或者默认选择模式的话随意即可，目前还没遇到说getSelectedCalendar() == null的情况

**Comment by DeveloperHu** [comment]
单选的

**Comment by DeveloperHu** [comment]
3.40

**Comment by huanghaibin-dev** [comment]
用3.4.8就好

**Comment by DeveloperHu** [comment]
mCalendarView.setWeeMargin(0, 0, 0, 0);
@huanghaibin-dev  大大 我升级后 这个api替换成什么啊？

**Comment by huanghaibin-dev** [comment]
没有这个API了，删掉即可

**Comment by DeveloperHu** [comment]
更新后我自己的MonthView 显示never use了.日历的是默认布局

**Comment by huanghaibin-dev** [comment]
没问题的，你试试看就知道了

**Comment by DeveloperHu** [comment]
变成默认布局了 我在CustomMonthView里面打断点都不进入了。。

**Comment by huanghaibin-dev** [comment]
你检查一下路径、大小写对不对，还有记得要配置一下周视图路径

**Comment by huanghaibin-dev** [comment]
给配置一个默认的路径就行了，之后这里再改掉吧

**Comment by DeveloperHu** [comment]
`mCalendarView.setSchemeDate(map);`设置后
```
Calendar calendar = mCalendarView.getSelectedCalendar();
        String scheme = calendar.getScheme();
```
这时候scheme是"",一定要点击后scheme才是我设置的scheme
@huanghaibin-dev

**Comment by DeveloperHu** [comment]
🙏感谢大大
