### ISSUE TITLE
选中日期状态混乱

### ISSUE THREAD

**Issue by wlianghe00** [huanghaibin-dev/CalendarView#27]
月视图选中的日期，切换到周视图就变了

每个月都有一个初始化的1号默认选中吗？
整个日历的选中日期应该就是一个吧？

**Comment by huanghaibin-dev** [comment]
周视图马上就更新了，3.0.0版本默认只有一个选中日期，并没有切换默认选中1号，稍等10分钟发布新版本就完整支持周视图了

**Comment by wlianghe00** [comment]
3.0.2版本demo还是会混乱

**Comment by huanghaibin-dev** [comment]
@wlianghe00 怎么个混乱法，没有发现啊。。。

**Comment by huanghaibin-dev** [comment]
我明白了，应该是使用上的误区了，一个是日期切换改变，一个是用户点击，这两个事件被区分开了，我做个统一吧。
