### ISSUE TITLE
请问如何得到当前显示月份的所有天数，包含显示的前后月的日期？谢谢

### ISSUE THREAD

**Issue by xiaominglee4github** [huanghaibin-dev/CalendarView#271]

**Comment by huanghaibin-dev** [comment]
目前倒是没有这个API，后续可以考虑开放一下

**Comment by xiaominglee4github** [comment]
可以给个大概思路吗？我需要得到显示的日期范围~感谢~

**Comment by huanghaibin-dev** [comment]
MonthViewPager添加以下方法   
/**
     * 获取当前月份数据
     *
     * @return 获取当前月份数据
     */
    List<Calendar> getCurrentMonthCalendars() {
        BaseMonthView view = (BaseMonthView) findViewWithTag(getCurrentItem());
        if (view == null) {
            return null;
        }
        return view.mItems;
    }

CalendarView相应添加这个方法
 /**
     * 获取当前月份日期
     *
     * @return return
     */
    public List<Calendar> getCurrentMonthCalendars() {
        return mMonthPager.getCurrentMonthCalendars();
    }

**Comment by huanghaibin-dev** [comment]
```
MonthViewPager添加以下方法
/**
* 获取当前月份数据
*
* @return 获取当前月份数据
*/
List getCurrentMonthCalendars() {
BaseMonthView view = (BaseMonthView) findViewWithTag(getCurrentItem());
if (view == null) {
return null;
}
return view.mItems;
}

CalendarView相应添加这个方法
/**
* 获取当前月份日期
*
* @return return
*/
public List getCurrentMonthCalendars() {
return mMonthPager.getCurrentMonthCalendars();
}
```

**Comment by huanghaibin-dev** [comment]
暴力一点的就是直接用mCalnedarView,getMonthViewPager(); 得到MonthViewPager，再参考上面的代码

**Comment by xiaominglee4github** [comment]
好的，感谢~

**Comment by zengcanxiang** [comment]
@huanghaibin-dev 再baseView 定义的mItems，mDelegate，是package-private，除非引用源码，不然是无法获取这两个变量的
