### ISSUE TITLE
不能滑到周日历，月份可以滑动。

### ISSUE THREAD

**Issue by LiuSolomon** [huanghaibin-dev/CalendarView#278]
从月日历不能滑到周日历。只能月份左右滑动，周日历没显示出来。
 代码跟你的一样的。
 不知道为何
 希望大佬解释一下

**Comment by LiuSolomon** [comment]
应该是不能缩放。

**Comment by huanghaibin-dev** [comment]
要显示周视图，须用CalendarLayout，看README的详细介绍吧

**Comment by LiuSolomon** [comment]
> 要显示周视图，须用CalendarLayout，看README的详细介绍吧

这个我写了。

**Comment by LiuSolomon** [comment]
代码跟你的一模一样，我还把你的 代码跑起来了，唯一的区别就是，你的代码在Activity里面，而我的代码在Fragment里面，月份可以用，但是我想缩放回去，显示周日历却不行。我没有加你的那个Recycle控件。

**Comment by LiuSolomon** [comment]
` mTextMonthDay.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (!mCalendarLayout.isExpand()) {
                    mCalendarView.showYearSelectLayout(mYear);
                    return;
                }
                mCalendarView.showYearSelectLayout(mYear);
                mTextLunar.setVisibility(View.GONE);
                mTextYear.setVisibility(View.GONE);
                mTextMonthDay.setText(String.valueOf(mYear));
            }
        });
        view.findViewById(R.id.fl_current).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mCalendarView.scrollToCurrent();
            }
        });`

**Comment by LiuSolomon** [comment]
[](url)
