### ISSUE TITLE
建议 Calendar 中增加农历颜色或类型

### ISSUE THREAD

**Issue by hao-li** [huanghaibin-dev/CalendarView#28]
当前 LunarCalendar.getLunarText 中返回的字串有数种类型
希望能对不同类型的内容显示不同颜色，所以建议 Calendar 中增加农历颜色或类型

**Comment by huanghaibin-dev** [comment]
农历这个是逻辑实现的，每个人都有不同的需求，不同农历不同颜色这种设计不应该又框架来提供，当然你可以自定义UI，然后做个静态配置，对特定的农历标记不同的颜色

**Comment by hao-li** [comment]
感谢快速回复，我的考虑是这样的：

目前框架提供的 lunar 实际上由 solar、term、festival、或 numToChinese 等不同类型构成。
不同颜色、不同事件处理等虽然属于具体业务层逻辑，但是识别 lunar 的实际类型应该属于通用的功能。
如果框架可以直接提供的话，应该会使框架更加方便、强大。

**Comment by huanghaibin-dev** [comment]
@hao-li 你是这个意思啊，对传统节日、24节气、公历定义的节日做个区分对吧，这种应该是属于框架范畴的，的确可以考虑，目前倒是还不太建议增加

**Comment by hao-li** [comment]
是这个意思，如果框架做了区分的话，就不用上层业务自行解析了；）

**Comment by lbx2015** [comment]
我现在也有这个需求，美工给我标注了不同的农历颜色，24节气是一个颜色。元旦这样的一个颜色，有demo吗？

**Comment by huanghaibin-dev** [comment]
@lbx2015 Calendar里面有单独的api getSolarTerm();  getGregorianFestival(); 等，自行判断一下不为空，就是对应的二十四节气、公历节日等，然后自定义画笔，用对应的画笔即可。
