### ISSUE TITLE
CalendarLayout listener for status expanded/shrinked

### ISSUE THREAD

**Issue by curiousily** [huanghaibin-dev/CalendarView#280]
Hey,

Is there a way to listen for changes between the status/state of the CalendarLayout? Something like `CalendarLayout.onChange(isExpanded: Boolean)`?

Thanks!

**Comment by tjouin** [comment]
I'am looking for that listener is it already implemented ?

**Comment by tjouin** [comment]
@curiousily

**Comment by AmolVJ** [comment]
@curiousily @tjouin I am also looking for same. Is it available?
