### ISSUE TITLE
CalendarView中有设置默认选中日期的方法吗？

### ISSUE THREAD

**Issue by TZ-TimZhang** [huanghaibin-dev/CalendarView#291]
您好~CalendarView是一个强大的库，我目前有一个需求，首次进入页面的时候要设置一个默认的时间，我没有找到这个方法，现在每次进入页面都会默认选中今天。有什么办法解决吗？

**Comment by huanghaibin-dev** [comment]
CalendarView.scrollToxxx 这一些列的API可以实现

**Comment by TZ-TimZhang** [comment]
哦哦 好的感谢！

**Comment by malinkang** [comment]
不知道是我没仔细看文档，还是文档里没有写。找了一个小时，看源码，搜issue，终于找到解决方案。
