### ISSUE TITLE
疑问：在使用过程中有这样一个现象，感觉像是bug。

### ISSUE THREAD

**Issue by hy1250** [huanghaibin-dev/CalendarView#3]
在使用过程中，如果我在3月份点击了某一天，这一天底色会改变，然后我翻到4月份，点击某一天，这一天底色也会变。但是再次返回3月份，发现3月份的那一天仍然处于被选中状态（底色改变中）。然而我在3月份点击后，翻到5月份点击就不会出现两个月中的某一天都处于被选中状态

**Comment by huanghaibin-dev** [comment]
@hy1250 你好，这不是bug啊，ViewPager默认最多会维持三个item，如果当前是4月，4月选中一天翻到5月再选中一天，此时维持的状态是4、5、6月，往4月翻，4月份的状态依然是维持的，魅族的日历是默认滚动都是让1号为选中状态的，当然如果不想使用这个状态，让选中颜色透明即可。

**Comment by hy1250** [comment]
@huanghaibin-dev 明白了，谢谢指教！希望这个项目越做越好，越来越多人看到并用到。

**Comment by huanghaibin-dev** [comment]
@hy1250 谢谢支持，我会尽快把节假日全加上去的，更加完善这个项目
