### ISSUE TITLE
Min or Max Date validation

### ISSUE THREAD

**Issue by bharatlagad** [huanghaibin-dev/CalendarView#31]
Hello,

have  you provided some way to set min max date programmatically.

**Comment by huanghaibin-dev** [comment]
yes, to use CalendarView attrs, for example: app:min_year="2004" and app:max_year="2050"

**Comment by bharatlagad** [comment]
want to set min date like 09/12/2017 and max date like 12/02/2017 is it possible to set programatically.

**Comment by huanghaibin-dev** [comment]
@bharatlagad this function is not available now. I can provide this function next Monday, you‘ d better wait for two days.

**Comment by bharatlagad** [comment]
@huanghaibin-dev  OK thank you

**Comment by bharatlagad** [comment]
Hello,

Have you done with Min Max date?

**Comment by huanghaibin-dev** [comment]
Hello, please wait a moment, I'm testing it.

**Comment by bharatlagad** [comment]
OKAY THANKS

**Comment by huanghaibin-dev** [comment]
@bharatlagad Hello, It's done

**Comment by bharatlagad** [comment]
Thanks a lot.

**Comment by bharatlagad** [comment]
can we set min date max date programatically except xml.

**Comment by huanghaibin-dev** [comment]
@bharatlagad OK, Let me try.

**Comment by bharatlagad** [comment]
@huanghaibin-dev OK

**Comment by bharatlagad** [comment]
Hello sir,

Have you done with min max date?

**Comment by huanghaibin-dev** [comment]
I'm sorry. I'm busy these days. I can finish it this afternoon.

**Comment by bharatlagad** [comment]
Okay,no problem.

**Comment by huanghaibin-dev** [comment]
@bharatlagad Hello, It's done, to use api CalendarView.setRange(int minYear, int minYearMonth,
                         int maxYear, int maxYearMonth)

**Comment by bharatlagad** [comment]
@huanghaibin-dev Thanks a lot...
can you please send me... linkedin profile link.

**Comment by huanghaibin-dev** [comment]
Sorry. I have no linkedin account. In china, very few programmer use linkedin. I work in open source china(https://my.oschina.net/huanghaibin).

**Comment by bharatlagad** [comment]
i don't know Chinese...

**Comment by huanghaibin-dev** [comment]
haha, we can contact each other via github or email.

**Comment by bharatlagad** [comment]
ok sure bharat.lagad@gmail.com. I don't have much experience but i am interested to work with you.

**Comment by bharatlagad** [comment]
Hello 
There is small mistake  in Delegate class in setRange method min and max month assign to max month

**Comment by bharatlagad** [comment]
Sorry my English

**Comment by huanghaibin-dev** [comment]
Never mind.  please tell me the line.

**Comment by bharatlagad** [comment]
Class CustomCalendarViewDelegate
line-214
