### ISSUE TITLE
calendarLayout中使用recyclerview,出现 显示不全的问题

### ISSUE THREAD

**Issue by carolinachung** [huanghaibin-dev/CalendarView#313]
recyclerview总是显示不出最后一条数据

**Comment by steven-gao** [comment]
同问，我也出现这个问题了，就是在日历上面添加了一定高度的布局。

**Comment by carolinachung** [comment]
已经解决,修改calendarlayout计算contentview高度的方法,就可以了

**Comment by chenyabingsuny** [comment]
> 已经解决,修改calendarlayout计算contentview高度的方法,就可以了

你好这个显示不全问题 你是如何修改的？

**Comment by steven-gao** [comment]
thanks a lot ,although i am been Job-hopping
