### ISSUE TITLE
月视图为mode_only_current模式下在dialog中滑动卡顿

### ISSUE THREAD

**Issue by lifuyuan123** [huanghaibin-dev/CalendarView#319]
月视图模式为仅显示当月，将日历放在FragmentDialog中，左右滑动日历。当日历前后一个月的行数不一致时，由于动态计算高度原因会出现卡顿情况。在Acitivity和Fragment中没有此现象。可否提供一个方法实现左右滑动效果和scrollToCalendar（）一样切换视图。

**Comment by huanghaibin-dev** [comment]
放Dialog仅可能不要用仅显示当月模式，如果要用的画，用Activity Dialog样式，让根布局全屏半透明即可

**Comment by lifuyuan123** [comment]
@huanghaibin-dev 试了下，只要让父布局全屏就不会卡顿，已解决，谢谢大神。

**Comment by Attect** [comment]
试了一下Activity Dialog模式，会鬼畜……

**Comment by huanghaibin-dev** [comment]
要注意Parent Layout的高度，Parent Layout match就没事

发自我的 iPhone

**Comment by licoba** [comment]
> @huanghaibin-dev 试了下，只要让父布局全屏就不会卡顿，已解决，谢谢大神。

请问一下具体是怎样操作的？？

**Comment by licoba** [comment]
> 月视图模式为仅显示当月，将日历放在FragmentDialog中，左右滑动日历。当日历前后一个月的行数不一致时，由于动态计算高度原因会出现卡顿情况。在Acitivity和Fragment中没有此现象。可否提供一个方法实现左右滑动效果和scrollToCalendar（）一样切换视图。

请问一下具体是怎么解决这个问题的？？

**Comment by wuh876** [comment]
请问怎么解决的？
<com.haibin.calendarview.CalendarLayout
        android:id="@+id/calendar_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
这样吗
