### ISSUE TITLE
Mr huanghaibin,你好，我的activity怎么把数据传递给自定义的monthview？期待您的回复

### ISSUE THREAD

**Issue by steven-gao** [huanghaibin-dev/CalendarView#323]
Mr huanghaibin,你好，我的activity怎么把数据传递给自定义的monthview？比如我的activity有一个月的数据，而monthview正好需要这一个月数据对比，怎么传递啊？期待您的回复

**Comment by steven-gao** [comment]
@cuixbo 确实是啊，拿不到monthview对象啊

**Comment by EpicWang** [comment]
我也遇到这个问题了，请问下怎么解决？ @steven-gao @cuixbo @huanghaibin-dev

**Comment by Xiuz-Hmy** [comment]
> 我也遇到这个问题了，请问下怎么解决？@ steven-gao @cuixbo @ huanghaibin-dev

SimpleMonthView monthView = mCalendarView.getMonthViewPager().findViewWithTag(mCalendarView.getMonthViewPager().getCurrentItem());
