### ISSUE TITLE
如何设定初始状态为周

### ISSUE THREAD

**Issue by cuixbo** [huanghaibin-dev/CalendarView#326]
现在默认展示的是月视图，如何设定默认展示位周视图。
如果一开始调用mCalendarLayout.shrink()会有问题。

**Comment by cuixbo** [comment]
> 如果用代码，记得用post即可

用post会出现切换动画，这是交互不期望的。
上周末已经找到xml中的静态设置了，但还是期望最好能够提供动态设置的方法。

**Comment by blle** [comment]
xml里怎么设置呢。我设了没起作用

**Comment by yixinyuan** [comment]
CalendarLayout  app:default_status="shrink" 这样就默认是周日历了

**Comment by Trammels** [comment]
Fragment中scrollView 里面有其他的内容，设置app:calendar_show_mode="only_week_view"，偶尔会错乱

**Comment by huanghaibin-dev** [comment]
@Trammels  scrollView不宜嵌套日历

**Comment by Trammels** [comment]
<com.haibin.calendarview.CalendarLayout
        android:visibility="gone"
        android:id="@+id/calendarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#fff"
        android:orientation="vertical"
        app:calendar_content_view_id="@+id/nestedScrollView"
        app:calendar_show_mode="only_week_view"
        app:default_status="shrink"
        >
        
        <com.haibin.calendarview.CalendarView
            android:id="@+id/calendarView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#fff"
            app:calendar_padding="10dp"
            app:current_day_lunar_text_color="#ff0000"
            app:current_day_text_color="#ff0000"
            app:current_month_lunar_text_color="#CFCFCF"
            app:current_month_text_color="#333333"
            app:lunar_text_size="10sp"
            app:max_year="2030"
            app:max_year_day="31"
            app:max_year_month="12"
            app:min_year="2017"
            app:min_year_day="1"
            app:min_year_month="1"
            app:month_view="com.mls.publicrms.custom.CustomMonthView"
            app:month_view_show_mode="mode_only_current"
            app:other_month_lunar_text_color="#e1e1e1"
            app:other_month_text_color="#e1e1e1"
            app:scheme_lunar_text_color="#FF00FF"
            app:scheme_text="假"
            app:scheme_text_color="#00FFFF"
            app:scheme_theme_color="#FFFF00"
            app:selected_lunar_text_color="#FFFFFF"
            app:selected_text_color="#FFFFFF"
            app:selected_theme_color="#6397EB"
            app:week_background="#fff"
            app:week_bar_height="46dp"
            app:week_bar_view="com.mls.publicrms.custom.CustomWeekBar"
            app:week_line_background="#00000000"
            app:week_line_margin="16dp"
            app:week_start_with="mon"
            app:week_text_size="10sp"
            app:week_view="com.mls.publicrms.custom.CustomWeekView"
            app:year_view_background="#f6f6f6"
            app:year_view_day_text_color="#333333"
            app:year_view_day_text_size="8sp"
            app:year_view_month_text_color="#ff0000"
            app:year_view_month_text_size="20sp"
            app:year_view_scheme_color="#f17706"
            app:year_view_week_height="0dp"
            app:year_view_week_text_color="#666666"
            app:year_view_week_text_size="7sp"/>

        <android.support.v4.widget.NestedScrollView
            android:id="@+id/nestedScrollView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="@dimen/x20">

            <LinearLayout

                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal"
                    android:paddingLeft="@dimen/x32"
                    android:paddingRight="@dimen/x32">

                    <Button
                        android:id="@+id/btn_maintain_task"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/x64"
                        android:layout_weight="1"
                        android:background="@drawable/shape_blue_bg1"
                        android:text="维护任务"
                        android:textColor="@color/white"
                        android:textSize="@dimen/text_big_size"/>

                    <Button
                        android:id="@+id/btn_spot_check"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/x64"
                        android:layout_weight="1"
                        android:background="@drawable/shape_gray_bg1"
                        android:text="点检任务"
                        android:textColor="@color/button_blue"
                        android:textSize="@dimen/text_big_size"/>


                </LinearLayout>


                <android.support.v7.widget.RecyclerView
                    android:id="@+id/rv_list"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginLeft="@dimen/x20"
                    android:layout_marginRight="@dimen/x20"
                    />


            </LinearLayout>
        </android.support.v4.widget.NestedScrollView>
    </com.haibin.calendarview.CalendarLayout>

这种写法，设置默认周日历的时候，下面的button偶尔会到达顶部的位置，就像日历好像没有绘制完成一样

**Comment by Trammels** [comment]
好像是我代码设置的问题，在xml和代码中都设置shrink 偶尔会导致嵌套在CalendarLayout的控件上移到初始位置，就好像日历没有绘制完成，在CalendarLayout的控件已经显示了。代码如下。
 <com.haibin.calendarview.CalendarLayout
        android:visibility="gone"
        android:id="@+id/calendarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#fff"
        android:orientation="vertical"
        app:calendar_content_view_id="@+id/nestedScrollView"
        app:calendar_show_mode="only_week_view"
        app:default_status="shrink"
        >
        
        <com.haibin.calendarview.CalendarView
            android:id="@+id/calendarView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#fff"
            app:calendar_padding="10dp"
            app:current_day_lunar_text_color="#ff0000"
            app:current_day_text_color="#ff0000"
            app:current_month_lunar_text_color="#CFCFCF"
            app:current_month_text_color="#333333"
            app:lunar_text_size="10sp"
            app:max_year="2030"
            app:max_year_day="31"
            app:max_year_month="12"
            app:min_year="2017"
            app:min_year_day="1"
            app:min_year_month="1"
            app:month_view="com.mls.publicrms.custom.CustomMonthView"
            app:month_view_show_mode="mode_only_current"
            app:other_month_lunar_text_color="#e1e1e1"
            app:other_month_text_color="#e1e1e1"
            app:scheme_lunar_text_color="#FF00FF"
            app:scheme_text="假"
            app:scheme_text_color="#00FFFF"
            app:scheme_theme_color="#FFFF00"
            app:selected_lunar_text_color="#FFFFFF"
            app:selected_text_color="#FFFFFF"
            app:selected_theme_color="#6397EB"
            app:week_background="#fff"
            app:week_bar_height="46dp"
            app:week_bar_view="com.mls.publicrms.custom.CustomWeekBar"
            app:week_line_background="#00000000"
            app:week_line_margin="16dp"
            app:week_start_with="mon"
            app:week_text_size="10sp"
            app:week_view="com.mls.publicrms.custom.CustomWeekView"
            app:year_view_background="#f6f6f6"
            app:year_view_day_text_color="#333333"
            app:year_view_day_text_size="8sp"
            app:year_view_month_text_color="#ff0000"
            app:year_view_month_text_size="20sp"
            app:year_view_scheme_color="#f17706"
            app:year_view_week_height="0dp"
            app:year_view_week_text_color="#666666"
            app:year_view_week_text_size="7sp"/>

        <android.support.v4.widget.NestedScrollView
            android:id="@+id/nestedScrollView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginTop="@dimen/x20">

            <LinearLayout

                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal"
                    android:paddingLeft="@dimen/x32"
                    android:paddingRight="@dimen/x32">

                    <Button
                        android:id="@+id/btn_maintain_task"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/x64"
                        android:layout_weight="1"
                        android:background="@drawable/shape_blue_bg1"
                        android:text="维护任务"
                        android:textColor="@color/white"
                        android:textSize="@dimen/text_big_size"/>

                    <Button
                        android:id="@+id/btn_spot_check"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/x64"
                        android:layout_weight="1"
                        android:background="@drawable/shape_gray_bg1"
                        android:text="点检任务"
                        android:textColor="@color/button_blue"
                        android:textSize="@dimen/text_big_size"/>


                </LinearLayout>


                <android.support.v7.widget.RecyclerView
                    android:id="@+id/rv_list"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginLeft="@dimen/x20"
                    android:layout_marginRight="@dimen/x20"
                    />


            </LinearLayout>
        </android.support.v4.widget.NestedScrollView>
    </com.haibin.calendarview.CalendarLayout>
