### ISSUE TITLE
作者您好，请问怎样清除选择的日期，源码修改大概在哪个地方，希望能得到您的指点，谢谢

### ISSUE THREAD

**Issue by Mad-YX** [huanghaibin-dev/CalendarView#327]
需求中需要首次进入的时候没有默认选择；选择后，切换月份会显示当月的数据，然后之前的选择会取消；源码里找了很久，希望能得到您的回复；

**Comment by Mad-YX** [comment]
> 下个版本就可以支持了，之前忽略了这个需求

可以问下您下个版本的大概发布时间嘛？

**Comment by huanghaibin-dev** [comment]
今天发布吧，近期没什么时间去改进

**Comment by huanghaibin-dev** [comment]
已经完成，请用最新版即可
