### ISSUE TITLE
滑动中优先X

### ISSUE THREAD

**Issue by clxy** [huanghaibin-dev/CalendarView#330]
你好，
（先👍一个，整个Github里最牛叉的Android日历控件！）

如题，想请教下如何在滑动中优先X方向。
比如，
斜上30度角滑动时，不进行周/月视图切换；
斜上60度角滑动时，则进行视图切换。

源代码看下来，貌似只判断Y方向是否有位移。

如果实现这个需求，不知道下面的方案是否可行，
- 在onTouchEvent方法中，
    - 计算Y方向位移时，同时计算X方向位移，
    - 计算X，Y夹角，超过某个阈值时，切换视图
- onInterceptTouchEvent方法貌似不用修改？

请赐教！
多谢

**Comment by clxy** [comment]
你好，
（先👍一个，整个Github里最牛叉的日历控件！）

如题，请教下如何在滑动中优先X方向。
比如，
斜上30度角滑动时，不进行周/月视图切换；
斜上60度角滑动时，则进行视图切换

源代码看下来，貌似只判断Y方向如果有位移。
不知道下面的方案是否可行，
- 在onTouchEvent方法中，计算Y方向位移时，同时计算X方向位移，
计算X，Y夹角，超过某个阈值时，切换视图

- onInterceptTouchEvent方法貌似不用修改？

请赐教！
多谢

**Comment by huanghaibin-dev** [comment]
目前是只要产生了y移动，就会随手势平移了，至于说要判断夹角超过某个阈值才切换，这是不可取的，如果APP是水平视图的，那夹角就会非常小，但是y平移却已经解决最大值了，这时是必须切换视图的，所以只能判断y平移了多少再进行视图切换，而不应该是夹角大小

**Comment by clxy** [comment]
多谢回复。

自己的app里面也用到了coordinatorlayout，发现它也貌似只判断Y方向（不是很确定，或者Y方向优先权很高）...

不好意思，追问下，如果要实现的话，上面的方案是否可取？

多谢

**Comment by huanghaibin-dev** [comment]
上面的方案是不可行的，一般只需要在action_up判断移动的y最大距离超过即可某个阈值即可

**Comment by clxy** [comment]
多谢
