### ISSUE TITLE
您好前辈，关于设置了时间范围过后，首次进入的默认选中时间变成了最大的那一天

### ISSUE THREAD

**Issue by GuoLiangjun123** [huanghaibin-dev/CalendarView#354]
如题，望指点。

**Comment by huanghaibin-dev** [comment]
日历有几种模式，默认模式为跟手机自带日历一样的操作，切换月份会自动选择第一天，单选和多选模式则不会

**Comment by GuoLiangjun123** [comment]
哇，谢谢前辈，么么哒！

**Comment by GuoLiangjun123** [comment]
> 日历有几种模式，默认模式为跟手机自带日历一样的操作，切换月份会自动选择第一天，单选和多选模式则不会

谢谢前辈抽时间解答，但是我还有两个问题，游览了您给出来的教程和demo过后都不知道在什么地方去解决，所以不好意思再麻烦您一下。  1. 范围以外的日期设置为灰色。   2.选中的背景是黄色的圆形底。

**Comment by huanghaibin-dev** [comment]
@Override
    protected boolean onDrawSelected(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme) {
        int cx = x + mItemWidth / 2;
        int cy = y + mItemHeight / 2;
        canvas.drawCircle(cx, cy, mRadius, mSelectedPaint);
        return true;
    }
这里绘制选中效果

**Comment by huanghaibin-dev** [comment]
@Override
    protected void onDrawText(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme, boolean isSelected) {
        boolean isInRange = isInRange(calendar);
        这里判断是不是在范围内，给Paint换个颜色或者直接换个Paint即可
}

**Comment by huanghaibin-dev** [comment]
不客气

**Comment by GuoLiangjun123** [comment]
> 不客气

前辈，如果使用可以收缩的日历形式的话，日历下面是一个网格布局RecyclerView，我用原生的rv来和您的作品联用会导致我自己的rv不显示。看了您的demo后，想问问用您的RecyclerViewGroup的话可以实现网格布局吗。

**Comment by huanghaibin-dev** [comment]
任意View都行的，要看你怎么用CalendarLayout，一般都是使用不对造成的

**Comment by huanghaibin-dev** [comment]
你改了MonthView就一起改了WeekView

**Comment by GuoLiangjun123** [comment]
> 你改了MonthView就一起改了WeekView
这样啊原来是！ 谢谢前辈，新年快乐!

**Comment by huanghaibin-dev** [comment]
不会的，你给recyclerview添加个背景

**Comment by GuoLiangjun123** [comment]
> 不会的，你给recyclerview添加个背景

加了的，日历背景和rv不是同一个颜色，折叠上去的时候就是有一截日历背景的颜色

**Comment by huanghaibin-dev** [comment]
贴上截图看看

**Comment by GuoLiangjun123** [comment]
> 贴上截图看看

不好意思哈前辈，昨天开会去了。。。如果您方便的话可以加一下QQ 吗，给您看看录屏。1260321778
