### ISSUE TITLE
请问 CalendarView 是如何处理好 configuration change？

### ISSUE THREAD

**Issue by yccheok** [huanghaibin-dev/CalendarView#355]
在月视图是，如果我把手机转了转，我发现原来被选择的月和年，还是能保持不变。

我预期能在 `CalendarView`，或 `MonthViewPager` 看到 `onSaveInstanceState`。可是并没寻到。可以问问，`CalendarView` 是如何处理好 configuration change？

**Comment by huanghaibin-dev** [comment]
现在新版本为CalendarView和CalendarLayout加上了onSaveInstanceState了，但onSaveInstanceState并不会因为configuration change而调用，如果你要处理onSaveInstanceState，请到开发者模式开启不保留活动activity，就能如期测试onSaveInstanceState

**Comment by yccheok** [comment]
那，您是否知道为何在旧版本（没有onSaveInstanceState） 当我旋转手机，CalendarView 的月视图能还原之前被选择的月和年？

黄海彬 <notifications@github.com> 於 2019年1月16日 週三 下午1:48寫道：

**Comment by yccheok** [comment]
奇怪。我并没做那样的设置。我的 activity 和 fragment 都会重建

黄海彬 <notifications@github.com> 於 2019年1月16日 週三 下午2:22寫道：

**Comment by huanghaibin-dev** [comment]
会重建都能保持选中日期不变，这个不太科学

**Comment by yccheok** [comment]
我做了些粗糙的测试。

我的猜想是 MonthViewPager 有把她现在 page position 用 onSavedInstance 收藏及复原。（原本 ViewPager 就有这项特性）

这样，onPageSelected 会被呼叫，根据 page position 得到 calendar，再把 calendar 传给 WeekBar。
