### ISSUE TITLE
类型转换可能出现缺失

### ISSUE THREAD

**Issue by JNYoung** [huanghaibin-dev/CalendarView#356]
private static final double GXC_L[] = {280.4664567 / ANGLE_PER_RAD,
            36000.76982779 / ANGLE_PER_RAD, 0.0003032028 / ANGLE_PER_RAD, 1 / 49931000 / ANGLE_PER_RAD,
            -1 / 153000000 / ANGLE_PER_RAD};中的1 / 49931000 / ANGLE_PER_RAD部分因为1为int，所以可能会出现类型缺失，严谨点的写法应该如下
private static final double GXC_L[] = {280.4664567 / ANGLE_PER_RAD,
            36000.76982779 / ANGLE_PER_RAD, 0.0003032028 / ANGLE_PER_RAD, (double)1 / 49931000 / ANGLE_PER_RAD,
            (double)-1 / 153000000 / ANGLE_PER_RAD};

**Comment by huanghaibin-dev** [comment]
好的，谢谢支持，java如果 int/double or float会自动将 int隐式转为double or float再进行算术运算的，这里强制或者非强制都没有问题，严谨点好。
