### ISSUE TITLE
如何给每一天绘制一个背景？

### ISSUE THREAD

**Issue by mmengchen** [huanghaibin-dev/CalendarView#359]

**Comment by huanghaibin-dev** [comment]
onDrawText回调里面，随意画背景

**Comment by mmengchen** [comment]
绘制一张图片也是可以的吗？？

**Comment by huanghaibin-dev** [comment]
drawBitmap 这个API了解清楚即可，你会用Canvas画什么，都可以

**Comment by mmengchen** [comment]
我根本就不懂canvas 啊，没有菜鸟版的么直接通过代码设置背景图片的功能么？

**Comment by huanghaibin-dev** [comment]
没有，框架只提供基础坐标、日期、逻辑运算，至于UI方面，都是只用最原生的Canvas操作的，打开demo一看自然就明白如何操作Canvas了，一点也不难，相当于框架提供了一张白纸，至于你能在白纸上画的多漂亮，那就得看审美了

**Comment by mmengchen** [comment]
好的，了解啦

**Comment by langrenfengzi** [comment]
onDrawText里画背景会覆盖掉之前在onDrawSelected / onDrawScheme 里画的东西，这样只能把画的全部逻辑都放到onDrawText里了。
