### ISSUE TITLE
嗯嗯，是否必须重写月视图和周视图？demo里面能直接用吗？

### ISSUE THREAD

**Issue by StriveCheng** [huanghaibin-dev/CalendarView#36]
日历很棒，感谢开源，已star

**Comment by huanghaibin-dev** [comment]
@StriveCheng 可以用自带的实现，也可以直接使用demo的效果，我把高仿魅族的设置为自带的了，源码中为DefaultMonthView和DefaultWeekView，如果这个效果满足你的需求，可以不需要自己实现，如果你们的需求是另外的UI，那你可以参考demo的实现，逻辑和坐标系都已经提供，只需要绘制你需要的效果即可，很简单的

**Comment by StriveCheng** [comment]
好的，谢谢，能否加个联系方式，qq或者微信？

**Comment by StriveCheng** [comment]
xcc2734，这是我微信号，希望您能加一下，方便交流
