### ISSUE TITLE
请问如何制作竖直的日历列表？

### ISSUE THREAD

**Issue by LLQQHH** [huanghaibin-dev/CalendarView#360]
类似于这样的！
![image](https://user-images.githubusercontent.com/19651932/51437131-a9dd2e00-1cd4-11e9-8abe-dc98cafef7b6.png)

**Comment by huanghaibin-dev** [comment]
得自行去改源码，如果阅读了源码，不难，把MonthViewPager换RecyclerView即可

**Comment by LLQQHH** [comment]
哦，好吧谢谢，前辈在问一下，新版本里面有没有解决默认每个月选中第一天的bug！

**Comment by huanghaibin-dev** [comment]
不是bug啊，日历有四种模式，默认模式会切换会自动选中第一天，参考手机自带的日历，一样的，单选模式应该就是你想要的模式，另外还有多选、范围选，可以代码或者xml配置，select_mode

**Comment by LLQQHH** [comment]
好的知道了，再次感谢！如果你demo里面能有垂直的列表，类似于RecycleView的形式，那就更完美了！

**Comment by huanghaibin-dev** [comment]
demo跟libs没什么关系，只是列举几种定制方式，方便使用，后续有空我在制作一个RecycleView的看看

**Comment by LLQQHH** [comment]
嗯，好的，您有空的时候，可以试试看，再次感谢！

**Comment by stonebirds** [comment]
> 类似于这样的！
> ![image](https://user-images.githubusercontent.com/19651932/51437131-a9dd2e00-1cd4-11e9-8abe-dc98cafef7b6.png)

你现在这个做出来没有啊，有没有demo提供一下啊，谢谢

**Comment by michaellee123** [comment]
我又fork一遍，加了个标题吸顶😄
