### ISSUE TITLE
3.5.1版本中显示为周视图时不会默认选中！

### ISSUE THREAD

**Issue by actionbar** [huanghaibin-dev/CalendarView#371]
配置文件
`<FrameLayout
                android:layout_width="match_parent"
                android:layout_height="67dp"
                android:layout_marginTop="5dp">

                <com.haibin.calendarview.CalendarLayout
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:background="@android:color/transparent"
                    android:orientation="vertical"
                    app:calendar_content_view_id="@+id/fl_choose_date_calendar_content_area"
                    app:calendar_show_mode="only_week_view"
                    app:default_status="shrink">

                    <com.haibin.calendarview.CalendarView
                        android:id="@+id/cv_choose_date_calendar"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:background="@android:color/transparent"
                        app:calendar_height="50dp"
                        app:current_day_lunar_text_color="#666"
                        app:current_day_text_color="#666"
                        app:current_month_lunar_text_color="#666"
                        app:current_month_text_color="#666"
                        app:day_text_size="13sp"
                        app:lunar_text_size="10sp"
                        app:min_year="2010"
                        app:month_view_show_mode="mode_fix"
                        app:other_month_lunar_text_color="#666"
                        app:other_month_text_color="#666"
                        app:scheme_text="假"
                        app:scheme_text_color="#333"
                        app:scheme_theme_color="#333"
                        app:select_mode="single_mode"
                        app:selected_lunar_text_color="@color/white"
                        app:selected_text_color="@color/white"
                        app:selected_theme_color="@color/colorAccent"
                        app:week_background="@color/white"
                        app:week_bar_height="17dp"
                        app:week_start_with="sun"
                        app:week_text_color="#666"
                        app:week_text_size="12sp" />

                    <FrameLayout
                        android:id="@+id/fl_choose_date_calendar_content_area"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:background="#d4d4d4" />
                </com.haibin.calendarview.CalendarLayout>
            </FrameLayout>
`

**Comment by huanghaibin-dev** [comment]
3.5.0版本开始，single_mode不再默认选择当前日期，也就是没有选择状态，比较适合单选的逻辑，可自行调用scrollerToXXX，

**Comment by actionbar** [comment]
感谢解惑，在提问时我也是调用scrollerToXXX来解决的，只是有疑问而已，谢谢！

**Comment by huanghaibin-dev** [comment]
不客气

**Comment by mengzhe1973** [comment]
日历可以默认选择的日期么，如果上次选择的是一天，再次弹起日历，那一天显示已经选中，如果是范围，再次弹起的时候日期范围已经展示选中
