### ISSUE TITLE
自定义每周的起始日

### ISSUE THREAD

**Issue by TouchHeart** [huanghaibin-dev/CalendarView#38]
我要自定义周一或者周日为起始日要怎么修改呢？

**Comment by huanghaibin-dev** [comment]
周视图切换的时候吗？默认选中周一或者周日？

**Comment by TouchHeart** [comment]
就是第一竖排起始为星期一还是星期日
![image](https://user-images.githubusercontent.com/21155843/34243407-90534380-e65b-11e7-8793-c649692b9b31.png)

**Comment by TouchHeart** [comment]
有没有提供设置农历显示与隐藏的方法呢？

**Comment by huanghaibin-dev** [comment]
星期日到星期一的排列这个就不提供切换了，这种需求会使整个框架多了一堆if else语句，农历的显示和隐藏这个你按照demo就可以自己实现的啊，你可以把农历换成你想要的任意文本都是可以的，这个框架本身不干扰

**Comment by TouchHeart** [comment]
星期日到星期一的排列这个如果要实现，可以提供一下思路么？具体在框架哪个部分修改呢？谢谢了！

**Comment by huanghaibin-dev** [comment]
整体的算法都需要改动，日历的核心部分是农历算法和周算法，涉及到两个日期有多少周的话，是需要计算这两个日期的起始偏移和结束偏移的，总之，不建议改动这里

**Comment by TouchHeart** [comment]
框架里的Month类，有个setDiff()方法，表示日期偏移，可以实现么？

**Comment by huanghaibin-dev** [comment]
真的不可以，如果只是单独考虑月视图，那还好，但是周视图太复杂，并不是任意就能改动的，如果真的需要的话，我看看接下来怎么升级比较好，不破坏现在的可读性
