### ISSUE TITLE
能不能实现这样的功能?

### ISSUE THREAD

**Issue by sankemao** [huanghaibin-dev/CalendarView#4]
单选, 只能选今天即今天以后的日期.
双选, 用于查询历史记录, 只能选今天即今天之前的起止两个日期.

**Comment by huanghaibin-dev** [comment]
这个需求没有，如果需要的话，自己可以修改代码使用gradle intoJar导出jar文件，CalendarAdapter 这里改为双选、CalendarCardView里面setOnItemClickListener的地方比较选择的日期

**Comment by sankemao** [comment]
ok, 刚下完源码看看改下

**Comment by zxfnicholas** [comment]
这个日历不错，要是能实现周视图 那就完美了

**Comment by huanghaibin-dev** [comment]
全新版本已经开源，可以任意自定义UI了，谢谢支持。
