### ISSUE TITLE
日历不以日为单位，以周为单位

### ISSUE THREAD

**Issue by ethi1989** [huanghaibin-dev/CalendarView#400]
你好，我想在日历中显示的周，比如
1月第一周，1月第二周，1月第三周，1月第四周
2月第一周，2月第二周，2月第三周，2月第四周
请问要实现这样的效果，有什么思路吗？

**Comment by ethi1989** [comment]
like this
<img width="300" alt="image" src="https://user-images.githubusercontent.com/5791861/54103559-d45f8380-4407-11e9-8834-eb48f09558ed.png">

**Comment by huanghaibin-dev** [comment]
这种跟日历格格不入，改动要把ViewPager换RecyclerView，然后要把月转周来排版自定义View，改动会非常大

**Comment by ethi1989** [comment]
好的，谢谢！我自己进行绘制，其实只要计算出每月里面包含几周，其他的也不会很复杂
