### ISSUE TITLE
很强大的库，打算使用，可以设置不允许收缩么

### ISSUE THREAD

**Issue by CodingHornet** [huanghaibin-dev/CalendarView#41]
很强大的库，打算使用，可以设置不允许收缩么

**Comment by huanghaibin-dev** [comment]
@CodingHornet 谢谢支持，不使用收缩功能的话不去用CalendarLayout就好了，直接使用CalendarView，里面各个模块都是采用组合的形式的，方便多种需求

**Comment by CodingHornet** [comment]
@huanghaibin-dev 好使了，之前改错地方了，以为去掉没效果。。。多谢
