### ISSUE TITLE
关于默认选中的建议

### ISSUE THREAD

**Issue by yeyueduxing** [huanghaibin-dev/CalendarView#42]
现在是每次滑动的时候都会进行一次默认选中，我们很多时候都会在选中日期的时候进行请求，获取当前日期的数据。如果是本地数据还好，很多时候是网络请求，这样在频繁滑动的时候会请求非常多次数据，而且我们根本无法区分到底是用户点击产生的选中事件还是滑动产生的选中事件。
所以还是请大神考虑一下，是否可以提供一个方法，让开发者知道选中事件到底是怎么产生的，用于区分滑动和点击事件。
谢谢。

**Comment by huanghaibin-dev** [comment]
@yeyueduxing 马上发布新版本了，已经实际考虑到了这个改进需求了，谢谢支持

**Comment by huanghaibin-dev** [comment]
@yeyueduxing ok了
