### ISSUE TITLE
Can we make CalendarView as indirect child of CalendarLayout?

### ISSUE THREAD

**Issue by yccheok** [huanghaibin-dev/CalendarView#426]
Currently, due to the code in https://github.com/huanghaibin-dev/CalendarView/blob/master/calendarview/src/main/java/com/haibin/calendarview/CalendarLayout.java#L541 , we are forced to make `CalendarView` as the direct child of `CalendarLayout`

```
<CalendarLayout>
    <CalendarView />
</CalendarLayout>
```

However, we would like to 

```
<CalendarLayout>
    <FrameLayout>
        <CalendarView />
        <ImageView />
    </FrameLayout>
</CalendarLayout>
```

This is because we would like to achieve the following outcome, in order to lure/provide hint to user, that the Calendar is scroll-able
<img width="270" alt="a" src="https://user-images.githubusercontent.com/308276/55209194-4b748480-521c-11e9-9282-fb80a04b1783.png"> (The arrow icon will animate)

Can we suggest using the following code, instead of hard coded `getChildAt(0)`?

```
    public static View getViewByClass(View view, Class<?> klass) {
        if (klass.isInstance(view)) {
            return view;
        } else if (view instanceof ViewGroup) {
            ViewGroup viewGroup = (ViewGroup)view;
            int count = viewGroup.getChildCount();
            for (int i = 0; i < count; i++) {
                View v = getViewByClass(viewGroup.getChildAt(i), klass);
                if (v != null) {
                    return v;
                }
            }
        }
        return null;
    }
```

Thank you.
.

**Comment by huanghaibin-dev** [comment]
That seems to be the case.
```
<FrameLayout>
     <CalendarLayout>
            <CalendarView />
             <ContentView />
    </FrameLayout>
     <ImageView />
</CalendarLayout>
```
however,  ImageView cannot be moved.

**Comment by yccheok** [comment]
I guess the following is not a valid XML right?

<FrameLayout>
     <CalendarLayout>
            <CalendarView />
             <ContentView />
    </FrameLayout>
     <ImageView />
</CalendarLayout>

I guess what you mean is

```
<FrameLayout>
     <CalendarLayout>
            <CalendarView />
             <ContentView />
    </CalendarLayout>
    <ImageView />
</FrameLayout>
```

I had tried that configuration before but it doesn't work for my case.

As, I need to make `ImageView` located at bottom of screen. If I use `gravity` = bottom for `ImageView`, it will then move to the bottom of `RecyclerView` (which is not visible during that time).

What I wish is, the `ImageView` should move to the bottom of `CalendarView`.

Thank you.

**Comment by yccheok** [comment]
Hi, I manage to solve this problem using `CoordinatorLayout`

```
<CoordinatorLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    
    <CalendarLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        
        <CalendarView
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <RecyclerView
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
            
    </CalendarLayout>
    
    <FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="bottom|center_horizontal" />
</CoordinatorLayout>
```
