### ISSUE TITLE
日历和列表之间添加view 不是很好使用

### ISSUE THREAD

**Issue by zengcanxiang** [huanghaibin-dev/CalendarView#427]

**Comment by huanghaibin-dev** [comment]
出现什么问题？CalendarLayout内部只维持2个直接子View，要多嵌套View参考ViewPager风格，实现CalendarScrollView即可

**Comment by zengcanxiang** [comment]
就是在参考demo CalendarLayout 的时候，收缩的时候， calendarview的背景没有跟上去，不知道为什么。 

后来干脆复制demo里面的xml代码，删除很多，文件对比下，也没有差别，不知道为什么。干脆不管了。。😓

现在有个问题咨询一下，我想设置在切换月的时候，再切回来的时候，能够记住上一个月的选中日期，应该是如何自定义。我看demo里面都是切换的时候，上次选中的日期都是重置到每个月的第一天，如果是当月的话，就回重置到今天。
