### ISSUE TITLE
当系统的日期是 四月一号。  在日历上，游览到三月份的月试图，三十一号会不见

### ISSUE THREAD

**Issue by yccheok** [huanghaibin-dev/CalendarView#429]
当系统的日期是 四月一号。

在日历上，游览到三月份的月试图，三十一号会不见。

请问是什么原因？

![0_IMG-20190401-WA0001](https://user-images.githubusercontent.com/308276/55298226-199f3000-545f-11e9-9339-5a6937012801.jpg)

![0_IMG-20190401-WA0002](https://user-images.githubusercontent.com/308276/55298168-bf9e6a80-545e-11e9-98d2-367d79905e7c.jpg)

**Comment by huanghaibin-dev** [comment]
真的抱歉，full_style MonthViewPager并没有自适应FrameLayout的高度，我正在寻找其中的原因

**Comment by yccheok** [comment]
full style 是全屏的意思吗？可，就算不是全屏 (第一个载图)，也会遇到一样的问题。谢谢。

黄海彬 <notifications@github.com> 於 2019年4月1日 週一 上午9:34 寫道：

**Comment by huanghaibin-dev** [comment]
你是否嵌套了ScrollerView？

**Comment by yccheok** [comment]
这是全屏的 XML

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/calendarBackgroundColor"
    android:orientation="vertical">

    
    <RelativeLayout
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp"
        android:background="?attr/calendarBackgroundColor">

        <ImageButton
            android:id="@+id/previous_button"
            android:layout_width="64dp"
            android:layout_height="64dp"
            android:src="?attr/calendarLeftArrowIcon"
            android:background="?attr/actionBarItemBackground"
            android:layout_alignParentLeft="true"
            android:layout_centerVertical="true" />

        <TextView
            android:id="@+id/month_year_text_view"
            android:layout_width="wrap_content"
            android:layout_height="64dp"
            android:gravity="center"
            android:textColor="?attr/primaryTextColor"
            android:textSize="24sp"
            android:textStyle="bold"
            android:layout_centerInParent="true"
            android:layout_centerVertical="true" />

        <ImageButton
            android:id="@+id/forward_button"
            android:layout_width="64dp"
            android:layout_height="64dp"
            android:src="?attr/calendarRightArrowIcon"
            android:background="?attr/actionBarItemBackground"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true" />

    </RelativeLayout>

    <com.haibin.calendarview.CalendarLayout
        android:id="@+id/calendar_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="?attr/calendarBackgroundColor"
        android:orientation="vertical"
        app:calendar_show_mode="only_month_view"
        app:default_status="expand">

        <com.haibin.calendarview.CalendarView


            android:layout_height="match_parent"
            app:calendar_padding="0dp"
            app:month_view_show_mode="mode_all"
            app:calendar_match_parent="true"


            android:id="@+id/calendar_view"
            android:layout_width="match_parent"
            android:background="?attr/calendarBackgroundColor"

            android:layout_marginLeft="0dp"
            android:layout_marginRight="0dp"

            app:month_view="com.yocto.wenote.calendar.CustomMonthView"
            app:week_view="com.haibin.calendarview.DefaultWeekView"

            app:current_month_text_color="?attr/calendarCurrentMonthTextColor"
            app:other_month_text_color="?attr/calendarOtherMonthTextColor"
            app:current_month_lunar_text_color="?attr/calendarCurrentMonthLunarTextColor"
            app:other_month_lunar_text_color="?attr/calendarOtherMonthLunarTextColor"

            app:day_text_size="16sp"
            app:current_day_text_color="?attr/calendarCurrentDayTextColor"
            app:current_day_lunar_text_color="?attr/calendarCurrentDayLunarTextColor"
            app:selected_text_color="?attr/calendarSelectedTextColor"
            app:selected_lunar_text_color="?attr/calendarSelectedLunarTextColor"
            app:selected_theme_color="?attr/calendarSelectedThemeColor"

            app:week_bar_view="com.yocto.wenote.calendar.FullscreenCustomWeekBar"
            app:week_background="?attr/calendarBackgroundColor"
            app:week_line_background="?attr/calendarWeekLineBackgroundColor"
            app:week_bar_height="46dp"
            app:week_start_with="sun"

            app:month_view_scrollable="false"
            app:week_view_scrollable="false"
            app:year_view_scrollable="false"

            app:year_view_background="?attr/calendarYearBackgroundColor"
            app:year_view_day_text_color="?attr/primaryTextColor"
            app:year_view_day_text_size="9sp"
            app:year_view_month_text_color="?attr/calendarYearMonthTextColor"
            app:year_view_month_text_size="20sp"
            app:year_view_scheme_color="?attr/calendarYearSchemeColor" />

    </com.haibin.calendarview.CalendarLayout>

</LinearLayout>

**Comment by yccheok** [comment]
这个是非全屏的 xml

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="?attr/calendarBackgroundColor"
    android:orientation="vertical">

    <!-- navigation toolbar -->
    <RelativeLayout
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="12dp"
        android:layout_marginRight="12dp"
        android:background="?attr/calendarBackgroundColor">

        <ImageButton
            android:id="@+id/previous_button"
            android:layout_width="64dp"
            android:layout_height="64dp"
            android:src="?attr/calendarLeftArrowIcon"
            android:background="?attr/actionBarItemBackground"
            android:layout_alignParentLeft="true"
            android:layout_centerVertical="true" />

        <TextView
            android:id="@+id/month_year_text_view"
            android:layout_width="wrap_content"
            android:layout_height="64dp"
            android:gravity="center"
            android:textColor="?attr/primaryTextColor"
            android:textSize="24sp"
            android:textStyle="bold"
            android:layout_centerInParent="true"
            android:layout_centerVertical="true" />

        <ImageButton
            android:id="@+id/forward_button"
            android:layout_width="64dp"
            android:layout_height="64dp"
            android:src="?attr/calendarRightArrowIcon"
            android:background="?attr/actionBarItemBackground"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true" />

    </RelativeLayout>

    <com.haibin.calendarview.CalendarLayout
        android:id="@+id/calendar_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="?attr/calendarBackgroundColor"
        android:orientation="vertical"
        app:calendar_show_mode="only_month_view"
        app:default_status="expand">

        <com.haibin.calendarview.CalendarView


            android:layout_height="wrap_content"
            app:calendar_padding="12dp"
            app:month_view_show_mode="mode_fix"
            app:calendar_match_parent="false"


            android:id="@+id/calendar_view"
            android:layout_width="match_parent"
            android:background="?attr/calendarBackgroundColor"

            android:layout_marginLeft="0dp"
            android:layout_marginRight="0dp"

            app:month_view="com.yocto.wenote.calendar.CustomMonthView"
            app:week_view="com.haibin.calendarview.DefaultWeekView"

            app:current_month_text_color="?attr/calendarCurrentMonthTextColor"
            app:other_month_text_color="?attr/calendarOtherMonthTextColor"
            app:current_month_lunar_text_color="?attr/calendarCurrentMonthLunarTextColor"
            app:other_month_lunar_text_color="?attr/calendarOtherMonthLunarTextColor"

            app:day_text_size="16sp"
            app:current_day_text_color="?attr/calendarCurrentDayTextColor"
            app:current_day_lunar_text_color="?attr/calendarCurrentDayLunarTextColor"
            app:selected_text_color="?attr/calendarSelectedTextColor"
            app:selected_lunar_text_color="?attr/calendarSelectedLunarTextColor"
            app:selected_theme_color="?attr/calendarSelectedThemeColor"

            app:week_bar_view="com.yocto.wenote.calendar.CustomWeekBar"
            app:week_background="?attr/calendarBackgroundColor"
            app:week_line_background="?attr/calendarWeekLineBackgroundColor"
            app:week_bar_height="46dp"
            app:week_start_with="sun"

            app:month_view_scrollable="false"
            app:week_view_scrollable="false"
            app:year_view_scrollable="false"

            app:year_view_background="?attr/calendarYearBackgroundColor"
            app:year_view_day_text_color="?attr/primaryTextColor"
            app:year_view_day_text_size="9sp"
            app:year_view_month_text_color="?attr/calendarYearMonthTextColor"
            app:year_view_month_text_size="20sp"
            app:year_view_scheme_color="?attr/calendarYearSchemeColor" />

    </com.haibin.calendarview.CalendarLayout>

</LinearLayout>
```

**Comment by yccheok** [comment]
我猜想，这问题只在系统今天日期是四月一号才发生。是不是在算最佳高度时，是采用三十天(因为四月分只有三十天)，而不是采用三十一天(最大可能性)？

**Comment by huanghaibin-dev** [comment]
非常奇怪，之前有issue反馈这个问题，但都说demo没问题，我个人也从未触发过，你可以制作一个简单的demo重现这个问题吗？我用你的xml也没触发

**Comment by yccheok** [comment]
奇怪。

我用 master branch 版本。可以轻易复制这问题

我用 Android API 28。点击 Full screen style

如图。四月图

<img width="272" alt="0" src="https://user-images.githubusercontent.com/308276/55303028-840f9a80-5476-11e9-964e-c2c24562ac7a.png">

因为是全屏，不是应该显示灰色的五月五号，六号，。。。吗，以填满荧幕？

SWIPE 右边。这是三月图

<img width="265" alt="1" src="https://user-images.githubusercontent.com/308276/55303035-896ce500-5476-11e9-9989-87f785e60a69.png">

三十一号不见了。

**Comment by huanghaibin-dev** [comment]
full style已经解决，但是我没触发过普通样式的bug，这很奇怪

**Comment by yccheok** [comment]
我觉得，是在呼叫 updateItemHeight，mLineCount 还没被初始化 ?

**Comment by yccheok** [comment]
嗨黄兄，您说 full style 已解决了。可我并没看到任何 Commit 在 Master branch 。是否还在测试中？谢谢

**Comment by huanghaibin-dev** [comment]
已经提交版本了

**Comment by yccheok** [comment]
感恩您。我会再次测试看看。

**Comment by yccheok** [comment]
一切都很完美。万分感谢。

![0](https://user-images.githubusercontent.com/308276/55854571-a9e42000-5b97-11e9-8f38-401bb0a7d7a5.png)

![1](https://user-images.githubusercontent.com/308276/55854576-abade380-5b97-11e9-9a3f-3ceb3068c7e6.png)
