### ISSUE TITLE
有没有可能保证左上角角标跟下标风格同时共存的可能，并且可以自由控制，有没有什么思路去实现的？我想改动一下

### ISSUE THREAD

**Issue by juyao** [huanghaibin-dev/CalendarView#43]
如题

**Comment by huanghaibin-dev** [comment]
@juyao 当然是可以的，里面的绘制完全是交给你来做的，但是要自由控制有些是魅族风格，有些是下标风格，有些是两种风格共存的话，建议你在scheme这个字段存储多种信息，例如：scheme="假,index,multi"这种数据，然后根据实际绘制即可

**Comment by juyao** [comment]
嗯嗯，已经搞定了，多谢多谢！！
