### ISSUE TITLE
为什么在华为mate 20 pro 日历存在重影

### ISSUE THREAD

**Issue by wangjieyan** [huanghaibin-dev/CalendarView#431]
![image](https://user-images.githubusercontent.com/13582231/55372667-1fffdb80-5535-11e9-9c34-1989aa82e7d9.png)

**Comment by huanghaibin-dev** [comment]
注意去掉Paint的高斯模糊设置吧

**Comment by wangjieyan** [comment]
我应该没有设置这个高斯模糊

**Comment by huanghaibin-dev** [comment]
你把周视图代码贴出来看就知道什么问题了

**Comment by wangjieyan** [comment]
![image](https://user-images.githubusercontent.com/13582231/55375165-bfc16780-553d-11e9-9b9b-490750a6f745.png)

**Comment by wangjieyan** [comment]
![image](https://user-images.githubusercontent.com/13582231/55375183-d4056480-553d-11e9-9fed-7aa3de92b81e.png)

**Comment by huanghaibin-dev** [comment]
构造韩式最后那几行兼容去掉

**Comment by wangjieyan** [comment]
ok 谢谢了
