### ISSUE TITLE
怎样在月日历控件下面添加一个view，点击这个view可以，展开或收起月日历？

### ISSUE THREAD

**Issue by zhangshuliang** [huanghaibin-dev/CalendarView#432]
![image](https://user-images.githubusercontent.com/16489590/55387167-826fd080-5563-11e9-86be-4d125a133ebb.png)
首先感谢你的开源项目，它的功能如此强大。
如图是我的设计图，需要在月日历下面显示一个横条，点击这个横条可以控制月日历的展开或收起，希望指点一下，谢谢。

**Comment by huanghaibin-dev** [comment]
这种只能改源码了，给MonthViewPager 跟 WeekViewPager套个FrameLayout，FrameLayout底部放这个横条就行，记得隐藏MonthViewPager 跟 WeekViewPager 改为隐藏父布局就行。只是不明白收拾操作就能收缩，一步到位，为何要让手指伸去点击按钮这种交互呢？

**Comment by zhangshuliang** [comment]
是的，你说的对，我之前没有意识到直接下滑日历控件就会展开，我和设计说下，我不加这个交互了，thanks very much

**Comment by zfy199466** [comment]
自定义来收缩，如果使用shrink()或者expand()无效，可以通过获取CalendarView的月视图和周视图来实现伸缩效果。
下面是我个人的代码，仅供参考。
布局代码：
<com.haibin.calendarview.CalendarLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:orientation="vertical"
                        android:layout_marginBottom="25dp"
                        app:gesture_mode="disabled"
                        app:default_status="shrink">

                        <com.haibin.calendarview.CalendarView
                            android:id="@+id/calendarView"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            app:month_view="自定义的MonthView"
                            app:week_view="自定义的WeekView"
                            app:current_day_text_color="#333333"
                            app:month_view_scrollable="false"
                            app:scheme_theme_color="#FFFFFF"
                            app:selected_text_color="#FFFFFF"
                            app:month_view_show_mode="mode_only_current"
                            app:week_view_scrollable="false"
                            app:current_month_lunar_text_color="#BDBDBD"/>

                    </com.haibin.calendarview.CalendarLayout>

收缩实现的代码：（其实就是月视图和周视图互相隐藏和显示）
if (calendarView.getWeekViewPager().getVisibility() == View.GONE) {
      calendarView.getMonthViewPager().setVisibility(View.GONE);
      calendarView.getWeekViewPager().setVisibility(View.VISIBLE);
} else {
      calendarView.getMonthViewPager().setVisibility(View.VISIBLE);
      calendarView.getWeekViewPager().setVisibility(View.GONE);
}
