### ISSUE TITLE
app:select_mode="single_mode" 模式下，进入当月默认选中的是1号，为什么？

### ISSUE THREAD

**Issue by zhangshuliang** [huanghaibin-dev/CalendarView#434]
app:select_mode="single_mode" 模式下，进入当月默认选中的是1号，为什么？

我下载demo，看demo中魅族的风格就是默认选中当天的，我是把魅族的代码搬过来的，改成sigle_mode模式，但是不知为什么就默认选中1号了，而不是当天，希望指点一下，谢谢

**Comment by huanghaibin-dev** [comment]
single_mode不会自动选择的，你看看xml或者代码有没有主动调用scrollerTo的方法

**Comment by zhangshuliang** [comment]
![image](https://user-images.githubusercontent.com/16489590/55451220-9a4b6100-5604-11e9-9533-d772044b48a3.png)
非常感谢你，同时也很敬佩楼主，回复问题非常快。
