### ISSUE TITLE
感觉可以再优化一些，这个框架在我的项目中出现了很多共存问题

### ISSUE THREAD

**Issue by 643063150** [huanghaibin-dev/CalendarView#436]
这边的日历是在中间的而且只显示周日历，整体布局比较长，日历在靠近底部的情况，使用周视图必须在CalendarLayout里面添加一个calendar_content_view，但是我这个布局要用scrollview就导致会有一大片空白区域，我把整体布局放到listview里面还是会出现大片空白，感觉周视图必须跟CalendarLayout和calendar_content_view绑定使用有些场景无法适用，算是一点小建议吧

**Comment by huanghaibin-dev** [comment]
ScrollerView的特性是：里面的唯一直接子View是强制wrap_content，因此如果你将一些不确定高度的View如ListView、RecyclerView放入ScrollerView，那都是不能正常显示的，如果你要让CalendarLayout放入ScrollerView，你得手动计算CalendarLayout的高度才行

**Comment by 643063150** [comment]
> ScrollerView的特性是：里面的唯一直接子视图是强制WRAP_CONTENT，因此如果你将一些不确定高度的景观如ListView控件，RecyclerView放入ScrollerView，那都是不能正常显示的，如果你要让CalendarLayout放入ScrollerView，你得手动计算CalendarLayout的高度才行

意思是根据CalendarView的高度去计算CalendarLayout的高度吗？但是我在布局中把两个view的高度都写死也还是会有大片的空白，我以为是RecyclerView的问题用了自定义的listview后还是存在空白`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/black_f6f6f6"
    android:orientation="vertical">

    <RelativeLayout
        android:id="@+id/titleBar"
        android:layout_width="match_parent"
        android:layout_height="@dimen/dp_44"
        android:background="@color/white">

        <ImageView
            android:id="@+id/back"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:layout_marginLeft="20dp"
            android:src="@mipmap/back" />

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:text="车辆详细"
            android:textColor="#1A1A1A"
            android:textSize="17sp"
            android:textStyle="bold" />
    </RelativeLayout>

    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:orientation="vertical">

            <cn.bingoogolapple.bgabanner.BGABanner
                android:id="@+id/banner_home"
                style="@style/BannerDefaultStyle"
                android:layout_height="@dimen/dp_180"
                app:banner_indicatorGravity="bottom|center_horizontal"
                app:banner_pointDrawable="@drawable/car_banner_selector_indicator"
                app:banner_transitionEffect="alpha" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                android:orientation="horizontal">

                <TextView
                    android:id="@+id/car_name"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="@dimen/dp_16"
                    android:layout_marginTop="@dimen/dp_17"
                    android:layout_weight="1"
                    android:text="梅赛德斯-迈巴赫S级"
                    android:textColor="#ff1a1a1a"
                    android:textSize="21sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/status"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="@dimen/dp_17"
                    android:layout_marginRight="@dimen/dp_21"
                    android:text="出租中"
                    android:textColor="#ff2ec888"
                    android:textSize="14sp"
                    android:textStyle="bold" />
            </LinearLayout>

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/white"
                android:paddingLeft="@dimen/dp_16"
                android:paddingTop="@dimen/dp_30"
                android:paddingRight="@dimen/dp_16">

                <TextView
                    android:id="@+id/tv_oil"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="燃油标号：92"
                    android:textColor="#ff1a1a1a"
                    android:textSize="13sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/tv_box"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_centerHorizontal="true"
                    android:text="变速箱：AT6"
                    android:textColor="#ff1a1a1a"
                    android:textSize="13sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/tv_auxiliar"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_alignParentRight="true"
                    android:text="倒车雷达:有"
                    android:textColor="#ff1a1a1a"
                    android:textSize="13sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/tv_safe"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/tv_oil"
                    android:layout_marginTop="@dimen/dp_20"
                    android:text="安全气囊:有"
                    android:textColor="#ff1a1a1a"
                    android:textSize="13sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/tv_seat"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/tv_oil"
                    android:layout_centerHorizontal="true"
                    android:layout_marginTop="@dimen/dp_20"
                    android:text="座位数:6个   "
                    android:textColor="#ff1a1a1a"
                    android:textSize="13sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/tv_gps"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/tv_oil"
                    android:layout_alignParentRight="true"
                    android:layout_marginTop="@dimen/dp_20"
                    android:text="GPS导航:有"
                    android:textColor="#ff1a1a1a"
                    android:textSize="13sp"
                    android:textStyle="bold" />

                <TextView
                    android:id="@+id/tv_displacement"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_below="@id/tv_safe"
                    android:layout_marginTop="@dimen/dp_20"
                    android:text="排量：2.0T"
                    android:textColor="#ff1a1a1a"
                    android:textSize="13sp"
                    android:textStyle="bold" />
            </RelativeLayout>

            <TextView
                android:id="@+id/car_address"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@drawable/mycar_bg"
                android:paddingLeft="@dimen/dp_16"
                android:paddingTop="@dimen/dp_28"
                android:paddingBottom="@dimen/dp_13"
                android:text="地址：北京市东城区王府井东街8号"
                android:textColor="#ff1a1a1a"
                android:textSize="14sp" />

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginTop="@dimen/dp_10"
                android:background="@drawable/mycar_bg"
                android:orientation="vertical"
                android:paddingBottom="@dimen/dp_21">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="@dimen/dp_16"
                    android:layout_marginTop="@dimen/dp_16"
                    android:layout_marginRight="@dimen/dp_16"
                    android:text="车辆收益"
                    android:textColor="#ff666666"
                    android:textSize="15sp"
                    android:textStyle="bold" />

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal"
                    android:paddingTop="@dimen/dp_24">

                    <TextView
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:gravity="center"
                        android:text="￥158/天(平日)"
                        android:textColor="#ffffab40"
                        android:textSize="20sp"
                        android:textStyle="bold" />

                    <View
                        android:layout_width="0.5dp"
                        android:layout_height="match_parent"
                        android:background="#F2F2F2" />

                    <TextView
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_weight="1"
                        android:gravity="center"
                        android:text="￥158/天(平日)"
                        android:textColor="#ffffab40"
                        android:textSize="20sp"
                        android:textStyle="bold" />
                </LinearLayout>
            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

                <com.haibin.calendarview.CalendarLayout
                    android:id="@+id/calendarLayout"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/dp_100"
                    android:orientation="vertical"
                    app:calendar_content_view_id="@+id/car"
                    app:calendar_show_mode="only_week_view">

                    <com.haibin.calendarview.CalendarView
                        android:id="@+id/calendarView"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/dp_100"
                        android:background="#fff"
                        app:calendar_padding="10dp"
                        app:current_month_lunar_text_color="#CFCFCF"
                        app:current_month_text_color="#333333"
                        app:max_multi_select_size="5"
                        app:month_view="com.st.eu.ui.rentcar.MyViews.CustomMonthView"
                        app:month_view_scrollable="false"
                        app:month_view_show_mode="mode_only_current"
                        app:other_month_lunar_text_color="#e1e1e1"
                        app:other_month_text_color="#e1e1e1"
                        app:scheme_text="假"
                        app:scheme_text_color="#333"
                        app:scheme_theme_color="#128c4b"
                        app:select_mode="multi_mode"
                        app:selected_lunar_text_color="#CFCFCF"
                        app:selected_text_color="#ffffff"
                        app:selected_theme_color="#f17706"
                        app:week_background="#fff"
                        app:week_start_with="sun"
                        app:week_text_color="#111111"
                        app:week_view="com.st.eu.ui.rentcar.MyViews.CustomWeekView"
                        app:week_view_scrollable="false"
                        app:year_view_day_text_color="#333333"
                        app:year_view_day_text_size="9sp"
                        app:year_view_month_text_color="#ff0000"
                        app:year_view_month_text_size="20sp"
                        app:year_view_scheme_color="#f17706" />
                    <com.st.eu.widget.MyListView
                        android:id="@+id/car"
                        android:layout_width="match_parent"
                        android:layout_height="1dp">
                    </com.st.eu.widget.MyListView>
                </com.haibin.calendarview.CalendarLayout>
            </LinearLayout>

            <Button
                android:id="@+id/submit"
                android:layout_width="190dp"
                android:layout_height="44dp"
                android:layout_alignParentBottom="true"
                android:layout_centerHorizontal="true"
                android:layout_marginTop="@dimen/dp_45"
                android:layout_marginBottom="@dimen/dp_15"
                android:background="@drawable/addcar_bg"
                android:text="下架该车辆"
                android:textColor="#ff1a1a1a"
                android:textSize="17sp" />


        </LinearLayout>
    </android.support.v4.widget.NestedScrollView>
</LinearLayout>` 整体布局如上  运行后的界面
![XC`6W0_6 8M $WF D8M}OAM](https://user-images.githubusercontent.com/11732536/55709970-1c2ff580-5a1c-11e9-9794-8d5cee91294c.png)

**Comment by huanghaibin-dev** [comment]
这种写法涉及到到问题很多啊，首先是CalendarLayout的高度你没有正确计算，你单独设置个100dp远远不够，其次就是当CalendarLayout的高度计算好了，你依然要解决手势冲突，不然事件全被NestedScrollView消费了，给不到CalendarLayout，这类问题你给出个交互原型图，就很容易解决了，基本就是自定义一个NestedScrollView的问题，没几行代码

**Comment by 643063150** [comment]
嗯，感谢大大的耐心解答 ，其实我这边没有社么交互的，只显示周视图就可以了，滑动和切换月视图全都不需要

**Comment by huanghaibin-dev** [comment]
```java

public class ScrollerLayout extends NestedScrollView {

    private View mHeaderView;
    private CalendarLayout mCalendarLayout;

    private float mLastY;

    public ScrollerLayout(Context context) {
        super(context);
    }

    public ScrollerLayout(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    private boolean isTouch;

    @SuppressLint("ClickableViewAccessibility")
    @Override
    public boolean onTouchEvent(MotionEvent event) {

        int action = event.getAction();
        float y = event.getY();
        switch (action) {
            case MotionEvent.ACTION_DOWN:
                isTouch = true;
                mLastY = y;
                return true;

            case MotionEvent.ACTION_MOVE:

                float dy = y - mLastY;


                int scrollY = getScrollY();
                //向上滑动
                if (dy < 0 && scrollY == mHeaderView.getHeight() && isTouch) {
                    mLastY = y;
                    return false;
                }
                isTouch = false;
                mLastY = y;
                //向下滑动
                if (dy > 0 && scrollY == 0 && !mCalendarLayout.isExpand()) {
                    //mCalendarLayout.onTouchEvent(event);
                    return true;
                }

                mLastY = y;
                break;
            case MotionEvent.ACTION_CANCEL:
                isTouch = true;
                mCalendarLayout.onTouchEvent(event);
            case MotionEvent.ACTION_UP:
                isTouch = true;
                mCalendarLayout.onTouchEvent(event);
                break;
        }
        return super.onTouchEvent(event);
    }

    @Override
    public boolean onInterceptTouchEvent(MotionEvent event) {

        int action = event.getAction();

        float y = event.getY();

        switch (action) {
            case MotionEvent.ACTION_DOWN:
                isTouch = true;
                mLastY = y;

                if (getScrollY() == mHeaderView.getHeight() && !mCalendarLayout.isExpand()) {
                    return false;
                }
                if(getScrollY() != mHeaderView.getHeight()){
                    return true;
                }
                return super.onInterceptTouchEvent(event);

            case MotionEvent.ACTION_MOVE:

                float dy = y - mLastY;
                //向上滑动，并且contentView平移到最大距离，停止滚动
                if (dy < 0 && getScrollY() == mHeaderView.getHeight()) {
                    mLastY = y;
                    return false;
                }


                mLastY = y;
                break;
        }
        return super.onInterceptTouchEvent(event);
    }

    @Override
    protected void onFinishInflate() {
        super.onFinishInflate();
        mHeaderView = findViewById(R.id.ll_header);
        mCalendarLayout = findViewById(R.id.calendarLayout);
    }

    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int height = MeasureSpec.getSize(heightMeasureSpec);
        LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) mCalendarLayout.getLayoutParams();
        params.height = height;
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

    }
}

```

```xml

<com.example.haibin.demo.ScrollerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#FFFFFF"
    android:scrollbars="vertical">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <LinearLayout
            android:id="@+id/ll_header"
            android:layout_width="match_parent"
            android:layout_height="300dp"
            android:background="#FFFFFF"
            android:orientation="vertical">

            <TextView
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:gravity="center"
                android:text="头部布局"
                android:textSize="22sp"
                tools:ignore="HardcodedText" />
        </LinearLayout>

        <com.haibin.calendarview.CalendarLayout
            android:id="@+id/calendarLayout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:default_status="shrink"
            app:calendar_show_mode="only_week_view"
            app:calendar_content_view_id="@+id/scrollView">

            <com.haibin.calendarview.CalendarView
                android:id="@+id/calendarView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:month_view_show_mode="mode_only_current"
                app:week_background="#cecece" />

            <android.support.v4.widget.NestedScrollView
                android:id="@+id/scrollView"
                android:layout_width="match_parent"
                android:layout_height="match_parent">

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:background="#E6E6E6"
                    android:orientation="vertical">

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="200dp"
                        android:gravity="center"
                        android:text="子内容布局"
                        android:layout_gravity="center"
                        android:textSize="22sp"
                        tools:ignore="HardcodedText" />

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="200dp"
                        android:gravity="center"
                        android:text="子内容布局"
                        android:layout_gravity="center"
                        android:textSize="22sp"
                        tools:ignore="HardcodedText" />

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="200dp"
                        android:gravity="center"
                        android:text="子内容布局"
                        android:layout_gravity="center"
                        android:textSize="22sp"
                        tools:ignore="HardcodedText" />

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="200dp"
                        android:gravity="center"
                        android:text="子内容布局"
                        android:layout_gravity="center"
                        android:textSize="22sp"
                        tools:ignore="HardcodedText" />

                    <TextView
                        android:layout_width="match_parent"
                        android:layout_height="200dp"
                        android:gravity="center"
                        android:text="子内容布局"
                        android:layout_gravity="center"
                        android:textSize="22sp"
                        tools:ignore="HardcodedText" />
                </LinearLayout>

            </android.support.v4.widget.NestedScrollView>
        </com.haibin.calendarview.CalendarLayout>
    </LinearLayout>
</com.example.haibin.demo.ScrollerLayout>

```

**Comment by huanghaibin-dev** [comment]
给你写个简单的demo，你简单测试一下就知道对不对了

**Comment by huanghaibin-dev** [comment]
你建个项目，复制那个类，然后xml换个包名就行了，不需要其它操作，看看是不是你要的效果，关于事件拦截、onMeasure相关的，就不展开细说了

**Comment by 643063150** [comment]
嗯 好的  非常感谢

**Comment by 643063150** [comment]
用上面的方法设置单行显示没有问题 最下面的布局位置也相对正确，但是你把上面的子内容布局减少到一个就会发现下面大片空白我看了下代码 感觉是` @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int height = MeasureSpec.getSize(heightMeasureSpec);
        LinearLayout.LayoutParams params = (LinearLayout.LayoutParams) mCalendarLayout.getLayoutParams();
        params.height = height;
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

    }`这里动态的设置CalendarLayout的高度无效，设置多少他都是那个高度

**Comment by 643063150** [comment]
如图，把其他视图山的只剩一个 大量的空白
![2)Q5}Y~LO%9}TX7DF5IH_96](https://user-images.githubusercontent.com/11732536/55716627-05909b00-5a2a-11e9-9172-454682ec14a3.png)

**Comment by huanghaibin-dev** [comment]
你要动态高度就得算啊，我也不知道你们的设计是什么，这只是大概的思路发自我的iPhone------------------ 原始邮件 ------------------发件人: 643063150  <notifications@github.com>发送时间: 2019年4月8日 18:13收件人: huanghaibin-dev/CalendarView <CalendarView@noreply.github.com>抄送: 黄海彬 <huanghaibin_dev@163.com>, Comment <comment@noreply.github.com>主题: 回复：[huanghaibin-dev/CalendarView] 感觉可以再优化一些，这个框架在我的项目中出现了很多共存问题 (#436)如图，把其他视图山的只剩一个 大量的空白


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/huanghaibin-dev/CalendarView","title":"huanghaibin-dev/CalendarView","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/huanghaibin-dev/CalendarView"}},"updates":{"snippets":[{"icon":"PERSON","message":"@643063150 in #436: \r\n如图，把其他视图山的只剩一个 大量的空白\r\n![2)Q5}Y~LO%9}TX7DF5IH_96](https://user-images.githubusercontent.com/11732536/55716627-05909b00-5a2a-11e9-9172-454682ec14a3.png)\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/huanghaibin-dev/CalendarView/issues/436#issuecomment-480771469"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/huanghaibin-dev/CalendarView/issues/436#issuecomment-480771469",
"url": "https://github.com/huanghaibin-dev/CalendarView/issues/436#issuecomment-480771469",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 643063150** [comment]
我的意思是我修改CalendarLayout的params的高度没有用

**Comment by huanghaibin-dev** [comment]
我大概明白了，你删除CalendarLayout的onMeasure方法就可以了，我没有考虑这种不需要滚动内容的情况

**Comment by 643063150** [comment]
嗯  有时间了 我再好好看一下 这块用的时间有点长 周视图我就先自己写了一个 月视图还是用您这个框架实现 非常感谢您的解答

**Comment by 643063150** [comment]
请问` mCalendarView2.scrollToNext(false);`
设置滑动后没有触发MonthChange 我要怎么才能得到当前正在显示的月份和年份呢？

**Comment by huanghaibin-dev** [comment]
应该会触发的，都是在onPagerSelected上做的处理

**Comment by 643063150** [comment]
` mCalendarView2.scrollToNext(false);
        mCalendarView2.setOnMonthChangeListener(new CalendarView.OnMonthChangeListener() {
            @Override
            public void onMonthChange(int year, int month) {
                mMonthTv2.setText(year + "年" + month + "月");
            }
        });`
是我代码写的哪有问题吗，您看日历的视图已经切换过去了，但是并没有触发监听，因为我上面的文字还是我给的默认的没有获取到年月（第二个日历是代码设置滑动的，第一个是当前的没有滑动直接获取是没问题的）
![NK(ZFJ9FDX37$J3 JL(DT](https://user-images.githubusercontent.com/11732536/55939584-b5574a00-5c70-11e9-90b4-48c527d75161.png)

**Comment by 643063150** [comment]
可能是多选的原因把，我直接修改github下载的示例，首页是可以监听到的，但是示例里面的多选再用代码滑动的时候也是无法获取到的，但是手动滑动日历就能监听的到

**Comment by huanghaibin-dev** [comment]
你再看看吧，onPageSelected不分视图的
