### ISSUE TITLE
如何设置一周起始日为周一到周日的任意一天？

### ISSUE THREAD

**Issue by Sunhulg** [huanghaibin-dev/CalendarView#437]
如何设置一周起始日为周一到周日的任意一天？

**Comment by huanghaibin-dev** [comment]
不太明白什么意思，可否详细一些？

**Comment by Sunhulg** [comment]
感谢作者的回答。
现在的日历可以设置周一、周六和周日为周起始日，现在有需求是可以设置周一到周日的任意一天为周起始日，目前很多手机的自带日历都实现了这个功能，比如华为和魅族等。现在我在改源码看能否实现这个功能，如果遇到问题，还希望作者大大有时间能解答一下，肥肠感谢~^^

**Comment by Sunhulg** [comment]
感谢作者的回答。
现在的日历可以设置周一、周六和周日为周起始日，现在有需求是可以设置周一到周日的任意一天为周起始日，目前很多手机的自带日历都实现了这个功能，比如华为和魅族等。现在我在改源码看能否实现这个功能，如果遇到问题，还希望作者大大有时间能解答一下，肥肠感谢~^^


------------------ 原始邮件 ------------------
发件人: "黄海彬"<notifications@github.com>;
发送时间: 2019年4月10日(星期三) 下午3:54
收件人: "huanghaibin-dev/CalendarView"<CalendarView@noreply.github.com>;
抄送: "胡栗桂"<1048054782@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [huanghaibin-dev/CalendarView] 如何设置一周起始日为周一到周日的任意一天？ (#437)




不太明白什么意思，可否详细一些？

**Comment by huanghaibin-dev** [comment]
只有华为才有这个吧，这个倒是不麻烦，只是应该不太可能会提供的，可自行去修改源码，看是怎么用weekStartWith这个参数的，基本只需要改CalendarUtil类的计算逻辑

**Comment by Sunhulg** [comment]
> 只有华为才有这个吧，这个倒是不麻烦，只是应该不太可能会提供的，可自行去修改源码，看是怎么用weekStartWith这个参数的，基本只需要改CalendarUtil类的计算逻辑
OK, 我自己改改试试~
