### ISSUE TITLE
为什么将GroupRecyclerView换成RecyclerView，整个日历视图无法收起？

### ISSUE THREAD

**Issue by Sunhulg** [huanghaibin-dev/CalendarView#439]
为什么将GroupRecyclerView换成RecyclerView，整个日历视图无法收起？如果用GroupRecyclerView，如何设置不显示title？

**Comment by huanghaibin-dev** [comment]
任意View都支持的，注意calendar_content_view_id或者有没有设置仅月视图、禁用手势之类的

**Comment by Sunhulg** [comment]
> 任意View都支持的，注意calendar_content_view_id或者有没有设置仅月视图、禁用手势之类的

非常感谢，确实是calendar_content_view_id没改过来，谢谢解答；
