### ISSUE TITLE
怎样只使用周视图

### ISSUE THREAD

**Issue by svran** [huanghaibin-dev/CalendarView#44]
怎样只使用周视图?  禁用展开;

**Comment by huanghaibin-dev** [comment]
如果是这样的话，此版本没有提供，不过你可以改一行代码就行了，CalendarLayout 的 onTouchEvent，第一行return就可以，然后加上app:default_status="shrink"，那就是只有周视图了

**Comment by svran** [comment]
感谢及时回复,下个版本如果不影响整体逻辑的话,可以加上;
那我先临时改了应付着先;

**Comment by huanghaibin-dev** [comment]
这个倒是简单，一个小功能还不至于发一个版本，我看看可以加什么特别的再发一个版本吧
