### ISSUE TITLE
有个界面显示问题我解决不了，大大能不能帮忙看看？

### ISSUE THREAD

**Issue by ChenChen345** [huanghaibin-dev/CalendarView#444]
我这两天在尝试使用您的日历，感觉很棒。但是有一个问题解决不了，当我自定义页面时，我发现日历的第一行始终显示不了。想问一下应该怎么处理？我现在还是一个学生，水平不够，望能不吝赐教。
![Screenshot_1555339849](https://user-images.githubusercontent.com/49589037/56142585-8541db00-5fd1-11e9-99a6-7da747f660fe.png)
这是屏幕截图

**Comment by ChenChen345** [comment]
`public class TestMonthview extends MonthView {

        public TestMonthview(Context context) {
            super(context);
        }
    
        @Override
        protected boolean onDrawSelected(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme) {
            //这里绘制选中的日子样式，看需求需不需要继续调用onDrawScheme
            Paint paint=new Paint();
            paint.setColor(0xffed2523);
            paint.setTextSize(85);

            canvas.drawLine(x,y,x+200,y,paint);
            return true;
        }

        @Override
        protected void onDrawScheme(Canvas canvas, Calendar calendar, int x, int y) {
            //这里绘制标记的日期样式，想怎么操作就怎么操作

        }

        @Override
        protected void onDrawText(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme, boolean isSelected) {
            mSelectedPaint.setTextSize(70);
            canvas.drawText(calendar.getDay()+"",x+40,y-20,mSelectedPaint);
            mSelectedPaint.setTextSize(30);
            canvas.drawText(" "+calendar.getLunar(),x+40,y+30,mSelectedPaint);
            
        }
`

`<com.haibin.calendarview.CalendarView
        android:id="@+id/calendarView"
        android:layout_marginTop="20dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#fff"
        app:month_view="com.example.testcalendar.TestMonthview"
        app:week_bar_height="30dp"
        app:day_text_size="35dp"
        app:calendar_height="80dp"
        app:current_day_text_color="#5266ff"
        app:current_day_lunar_text_color="#5266ff"
        app:current_month_text_color="#333333"
        app:current_month_lunar_text_color="#CFCFCF"
        app:min_year="2004"
        app:other_month_text_color="#e1e1e1"
        app:scheme_text="真"
        app:scheme_text_color="#222"
        app:scheme_theme_color="#333"
        app:selected_text_color="#FFF"
        app:selected_theme_color="#87c2ec"
        app:week_start_with="sun"
        app:week_background="#fff"
        app:month_view_show_mode="mode_only_current"
        app:week_text_color="#111" `/>``

**Comment by huanghaibin-dev** [comment]
很多都是错误的，如onDrawText，明显y坐标就错了，而且不能单纯+-20那样算，其次onDrawSelected不必要每次都new Paint，很容易引起GC
