### ISSUE TITLE
WeekView的背景问题

### ISSUE THREAD

**Issue by kobayashikanata** [huanghaibin-dev/CalendarView#445]
作者您好，我使用了您的CalendarView开发应用的日历视图，现在有这样一个需求
![Untitled](https://user-images.githubusercontent.com/19747520/56177905-e51c9e00-6032-11e9-9c8e-bf713d3b3385.png)
需要星期栏和状态栏共享一个背景，我尝试过设置已有的attr，未达到效果

**My implement**
我的想法是WeekBar设置透明，然后Appbar和Weekbar的底部放一个ImageView，这样他们可以共享一个背景，然后WeekView单独设置一个背景

**Problem**
CalendarView和CalendarLayout只能直接设置background，这样WeekBar和WeekView会是同一个背景，如果单独设置week_background，又会导致背景不是solidColor的情况下，不连续

请问此库是否提供有这样的实现?
有空劳烦请解答一下，谢谢！

**Comment by huanghaibin-dev** [comment]
WeekBar直接设置背景色就可以了，跟你的Appbar颜色相同，我其实也不太清楚你具体是实现怎么样的效果

**Comment by kobayashikanata** [comment]
您好，谢谢回复，我想要实现的效果请参考下面的图片
![Capture](https://user-images.githubusercontent.com/19747520/56188400-ffb53e00-6057-11e9-8082-6b267e6bc2b1.PNG)

**Comment by huanghaibin-dev** [comment]
自定义WeekBar，将Appbar放入WeekBar

**Comment by kobayashikanata** [comment]
Get it! 谢谢
