### ISSUE TITLE
不可选中的日期颜色设置为灰色

### ISSUE THREAD

**Issue by LiweiStarwalker** [huanghaibin-dev/CalendarView#449]
请问如何给不可选中的日期颜色设置为灰色，如setRange后，range以外设置为灰色，谢谢哦

**Comment by huanghaibin-dev** [comment]
clone demo里面有，任何视图都能获取isRange等API得到判断，给画笔换个颜色什么的自行操作

**Comment by zhaoxiuyu** [comment]
@huanghaibin-dev  我设置的是single_mode单选模式，在拦截器中对部分不可选的日期进行了拦截， 那么不可选日期的颜色 怎么设置?至灰

**Comment by gs666** [comment]
我最近实现了这个需求，贴出代码，仅供参考。
public class CustomMonthView extends MonthView {

    private int mRadius;

    /**
     * 自定义魅族标记的文本画笔
     */
    private Paint mTextPaint = new Paint();

    /**
     * 背景圆点
     */
    private Paint mPointPaint = new Paint();

    /**
     * 蓝色圆点半径
     */
    private float mPointRadius;

    private int mPadding;

    private float mCircleRadius;

    /**
     * 自定义魅族标记的圆形背景
     */
    private Paint mSchemeBasicPaint = new Paint();

    public CustomMonthView(Context context) {
        super(context);

        mTextPaint.setTextSize(dipToPx(context, 8));
        mTextPaint.setColor(0xffffffff);
        mTextPaint.setAntiAlias(true);
        mTextPaint.setFakeBoldText(true);

        mSchemeBasicPaint.setAntiAlias(true);
        mSchemeBasicPaint.setStyle(Paint.Style.FILL);
        mSchemeBasicPaint.setTextAlign(Paint.Align.CENTER);
        mSchemeBasicPaint.setFakeBoldText(true);
        mSchemeBasicPaint.setColor(Color.WHITE);

        mPointPaint.setAntiAlias(true);
        mPointPaint.setStyle(Paint.Style.FILL);
        mPointPaint.setTextAlign(Paint.Align.CENTER);
        mPointPaint.setColor(0xFF3366FF);

        mCircleRadius = dipToPx(getContext(), 7);

        mPadding = dipToPx(getContext(), 3);

        mPointRadius = dipToPx(context, 2);
    }


    @Override
    protected void onPreviewHook() {
        mRadius = Math.min(mItemWidth, mItemHeight) / 11 * 5;
    }


    @Override
    protected boolean onDrawSelected(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme) {
        int cx = x + mItemWidth / 2;
        int cy = y + mItemHeight / 2;
        canvas.drawCircle(cx, cy, mRadius, mSelectedPaint);
        return true;
    }

    @Override
    protected void onDrawScheme(Canvas canvas, Calendar calendar, int x, int y) {

    }

    @SuppressWarnings("IntegerDivisionInFloatingPointContext")
    @Override
    protected void onDrawText(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme, boolean isSelected) {
        int cx = x + mItemWidth / 2;
        float baselineY = mTextBaseLine + y;

        //当天的蓝色圆点
        if (calendar.isCurrentDay()) {
            mPointPaint.setColor(0xFF3366FF);
            canvas.drawCircle(x + mItemWidth / 2, y + mItemHeight - 5 * mPadding, mPointRadius, mPointPaint);
        }

        //当前月份颜色
        mCurMonthTextPaint.setColor(0xFF2C2836);

        //其他月份颜色or不可用
        mOtherMonthTextPaint.setColor(0x522C2836);

        //当日颜色
        mCurDayTextPaint.setColor(0xFF2C2836);

        boolean isInRange = isInRange(calendar);
        boolean isEnable = !onCalendarIntercept(calendar);

        if (isSelected) {
            canvas.drawText(String.valueOf(calendar.getDay()),
                    cx,
                    baselineY,
                    mSelectTextPaint);
        } else if (hasScheme) {
            canvas.drawText(String.valueOf(calendar.getDay()),
                    cx,
                    baselineY,
                    calendar.isCurrentDay() ? mCurDayTextPaint :
                            calendar.isCurrentMonth() && isInRange && isEnable ? mSchemeTextPaint : mOtherMonthTextPaint);

        } else {
            canvas.drawText(String.valueOf(calendar.getDay()), cx, baselineY,
                    calendar.isCurrentDay() ? mCurDayTextPaint :
                            calendar.isCurrentMonth() && isInRange && isEnable ? mCurMonthTextPaint : mOtherMonthTextPaint);
        }
    }

    /**
     * dp转px
     *
     * @param context context
     * @param dpValue dp
     * @return px
     */
    private static int dipToPx(Context context, float dpValue) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (dpValue * scale + 0.5f);
    }
}
