### ISSUE TITLE
周视图月初月末交替时onMonthChange没有触发，造成标记没出来

### ISSUE THREAD

**Issue by TopTime1** [huanghaibin-dev/CalendarView#450]
周视图月初月末交替时onMonthChange没有触发，造成标记没出来，这个在onMonthChange这个监听里缓存上下两个月的数据吗
？

**Comment by huanghaibin-dev** [comment]
后面安排一下，原本设计是月是月、年是年这样变化的，一直没有去改这里，我看看怎么改合适一些

**Comment by TopTime1** [comment]
或者能不能像月视图那样支持设置只显示当前月的，交替处可以空出那几天来

**Comment by huanghaibin-dev** [comment]
周视图没法判断是不是当前月份啊，例如一周内有2个月的数据，要以什么条件判断当前是哪一周呢？

**Comment by TopTime1** [comment]
也是，确实比较难处理

**Comment by TopTime1** [comment]
大神，还有个问题咨询下，calendarView.setRange；然后 calendarView.scrollToCurrent(true);滚动到今天，为什么onMonthChange，会先走一次最大的月份，然后再走当前月份

**Comment by huanghaibin-dev** [comment]
这里必须是false，因为ViewPagerAdapter的数据变化了，更新会引起onPageSelected的，一定要false

**Comment by TopTime1** [comment]
onCalendarSelect这个监听方法也会走一次最大月份的1号
![image](https://user-images.githubusercontent.com/7701170/56496647-db140700-652c-11e9-905d-bd9c05b1f0cb.png)

**Comment by TopTime1** [comment]
设置成false也是这样

**Comment by TopTime1** [comment]
![image](https://user-images.githubusercontent.com/7701170/56497209-35ae6280-652f-11e9-8071-4d1cb232e217.png)
第一次进来这个监听走了两次

**Comment by huanghaibin-dev** [comment]
Adapter count会变化，默认选择模式似乎是没办法的事，

**Comment by TopTime1** [comment]
那么我只能判断下是不是第一次加载数据，加个判断？
