### ISSUE TITLE
RangeMonthView如何动态设置可选日期范围

### ISSUE THREAD

**Issue by GoombaCN** [huanghaibin-dev/CalendarView#451]
比如我起始时间选择了1号 限制条件是30天内的日期 那么我选下个月2号 是不能选中的
比如我起始时间选择了2号 限制条件是30天内的日期 那么我选下个月3号 是不能选中的
我在onCalendarRangeSelect方法中 使用 int days = endCalendar.differ(startCalendar);
是可以实现“如果日期是30天内”的判断
但是判断里面的代码是拦截点击事件 这里应该怎么做呢

int days = endCalendar.differ(startCalendar);
if(days>30){
  不响应或拦截点击事件
}
@huanghaibin-dev  求大佬指点一二 
十分感谢！

**Comment by huanghaibin-dev** [comment]
动态设置日期范围不是很简单吗，如日期：2019-04-01，如果限制30天，用时间戳一算就换算得出2019-04-30了，然后setRange就行了，拦截点击事件可添加个事件就可以，demo都有的

**Comment by GoombaCN** [comment]
> 动态设置日期范围不是很简单吗，如日期：2019-04-01，如果限制30天，用时间戳一算就换算得出2019-04-30了，然后setRange就行了，拦截点击事件可添加个事件就可以，demo都有的

这里setRange会影响视图 比如设置2019-04-01 至 2019-04-30 
这样页面无法左右滚动 也就是说用户无法查看之前的日期 
然后通过查看 我找到有一个setSelectCalendarRange方法 想通过setSelectCalendarRange控制显示视图 然后setRange控制选择范围 
结果发现range模式使用setSelectCalendarRange是无效的

因为需要拦截的日期是实时的 是用户点击起始日期时决定的 所以setOnCalendarInterceptListener这里不适用吧
<从2018年开始 到今天的31天后 是视图需要显示的时间 用户可以选择的日期 间隔不能超过30天> 本人愚昧 没有从您的demo中找到相关这种需求的设置 
demo中拦截的是特定的一些日期 且并非动态设置的
绘制颜色相关的代码已经通过阅读您的代码找到了解决方法 但是动态设置拦截这块确实没有找到
还望您指点下

**Comment by huanghaibin-dev** [comment]
我不太明白具体是什么需求，意思是用户选择了3月1号，最多只能往后选择30天的意思吗？然后还是能滑到1月，当用户点击1月1日，最多只能点击选中到1月30号？

**Comment by GoombaCN** [comment]
> 我不太明白具体是什么需求，意思是用户选择了3月1号，最多只能往后选择30天的意思吗？然后还是能滑到1月，当用户点击1月1日，最多只能点击选中到1月30号？

感谢您的回复

用户的可选范围是2016年1月1日 至 现在为止的下个月 也就是日历可以显示的范围
以今天的日期来说 日历向左翻 只能翻到2016年1月 日向右翻 只能翻到2019年5月 
然后假设用户点击3月1号为起始时间 截止日期只能选择距离起始时间30天之内的日期 也就是最多选到3月31号 


我这里的代码 
setRange实现了日历的显示范围
接下来是拿到用户选择的起始日期和截止时间 来判断是否大于30天 
可以通过setOnCalendarRangeSelectListener中onCalendarRangeSelect
最后 判断条件成立 则 不去响应用户的点击 

这里我就不知道该怎么做了

**Comment by huanghaibin-dev** [comment]
`setSelectRange(-1, 30)`，了解一下，设置范围选择的可选范围

**Comment by GoombaCN** [comment]
> `setSelectRange(-1, 30)`，了解一下，设置范围选择的可选范围

感谢大佬 完美解决了！
希望可以加到ReadMe中 帮到更多人
