### ISSUE TITLE
setSelectRange的minRange与maxRange是什么含义

### ISSUE THREAD

**Issue by GoombaCN** [huanghaibin-dev/CalendarView#455]
@huanghaibin-dev 大佬 这个是我的代码

 @Override
            public void onCalendarRangeSelect(Calendar calendar, boolean isEnd) {
                search.setEnabled(true);
                if (!isEnd) {
                    calendar_view.setSelectRange(calendar.getDay() + 1, 1);
                } else {
                    ToastUtil.showCenterToast(MainActivity.this, "end");
                }
            }
__________________________________________________________________________________________________
核心代码calendar_view.setSelectRange(calendar.getDay() + 1, 1);
这里设置之后 我起始日期选择日期4月1日 为什么截止日期可以选到5月24号呢 选5月25号才触发onSelectOutOfRange中的代码

**Comment by huanghaibin-dev** [comment]
设置最小可选范围和最大可选范围，-1为不限制

**Comment by GoombaCN** [comment]
> 设置最小可选范围和最大可选范围，-1为不限制

最大可选范围写30 含义是最大只能选择30天内 还是30号之内呢

**Comment by huanghaibin-dev** [comment]
最大可选30天，不是多少号

**Comment by GoombaCN** [comment]
> 最大可选30天，不是多少号

最大30天指的是距离当前日期 还是选择的起始日期呢

**Comment by huanghaibin-dev** [comment]
你点下1号，往后就只能选到30号，从你选择某一天开始算

**Comment by GoombaCN** [comment]
> 你点下1号，往后就只能选到30号，从你选择某一天开始算

多谢大佬
