### ISSUE TITLE
【标记】动态添加标记的功能

### ISSUE THREAD

**Issue by 1226362423** [huanghaibin-dev/CalendarView#464]
目前调用setSchemeDate去设置标记  会将之前的标记清空，现有需求：需要点击按钮动态调整标记，并不需要将之前的标记清空，这个是怎么实现的啊，为什么设置标记需要将之前的清空呢，不是有清空标记的clearSchemeDate方法吗

**Comment by 1226362423** [comment]
@huanghaibin-dev   忘大神解答下

**Comment by 1226362423** [comment]
这是要结合本地缓存数据库来实现吗   框架不会自带这个功能吗？

**Comment by 1226362423** [comment]
@huanghaibin-dev

**Comment by 1226362423** [comment]
可不可以动态调整指定清除哪天的标记   设置标记不需要清除所有标记

**Comment by huanghaibin-dev** [comment]
@1226362423 removeSchemeDate(Calendar calendar);这个很久之前就有的吧

**Comment by 1226362423** [comment]
已经解决
