### ISSUE TITLE
混淆打包后，不能向上拉起日历控件，只能左右滑动

### ISSUE THREAD

**Issue by helloworkcupid** [huanghaibin-dev/CalendarView#47]
如题，混淆打包后，控件只能左右滑动，不能实现原来的功能，不知道哪里出了问题

**Comment by huanghaibin-dev** [comment]
看readme，-keepclasseswithmembers class * {
    public <init>(android.content.Context);
}

**Comment by helloworkcupid** [comment]
已经设置了
-keepclasseswithmembers class * {   # 高度自定义日历控件
    public <init>(android.content.Context);
}

现在的情况是能显示日历，能左右滑动，但是不能上下滑动，不能设置每行的高度。<init>不添加会报错

**Comment by huanghaibin-dev** [comment]
是混淆的时候才出现么？应该是你哪里弄错了，或者可以加一下我看看问题

**Comment by helloworkcupid** [comment]
您的qq是多少呢？

**Comment by helloworkcupid** [comment]
是混淆的时候才出现的，debug模式下没有问题

**Comment by huanghaibin-dev** [comment]
1505651581
