### ISSUE TITLE
沉浸式状态栏设置不了

### ISSUE THREAD

**Issue by sweetysweets** [huanghaibin-dev/CalendarView#471]
您好~想问一下我更改了日历头部的背景颜色后，设置状态栏的颜色不生效是怎么回事呀，需要更改哪部分代码呀

**Comment by huanghaibin-dev** [comment]
沉浸式跟框架没什么关系吧，xml代码是怎么样的

**Comment by sweetysweets** [comment]
啊啊发现自己傻逼了。。是我代码设置有问题，现在已经解决了，感谢！
