### ISSUE TITLE
设置日历不可选

### ISSUE THREAD

**Issue by zhangjianwei1** [huanghaibin-dev/CalendarView#472]
因为需求原因，日历只起一个展示的作用，想设置成让用户不可点击的，不知道要怎么实现呢

**Comment by huanghaibin-dev** [comment]
select_mode="single_mode"，然后代码添加拦截器，拦截器返回true代表全部拦截

**Comment by zhangjianwei1** [comment]
不可以全部拦截，因为页面还有手动添加的选中效果，你说的方法我试了，然后设置的选中效果都没有了

**Comment by huanghaibin-dev** [comment]
如果是这样，周月视图onClick方法去掉实现不就可以了

**Comment by 748297973** [comment]
解决了吗

**Comment by zhangjianwei1** [comment]
自定义了最后

**Comment by YoungMr** [comment]
> 自定义了最后
@所有人：不用自定义
  public void onClick(View v) {
//        super.onClick(v);  去掉实现就可以，不走父类的逻辑
        Calendar index = getIndex();//同时可以拿到点击calendar，自己可以自定义点击事件

    }
