### ISSUE TITLE
calendar_height 这个属性的准确性

### ISSUE THREAD

**Issue by nangonghuang** [huanghaibin-dev/CalendarView#479]
在CalendarView的onMeasure里面有这么一句话
```java
 setCalendarItemHeight((height -mDelegate.getWeekBarHeight()) / 6);
```
这样子的话，设置的calendar_height这个属性是不是就失去了意义了？比如我想设置每个日期的大小是48*48dp,结果这么一算出去，宽高都不知道变成多少了

**Comment by huanghaibin-dev** [comment]
看配置的，这个没有问题，如果你配置全屏日历的话，就会执行这句代码
