### ISSUE TITLE
如何同时使用下表和多彩风格

### ISSUE THREAD

**Issue by SimonGyf** [huanghaibin-dev/CalendarView#48]
如题 我现在一方面要对选中的日期加上选中的圆形标记，另一方面还要同步系统日历日程即在日历日期的下面加上标记，请问这要如何同时实现呢

**Comment by huanghaibin-dev** [comment]
要关联系统日历，这个就不是框架提供的操作了，自行google查访问系统日历的代码，要混用各种风格是没问题的，canvas在那里由你自行绘制，当然你clone Demo一看估计就明白了，写得很清楚，可以支持copy对应的代码混用一下，而且很简单，没几行代码

**Comment by SimonGyf** [comment]
嗯嗯 已经弄好 非常感谢你
