### ISSUE TITLE
CalendarView.setTextColor无效

### ISSUE THREAD

**Issue by MaryDQ** [huanghaibin-dev/CalendarView#489]
CalendarView.setThemeColor
CalendarView.setWeeColor
这两个方法有效，另一个无效

**Comment by MaryDQ** [comment]
CalendarView.setTextColor无效

**Comment by MaryDQ** [comment]
mCalendarView.setTextColor(Color.WHITE,Color.parseColor("#ffffff"),Color.parseColor("#333333"),Color.parseColor("#cfcfcf"),Color.WHITE);

几个方法都是在主线程调用的

**Comment by huanghaibin-dev** [comment]
已修复，周月视图本身是可自选Paint的，如果是自定义的Paint都是无效的，所以这几个方法已经很久没维护了，忘记标记过时了，顺便修复一下
