### ISSUE TITLE
你好，范围选择动态屏蔽日期能行吗，没有找到相关方法

### ISSUE THREAD

**Issue by houyinyu** [huanghaibin-dev/CalendarView#493]
在监听里面可以设置屏蔽特定日期，我想的场景：外部一个按钮，点击了之后再屏蔽特定日期

**Comment by huanghaibin-dev** [comment]
实现onCalendarIntercept接口方法，条件是客户端任意写的，例如你可以自定义一个条件类，点击按钮的时候更改条件对象，或者定义一个map，点击按钮把特定的日期添加进去即可，然后判断map是不是包括了日期

**Comment by houyinyu** [comment]
我开始是这样想的，由于onCalendarIntercept是protected的，所以每一次点击就去触发监听setOnCalendarInterceptListener，然后实现onCalendarIntercept，但个人感觉每次都去实现监听感觉不好。
然后我这边的业务逻辑是：

我已经在日历控件上选择的范围了，再去点击CheckBox的星期一的按钮，日历控件上的所有选择的星期一刷新为非选择状态，取消选择选择星期一，日历控件上的星期一回归选择状态，这个实时刷新就有点难受，不知道我表述清楚没有。然后谢谢大神上面的解答

**Comment by houyinyu** [comment]
projectCycle_calendar.update()能实时刷新，功能实现了
