### ISSUE TITLE
请教一个问题，关于字体颜色设置

### ISSUE THREAD

**Issue by Goode-Man** [huanghaibin-dev/CalendarView#494]
目前设置颜色只有当前月份，今天，其它月份，希望能增加一个isWeekend的颜色设定（一般周末默认灰色这样的），加入使用setTextColor就连周末的颜色也统一了

**Comment by huanghaibin-dev** [comment]
看demo吧，这个框架跟xml、setTextColor没多大关系，完全可以自选Paint来完成各种UI，这种需求custom包就已经提供了
