### ISSUE TITLE
MonthView对象该怎么获取，activity或者fragment要交互，看源码不能获取该对象，好多东西不好处理，作者能不能暴露获取monthview对象

### ISSUE THREAD

**Issue by ZevShiShi** [huanghaibin-dev/CalendarView#497]
如题

**Comment by huanghaibin-dev** [comment]
获取MonthView对象是出于什么操作？它只是一个普通的View，获取方法源码有给出例子：

`
MonthView monthView = mCalendarView.getMonthViewPager().findViewWithTag(mCalendarView.getMonthViewPager().getCurrentItem());
`
同理可以for循环获取三个MonthView或者WeekView，
获取出来判断非空，貌似获取到也没什么实际用途

**Comment by ZevShiShi** [comment]
就是作者有没有办法获取所有二十四节气名称和节日名称对应的日期，因为要一一对应，所以我要存到数据库中，在其他地方获取，因为逻辑都写在monthview中，所以没法取到

**Comment by ZevShiShi** [comment]
> 获取MonthView对象是出于什么操作？它只是一个普通的View，获取方法源码有给出例子：
> 
> `MonthView monthView = mCalendarView.getMonthViewPager().findViewWithTag(mCalendarView.getMonthViewPager().getCurrentItem());`
> 同理可以for循环获取三个MonthView或者WeekView，
> 获取出来判断非空，貌似获取到也没什么实际用途

就是作者有没有办法获取所有二十四节气名称和节日名称对应的日期，因为要一一对应，所以我要存到数据库中，在其他地方获取，因为逻辑都写在monthview中，所以没法取到

**Comment by huanghaibin-dev** [comment]
你要获取当前月份的24节气或者节日的日期吗？

**Comment by ZevShiShi** [comment]
> 你要获取当前月份的24节气或者节日的日期吗？

是的就是 日期--名称 这样一一对应

**Comment by ZevShiShi** [comment]
> 你要获取当前月份的24节气或者节日的日期吗？
节日和二十四节气都要一一对应这样

**Comment by huanghaibin-dev** [comment]
不是有个API吗？
`
mCalendarView.getCurrentMonthCalendars();
`
里面的Calendar对象可以直接获取节气节日，而且都是区分对应的，判断一下即可

**Comment by ZevShiShi** [comment]
> 不是有个API吗？
> `mCalendarView.getCurrentMonthCalendars();`
> 里面的Calendar对象可以直接获取节气节日，而且都是区分对应的，判断一下即可

哦对对没想起来，谢谢作者，效率很高，感谢
