### ISSUE TITLE
从竖屏切换到横屏时 日历圆球背景出现剃头和剪尾的情况

### ISSUE THREAD

**Issue by yaoxin2017** [huanghaibin-dev/CalendarView#5]
从竖屏切换到横屏时 日历圆球背景出现剃头和剪尾的情况
我有一个activity，配置（android:configChanges="keyboardHidden|orientation|screenSize"）当横竖屏切换时，不销毁重建activity，在这个activity中我使用一个fragment，这个fragment内使用了你的日历控件，竖屏的时候一切都很好，但横屏就会发生剃头和剪尾的情况。

**Comment by yaoxin2017** [comment]
我自己解决了，楼主下个版本自己更新下吧：
在CellView类中onDraw方法里大概80行改为:

if (isSelectedDay) {
            //解决横竖屏剪头去尾的bug
            canvas.drawCircle(width / 2, height / 2, Math.min(height / 2,width/2), mSelectedPaint);
}

**Comment by huanghaibin-dev** [comment]
@yaoxin2017 哈哈哈，感谢你的反馈，我会改进这里，没有考虑横屏的情况，接下来主要是节假日和你的这个建议

**Comment by huanghaibin-dev** [comment]
全新版本已经开源，可以任意自定义UI了，谢谢支持。
