### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by bravewh** [huanghaibin-dev/CalendarView#50]
你好楼主，非常感谢你分享的这个日历控件，发现一个问题，比如默认设置的日期为红色，农历默认为黑色，如果设置选中状态日期为白色，农历也为白色，那么初始化时，显示的当天字体颜色还是红色，而农历选中状态变成白色，这样就不美观了。可以添加这个功能吗，就是第一次进去时，当天日期颜色是选中状态的白色，不是选中状态时，变为红色了。

还有，农历部分，农历和节假日的颜色可以分开来设置吗？统一设置，不太美观。

最后，非常感谢你的分享，祝工作顺利，生活愉快。

**Comment by huanghaibin-dev** [comment]
谢谢支持，我过两天忙完发布新版本，增加更多attr，以及调整对应的自定义UI绘制，让自定义日历UI更加好懂一点

**Comment by bravewh** [comment]
感谢你的回复，你好，我想问一下，如果和CoordinatorLayout+AppLayout+TabLayout+ViewRecyclerView一起时候，怎么在判断当CalendarLayout收缩起来时，并且TabLayout也滑动至CalendarLayout下面时，可以把CalendarLayout滑出界面，然后TabLayout就固定在TooBar下面了。不然的话，CalendarLayout还存在，那么就不能让ViewPager更好的利于界面空间了。谢谢了。

**Comment by huanghaibin-dev** [comment]
你需要个CalendarLayout收缩的或者展开的回调是吧，目前是不太建议这个控件放AppLayout里面的

**Comment by bravewh** [comment]
我试过放在AppLayout里面，但是点击年份选择，没有弹出选择窗口，其他还没发现问题，现在我的解决方式是使用CalendarLayout来包裹CoordinatorLayout+AppBarLayout，这样没有出现问题的。现在研究上滑时，TabLayout把收缩的CalendarLayout顶出界面，并固定在TooBar下方，只是我自定义View和滑动处理方面很薄弱，只能边学习边摸索了。

**Comment by huanghaibin-dev** [comment]
@bravewh 新版本已经发布，更加方便自定义了

**Comment by bravewh** [comment]
谢谢，辛苦了，加油。

**Comment by jweihao** [comment]
楼主，有研究过，将CalendarLayout放入AppLayout或者NestedScrollView后，点击年月选择无法弹出的原因么？并且不需要周视图，只要月视图就好。我虽然因为弹出年月选择，所以只能在自己的项目中实现这个功能了，但是，还是很想知道这个问题的答案，而且，后期楼主会添加记事或者闹钟提醒的功能么?

**Comment by huanghaibin-dev** [comment]
@jweihao 当前的版本这个的确是不兼容的，不弹出的原因也很简单，这个控件依赖月视图来计算高度，如果放入NestedScrollView，会导致初始化高度计算为0，我待会发布改进。当然我的个人建议是尽可能不要和其它滚动控件一同使用的，因为这个控件不是特别兼容NestedScroll特性
