### ISSUE TITLE
周视图左右滑动非常容易触发展开月视图 能否优化

### ISSUE THREAD

**Issue by Android4Wang** [huanghaibin-dev/CalendarView#503]
rt

**Comment by Zhangxxl** [comment]
+1

**Comment by codingbooo** [comment]
您好.您问题解决了吗 @Android4Wang

**Comment by yanerchuang** [comment]
+1，应该是事件冲突导致的

**Comment by yanerchuang** [comment]
我把这几行代码注释掉后，事件不再分发，问题解决
`        final int action = ev.getAction();
        float y = ev.getY();
        if (action == MotionEvent.ACTION_MOVE) {
            float dy = y - mLastY;
            /*
             * 如果向下滚动，有 2 种情况处理 且y在ViewPager下方
             * 1、RecyclerView 或者其它滚动的View，当mContentView滚动到顶部时，拦截事件
             * 2、非滚动控件，直接拦截事件
             */
            if (dy > 0 && mContentView.getTranslationY() == -mContentViewTranslateY) {
                if (isScrollTop()) {
                    requestDisallowInterceptTouchEvent(false);//父View向子View拦截分发事件
                    return super.dispatchTouchEvent(ev);
                }
            }
        }`

**Comment by sinduanan** [comment]
> rt

老哥，这个问题解决了吗
