### ISSUE TITLE
请问星期栏和月视图之间可以设置外边距吗？

### ISSUE THREAD

**Issue by ZevShiShi** [huanghaibin-dev/CalendarView#508]
如题

**Comment by huanghaibin-dev** [comment]
可以吧，自定义WeekBar，WeekBar具体什么margin，什么高度都可以自由设置

**Comment by ZevShiShi** [comment]
好吧我试试

> 可以吧，自定义WeekBar，WeekBar具体什么margin，什么高度都可以自由设置

好吧我试试
