### ISSUE TITLE
《建议作者建一个QQ群或者微信群方便大家讨论》

### ISSUE THREAD

**Issue by xuxinjiang** [huanghaibin-dev/CalendarView#511]
这样可以解决用户给你在GitHub上提的问题，你如果有建群 我这里还有更好的建议 ，请大神加我QQ：478104175，我可以作为管理员 帮你解决日历上一些小问题

**Comment by huanghaibin-dev** [comment]
个人不习惯搞Q群，一般issue我都会用心回复的，不好意思，难得有心，感谢了
