### ISSUE TITLE
请问如何设置 月视图 固定显示为6行，行数不变化。

### ISSUE THREAD

**Issue by lxfwelldone** [huanghaibin-dev/CalendarView#519]

**Comment by huanghaibin-dev** [comment]
month_view_show_mode或者api可以配置，demo或者文档都有的

**Comment by lxfwelldone** [comment]
> month_view_show_mode或者api可以配置，demo或者文档都有的

**Comment by lxfwelldone** [comment]
> month_view_show_mode或者api可以配置，demo或者文档都有的

谢了大佬
