### ISSUE TITLE
选择其他日期，给今天加上背景颜色怎么加

### ISSUE THREAD

**Issue by Bobyang912** [huanghaibin-dev/CalendarView#52]
如题，选择其他日期，给今天加上背景颜色怎么加，不仅要文字颜色

**Comment by huanghaibin-dev** [comment]
onDrawText 判断isCurrentDay，绘制上背景即可，或者你等明天吧，我今天把怎么使用的博客发布上去，看博客教程吧

**Comment by Bobyang912** [comment]
按照你的指引，实现了

**Comment by huanghaibin-dev** [comment]
@Bobyang912 新版本刚刚已经发布了，建议使用新版本
