### ISSUE TITLE
大大你好啊，calendar_height设置过大时，整个日历不显示，显示空白

### ISSUE THREAD

**Issue by LiweiStarwalker** [huanghaibin-dev/CalendarView#520]
app:calendar_height=""，这个指定的高度超过屏幕高度时整个日历不显示，小于屏幕高度时则正常显示。谢谢啦！

**Comment by huanghaibin-dev** [comment]
使用demo的话，去掉软件加速的代码即可，View.setLayerType(View.LAYER_TYPE_SOFTWARE, Paint); Android为了性能对这个做了限制，如果View高于手机屏幕高度，则不进行onDraw调用

**Comment by LiweiStarwalker** [comment]
谢谢啊！解决了。
