### ISSUE TITLE
小白求助，怎么屏蔽今天以前的日期不可点击

### ISSUE THREAD

**Issue by w2396631304** [huanghaibin-dev/CalendarView#529]
看了好久您这个源码，发现返回屏蔽的不是list或者具体哪一天，注释的方法也尝试了下，但是好像都没其效果，不知道是根据什么来屏蔽的。。。

**Comment by huanghaibin-dev** [comment]
添加拦截器，看中文文档，条件就判断日期小于今天即可

**Comment by w2396631304** [comment]
> 添加拦截器，看中文文档，条件就判断日期小于今天即可

那个，好像，return calendar.getDay<CalendarView.getCurDay 拦截无效

**Comment by huanghaibin-dev** [comment]
把模式改为单选模式，默认模式不支持拦截器的

**Comment by w2396631304** [comment]
> 把模式改为单选模式，默认模式不支持拦截器的

额，刚刚试了下改成single_mode，好像不起效果，我现在用的是您的多选MonthView

@Override
    public boolean onCalendarIntercept(Calendar calendar) {
        int day = calendar.getDay();
        return day < calendarView.getCurDay();
    }

这样写的，设置了selectRange也是从今天开始到月底

**Comment by w2396631304** [comment]
![image](https://user-images.githubusercontent.com/29300752/62854512-1c216880-bd22-11e9-80d8-f567859ed18f.png)
我仿写了下您的demo，添加map，然后return hasScheme，没有成功[委屈]

**Comment by Stanllley** [comment]
你写的拦截逻辑有问题，应该是这样子的，翻译成java代码就好

**Comment by Stanllley** [comment]
![1565662695(1)](https://user-images.githubusercontent.com/18157486/62910816-9995b900-bdb4-11e9-85b2-c06342a66640.png)

**Comment by w2396631304** [comment]
我转成java看了，这个逻辑不是一样的吗？获取当前时间和系统时间对比

**Comment by w2396631304** [comment]
![image](https://user-images.githubusercontent.com/29300752/62921006-00799900-bdda-11e9-8420-90779cd7c670.png)

**Comment by huanghaibin-dev** [comment]
检查一下有没有设置拦截器

**Comment by w2396631304** [comment]
> 检查一下有没有设置拦截器
方便的话请告诉我您的demo里拦截器的代码，我去看您的demo，（我好菜啊。。。）

**Comment by huanghaibin-dev** [comment]
`
//设置日期拦截事件
mCalendarView.setOnCalendarInterceptListener(new CalendarView.OnCalendarInterceptListener() {
     @Override
     public boolean onCalendarIntercept(Calendar calendar) {
         //这里写拦截条件，返回true代表拦截，尽量以最高效的代码执行
         return calendar.isWeekend();//例如周末的日期全部拦截
     }

     @Override
     public void onCalendarInterceptClick(Calendar calendar, boolean isClick) {
         //todo 点击拦截的日期回调
     }
});
`

**Comment by w2396631304** [comment]
> `
> //设置日期拦截事件
> mCalendarView.setOnCalendarInterceptListener(new CalendarView.OnCalendarInterceptListener() {
> @override
> public boolean onCalendarIntercept(Calendar calendar) {
> //这里写拦截条件，返回true代表拦截，尽量以最高效的代码执行
> return calendar.isWeekend();//例如周末的日期全部拦截
> }
> 
> ```
>  @Override
>  public void onCalendarInterceptClick(Calendar calendar, boolean isClick) {
>      //todo 点击拦截的日期回调
>  }
> ```
> 
> });
> `

额，这个是写了的

**Comment by w2396631304** [comment]
![image](https://user-images.githubusercontent.com/29300752/62921960-c1991280-bddc-11e9-9145-4b12b81b7700.png)
这两行代码会互相影响吗？

**Comment by huanghaibin-dev** [comment]
没影响，不改源码没什么问题的，添加拦截器就可以了，你点击被拦截的日期，调试一下看看有没有进入拦截器，没有的话应该就是改了什么地方了

**Comment by w2396631304** [comment]
> 没影响，不改源码没什么问题的，添加拦截器就可以了，你点击被拦截的日期，调试一下看看有没有进入拦截器，没有的话应该就是改了什么地方了

好的，谢谢！

**Comment by huanghaibin-dev** [comment]
不行的话加qq我帮你看看1505651581，也看看xml有没有设置select_mode之类的

**Comment by w2396631304** [comment]
> 不行的话加qq我帮你看看1505651581，也看看xml有没有设置select_mode之类的

ok，我再结合回复重新写一遍，真的非常感谢

**Comment by w2396631304** [comment]
> 不行的话加qq我帮你看看1505651581，也看看xml有没有设置select_mode之类的

已屏蔽成功，可是后面几个月也被屏蔽了

**Comment by w2396631304** [comment]
> 你写的拦截逻辑有问题，应该是这样子的，翻译成java代码就好

![image](https://user-images.githubusercontent.com/29300752/63076988-7c561b80-bf69-11e9-8b01-5ed511354aae.png)
这位大哥，加了你的代码后，频繁出现今天也不能点击。。。

**Comment by w2396631304** [comment]
老大人很nice

**Comment by LeeeeeYao** [comment]
> > 你写的拦截逻辑有问题，应该是这样子的，翻译成java代码就好
> 
> ![image](https://user-images.githubusercontent.com/29300752/63076988-7c561b80-bf69-11e9-8b01-5ed511354aae.png)
> 这位大哥，加了你的代码后，频繁出现今天也不能点击。。。

我也遇到今天第一次不能点击，再次点击可以的问题，这个问题 解决了吗
