### ISSUE TITLE
How to select specific day programmatically?

### ISSUE THREAD

**Issue by koza4e4ok** [huanghaibin-dev/CalendarView#533]
Hello, for now only current day can be selected, how i can select day programmatically?

**Comment by huanghaibin-dev** [comment]
CalendarView.scrollToCalendar(year,month,day);

**Comment by koza4e4ok** [comment]
@huanghaibin-dev thanks for your answer, but in my case i want to scroll to specific date and automatically select (highlight) day

with CalendarView.scrollToCalendar(year,month,day); i can only scroll to date
