### ISSUE TITLE
大佬 无法调用  BaseRecyclerAdapter 中 setOnItemClickListener

### ISSUE THREAD

**Issue by lxfwelldone** [huanghaibin-dev/CalendarView#534]
日历下面的新闻点击事件。。。
我这里是gradle引用3.6.4版本
在CustomActivity中，
        articleAdapter.setOnItemClickListener(new BaseRecyclerAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(int position, long itemId) {
                Toast.makeText(CustomActivity.this, "哈哈哈--", Toast.LENGTH_SHORT).show();
            }
        });

提示不是 public 修饰
    void setOnItemClickListener(OnItemClickListener onItemClickListener) {
        this.onItemClickListener = onItemClickListener;
    }

请问怎么修改？

**Comment by huanghaibin-dev** [comment]
这个你该下demo代码public就可以了，demo跟日历没什么关系的，就普通封装一下Adapter，很多这种BaseAdapter可以用的，不需要极限demo的案例

**Comment by lxfwelldone** [comment]
> 这个你该下demo代码public就可以了，demo跟日历没什么关系的，就普通封装一下Adapter，很多这种BaseAdapter可以用的，不需要极限demo的案例
谢了
