### ISSUE TITLE
日历的星期显示不正确

### ISSUE THREAD

**Issue by sprikid** [huanghaibin-dev/CalendarView#552]
![微信图片_20190923181054](https://user-images.githubusercontent.com/6179454/65417806-894e1080-de2d-11e9-90fb-5b46f938b1a7.jpg)
引用的版本是implementation 'com.haibin:calendarview:3.6.6'

**Comment by SuperZiLu** [comment]
这不挺正确的嘛？哪有问题？
![image](https://user-images.githubusercontent.com/30061527/65476043-31a6b800-deb4-11e9-8ccb-f390a5f215a7.png)

**Comment by sprikid** [comment]
和Java中的月份转换时出错了
