### ISSUE TITLE
建议升级targetSdkVersion

### ISSUE THREAD

**Issue by yuanliu666** [huanghaibin-dev/CalendarView#56]
很不错的库。
不过为什么不升级版本呢？一看库的targetSdkVersion还是23，现在API都到27了，还有各种support lib和plugin也可以升级。

**Comment by huanghaibin-dev** [comment]
谢谢支持，这个库不需要任何系统权限，也不需要高级api的支持，目前升级对于部分想使用的客户端带来的support style兼容性并不好，因此个人更加建议使用exclude排除重复的support包即可
