### ISSUE TITLE
请教下，如何显示农历日期，但是不显示特殊农历呢？

### ISSUE THREAD

**Issue by Hemione521** [huanghaibin-dev/CalendarView#573]
如题，我看特殊农历什么的都是在values.xml文件中写死的，我想只显示正常的农历应该怎么办呢？没看到有配置项，谢谢

**Comment by huanghaibin-dev** [comment]
Calendar类，可以拿到lunarCalendar，拿农历日期即可

**Comment by Hemione521** [comment]
谢谢回复
这个拿到的农历日期好像是完整的对吧？
不是类似于初一、初二这种，我看代码应该是十月初一类似这种的

**Comment by huanghaibin-dev** [comment]
lunarCalendar里也有getLunar字符串，就是初一初二这种，如果还需要特殊的，可以利用里面的LunarCalendar类这些，也能单独运算日期的

**Comment by Hemione521** [comment]
好的，谢谢
我试一下
