### ISSUE TITLE
Activity和MonthView怎么进行数据交互？

### ISSUE THREAD

**Issue by EpicWang** [huanghaibin-dev/CalendarView#574]
有没有大神指导一下，Activity和MonthView怎么进行数据交互？MonthView中的onDrawText()方法执行的时候怎么拿到activity中的数据?

**Comment by huanghaibin-dev** [comment]
通过Scheme，最高效运行，不限数据量，MonthView就是ViewPager中的一项，Scheme里面可以放任意数据

**Comment by EpicWang** [comment]
@huanghaibin-dev 了解，多谢回复~~
