### ISSUE TITLE
用了依赖包，日期没有显示

### ISSUE THREAD

**Issue by chenjiaming2qiqi** [huanghaibin-dev/CalendarView#58]
用了依赖包，日期没有显示？是不是接漏了什么

**Comment by huanghaibin-dev** [comment]
没有显示的话看月视图和周视图是不是接错了，对着demo或者教程看看文档使用方法

**Comment by chenjiaming2qiqi** [comment]
app:month_view="com.jmsofts.calendartest.simple.SimpleMonthView"
app:week_view="com.jmsofts.calendartest.simple.SimpleWeekView"

发现这两个view没有被调用，删除之后运行，跑了默认界面。

**Comment by fenggeZhang** [comment]
用的依赖，我的也是没有显示日期？

**Comment by huanghaibin-dev** [comment]
他已经解决了啊，请注意使用的月视图是app:month_view="路径"，如果有什么疑问的话可以加QQ：1505651581 看看




发自网易邮箱大师


在2018年01月31日 15:20，fenggeZhang<notifications@github.com> 写道：

用的依赖，我的也是没有显示日期？

**Comment by fenggeZhang** [comment]
谢谢 没有注意到
