### ISSUE TITLE
滑动瞬间回弹及默认选中1号

### ISSUE THREAD

**Issue by xh101gkkk** [huanghaibin-dev/CalendarView#60]
没有使用CalendarLayout在每次滑动的时候会出现底下控件被挤开一定高度又迅速回弹的情况，虽然使用CalendarLayout嵌套可以解决这个问题，可是每次滑动分页的时候又会出现默认选择1号的情况...希望可以解决下...

**Comment by huanghaibin-dev** [comment]
@xh101gkkk 谢谢反馈，更新的比较匆忙，忽略了这个bug

**Comment by huanghaibin-dev** [comment]
已经ok，请使用3.1.9版本即可
