### ISSUE TITLE
如何在onDrawSelected()里获取到返回选中范围的Calendar集合

### ISSUE THREAD

**Issue by lucky-you** [huanghaibin-dev/CalendarView#600]
我想在onDrawSelected()里获取到返回选中范围的Calendar集合，请问如何在onDrawSelected()方法里面获取到获取选中范围？

![企业微信截图_15759602338763](https://user-images.githubusercontent.com/22268878/70502834-d6a06b00-1b5c-11ea-8c32-57328423e96b.png)

**Comment by lucky-you** [comment]
已经解决了

**Comment by DreamerLeon** [comment]
你好我遇到相同的需求，请问你怎样获取的呢？
