### ISSUE TITLE
只想要显示周视图

### ISSUE THREAD

**Issue by wei7785929** [huanghaibin-dev/CalendarView#61]
项目中只需要用到周视图单行的效果 不需要上下滑动切换为周视图，没看到是怎么用的

**Comment by huanghaibin-dev** [comment]
@wei7785929 CalendarLayout 有个attr，<attr name="only_week_view" format="boolean" />，用这个就可以了

**Comment by wei7785929** [comment]
如果我只用calendarlayout和calendarview，设置这个属性是不行的，必须在下方设置calendar_content_view_id的依赖控件对吧

**Comment by huanghaibin-dev** [comment]
目前是的，CalendarLayout是作为收缩辅助控件，本身并没有和日历视图做关联
