### ISSUE TITLE
能把周六周日的字体置灰,只显示当前月 不显示别的月份的日期么?

### ISSUE THREAD

**Issue by gexiangjie** [huanghaibin-dev/CalendarView#62]
![image](https://user-images.githubusercontent.com/9777969/35501780-df036b3a-0515-11e8-9c3d-98398cb3320f.png)
就像z这种效果的,求告知,多谢

**Comment by huanghaibin-dev** [comment]
可以的，使用CalendarView的一个attr，month_view_show_mode，这里可以配置显示当前月的，里面三种模式，具体还是建议你看README或者教程，或者demo吧，周末字体灰色这个你按教程热插拔设计写个自定义View就可以了啊，Calendar类有个isWeekend(),判断周末，用周末的画笔，否则用其它画笔

**Comment by gexiangjie** [comment]
恩恩 好的 多谢 建议建个交流群

**Comment by huanghaibin-dev** [comment]
@gexiangjie 你可以阅读以下源码，类都很简单，没什么大逻辑，结果也清晰，还有个人并不喜欢建群拉人

**Comment by gexiangjie** [comment]
还有一个问题 就是我想在选中日期的时候  上面的星期几也被选中  这个可以实现么

**Comment by huanghaibin-dev** [comment]
这个控件本身没有提供，不过也的确是可以改进的思路，如果你要实现的话，自定义WeekBar吧，注意一下，用merge，然后写个回调即可，在OnDateSelectedListener回调自行判断是周几，然后更新WeekBar

**Comment by gexiangjie** [comment]
好的 多谢提供思路  佩服

**Comment by huanghaibin-dev** [comment]
@gexiangjie 哈哈，他真的是万能解耦的！基本上都可以自由定制各种效果
