### ISSUE TITLE
有没有判断当前是否showSelectLayout的方法

### ISSUE THREAD

**Issue by ImHone** [huanghaibin-dev/CalendarView#63]
我想监听返回键，如果当前年月选择界面显示，则关闭年月选择界面

**Comment by huanghaibin-dev** [comment]
这个倒是没有提供，直接用mCalendarView.findViewById(R.id.selectLayout)去判断是否显示了

**Comment by ImHone** [comment]
不好意思，再问一下，我应该怎么关闭年月选择界面，closeSelectLayout和它里面的东西都是private修饰，怎么才能优雅的解决

**Comment by huanghaibin-dev** [comment]
@ImHone 我找个时间发布个版本，优雅的解决一下

**Comment by huanghaibin-dev** [comment]
@ImHone done，最新版发布
