### ISSUE TITLE
建议增加一个换肤的内部方法

### ISSUE THREAD

**Issue by zxfnicholas** [huanghaibin-dev/CalendarView#68]
动态换颜色是时，在CalendarView中加入方法：
public void updateTheme(){
        mSelectLayout.update();
        mMonthPager.updateSelected();
        mWeekPager.updateSelected(getSelectedCalendar());
    }

**Comment by zxfnicholas** [comment]
动态修改Selected背景颜色，周末的颜色

**Comment by huanghaibin-dev** [comment]
明白了，慢慢改进，谢谢支持

**Comment by zxfnicholas** [comment]
之前用的另一个开源项目，定制性太差，这个项目做的已经很好了，灵活度很高，还有一点就是CalendarView.scrollToCalendar（）跳转的时候性能上会卡，过渡也会有空白，不是太友好，希望可以优化一下

**Comment by zxfnicholas** [comment]
是的，希望越做越好，

**Comment by huanghaibin-dev** [comment]
新版本已经发布，各种scroll函数可以自由选择是否平滑过渡了
