### ISSUE TITLE
设置当天文本样式无效果，清除圆点标记正确显示

### ISSUE THREAD

**Issue by GXSZone** [huanghaibin-dev/CalendarView#714]
设置当天日期及农历文本颜色为红色，背景色为灰色，预览是正确的，当设置圆点标记时，见视频二，当天日期及农历文本颜色没有效果均和当月其他日期样式一样，当清除标记时，效果正常消失

[图片](https://share.weiyun.com/M24cgXLp)
[视频二](https://share.weiyun.com/VTWy7yxh)

**Comment by AngelBo** [comment]
怎么解决的 我现在也是圆点问题 当天圆点只有选中的时候才有
