### ISSUE TITLE
月视图 在左右切换的时候 总是显示一号

### ISSUE THREAD

**Issue by gexiangjie** [huanghaibin-dev/CalendarView#72]
大佬 月视图 在左右切换的时候 总是显示一号 而且第一次进来会默认点击一个日期 这样我就会做一次网络请求 我现在是3.2.0 的版本

**Comment by huanghaibin-dev** [comment]
有个isclick参数判断是否人为点击的啊

发自我的 iPhone

**Comment by gexiangjie** [comment]
哦哦 那在切换月份的时候 都是默认显示1号 这个可以不默认么

**Comment by huanghaibin-dev** [comment]
默认显示一号是因为需要确定收缩的位置，几乎所有的日历都是这么做的，但如果你真的需要改动的话，有两种办法可以解决，第一就是改源码，MonthView里面有个方法    void setSelectedCalendar(Calendar calendar) ;这个方法删除掉实现即可，第二种更加推荐，就是自己实现MonthView，在onDrawSelected里面判断如果是一号并且不是今天，则不绘制

**Comment by LeeDuo** [comment]
@huanghaibin-dev 按照你提供的第二种方式，实现了月视图不会默认选中1号。但是我点击1号的时候，没有绘制选中效果，这个该怎么解决呀？
![qq 20180301160950](https://user-images.githubusercontent.com/18297605/36833666-2e545a4c-1d6b-11e8-9e90-ee03a0b03d6d.png)

贴上代码：
![qq 20180301160740](https://user-images.githubusercontent.com/18297605/36833560-c842f6be-1d6a-11e8-8416-0d74c9518a3c.png)

**Comment by huanghaibin-dev** [comment]
其实换一个方式解决就可以实现了，步骤1：onDateSelected在这个回调里面你记录一下点击的日期，用个静态变量就好，也不需要担心内存泄露，onDestroy的时候释放引用即可。
步骤2：周月视图去掉默认的onDrawSelected方法，不去实现它。
步骤3：onDrawText里面判断是不是=静态变量保存的日期，绘制效果即可

**Comment by huanghaibin-dev** [comment]
@LeeDuo

**Comment by LeeDuo** [comment]
@huanghaibin-dev 感谢大佬！按照你提供的思路，完美的解决了问题。

**Comment by xiaominglei001** [comment]
@LeeDuo 解决的话,贴下代码onDrawText里代码看看呗,感谢,有同样需求

**Comment by huanghaibin-dev** [comment]
@xiaominglei001 通过calendar.equals(静态变量)判断是不是同一个日期就可以了

**Comment by xiaominglei001** [comment]
@huanghaibin-dev 

![image](https://user-images.githubusercontent.com/7384014/36880709-1ed3d544-1e05-11e8-9d2b-f3e61c1aab25.png)
我已参考了上面步骤,现在其他可以了,但是左右滑动发现没有1号是白色的,看不到了

**Comment by huanghaibin-dev** [comment]
@xiaominglei001 那肯定是你用了白色画笔，自己查看一下哪里用错了吧

**Comment by xiaominglei001** [comment]
@huanghaibin-dev 嗯,感谢,可以了,原来改后虽说1号不自动绘制背景了,但是默认还是自动选上的,绘制文字的颜色还是白色.贴个代码,供需要的参考:

```java

    @Override
    protected void onDrawText(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme, boolean isSelected) {
        int cx = x + mItemWidth / 2;
        int cy = y + mItemHeight / 2;
        int top = y - mItemHeight / 6;

        //绘制今天且非手动选中的日期背景(默认进入时今天是被自动选中的,isSelected为true,所以也不会绘制)
        if (calendar.isCurrentDay() && !isSelected) {
            canvas.drawCircle(cx, cy, mRadius, mCurrentDayPaint);
        }

        //绘制手动选中的日期背景,不包含自动选中的.
        if (calendar.toString().equals(CustomActivity.mChosedDay)) {
            canvas.drawCircle(cx, cy, mRadius, mSelectedPaint);
        }

        if (hasScheme) {
            canvas.drawCircle(x + mItemWidth - mPadding - mCircleRadius / 2, y + mPadding + mCircleRadius, mCircleRadius, mSchemeBasicPaint);
            mTextPaint.setColor(calendar.getSchemeColor());
            canvas.drawText(calendar.getScheme(), x + mItemWidth - mPadding - mCircleRadius, y + mPadding + mSchemeBaseLine, mTextPaint);
        }

        //当然可以换成其它对应的画笔就不麻烦，
        if (calendar.isWeekend() && calendar.isCurrentMonth()) {
            mCurMonthTextPaint.setColor(0xFF489dff);
            mCurMonthLunarTextPaint.setColor(0xFF489dff);
            mSchemeTextPaint.setColor(0xFF489dff);
            mSchemeLunarTextPaint.setColor(0xFF489dff);
            mOtherMonthLunarTextPaint.setColor(0xFF489dff);
            mOtherMonthTextPaint.setColor(0xFF489dff);
        } else {
            mCurMonthTextPaint.setColor(0xff333333);
            mCurMonthLunarTextPaint.setColor(0xffCFCFCF);
            mSchemeTextPaint.setColor(0xff333333);
            mSchemeLunarTextPaint.setColor(0xffCFCFCF);

            mOtherMonthTextPaint.setColor(0xFFe1e1e1);
            mOtherMonthLunarTextPaint.setColor(0xFFe1e1e1);
        }

        if (calendar.toString().equals(CustomActivity.mChosedDay)) {//原代码 isSelected ,不管是自动或者是手动的都绘制字体为白色,这里改为只有手动选中的才绘制白色字
            canvas.drawText(String.valueOf(calendar.getDay()), cx, mTextBaseLine + top,
                    mSelectTextPaint);
            canvas.drawText(calendar.getLunar(), cx, mTextBaseLine + y + mItemHeight / 10, mSelectedLunarTextPaint);
        } else if (hasScheme) {

            canvas.drawText(String.valueOf(calendar.getDay()), cx, mTextBaseLine + top,
                    calendar.isCurrentMonth() ? mSchemeTextPaint : mOtherMonthTextPaint);

            canvas.drawText(calendar.getLunar(), cx, mTextBaseLine + y + mItemHeight / 10,
                    !TextUtils.isEmpty(calendar.getSolarTerm()) ? mSolarTermTextPaint : mSchemeLunarTextPaint);
        } else {
            canvas.drawText(String.valueOf(calendar.getDay()), cx, mTextBaseLine + top,
                    calendar.isCurrentDay() ? mCurDayTextPaint :
                            calendar.isCurrentMonth() ? mCurMonthTextPaint : mOtherMonthTextPaint);

            canvas.drawText(calendar.getLunar(), cx, mTextBaseLine + y + mItemHeight / 10,
                    calendar.isCurrentDay() ? mCurDayLunarTextPaint :
                            calendar.isCurrentMonth() ? !TextUtils.isEmpty(calendar.getSolarTerm()) ? mSolarTermTextPaint :
                                    mCurMonthLunarTextPaint : mOtherMonthLunarTextPaint);
        }
    }



```

**Comment by LeeDuo** [comment]
@xiaominglei001 
我的项目需求效果是这样的：
初始时选中今天
![1](https://user-images.githubusercontent.com/18297605/36882829-24f11728-1e11-11e8-8407-e6946446e571.png)

选择其他日期
![2](https://user-images.githubusercontent.com/18297605/36882856-46568e34-1e11-11e8-8396-954d79cab7e1.png)


代码供参考：

	@Override
	protected void onDrawText(Canvas canvas, Calendar calendar, int x, int y, boolean hasScheme, boolean isSelected){
		mCurMonthTextPaint.setColor(colorWhite);
		float baselineY = mTextBaseLine + y;
		int cx = x + mItemWidth / 2;

		int selectedX = x + mItemWidth / 2;
		int selectedY = y + mItemHeight / 2;
		mSelectedPaint.setColor(colorYellow);


		if((LocusCalenderFragment.clickDay != null && LocusCalenderFragment.clickDay.equals(calendar)) || (LocusCalenderFragment.clickDay == null && calendar.isCurrentDay())){
			//选中的日期，用实心圆覆盖
			mCurDayTextPaint.setColor(colorWhite);
			mSelectedPaint.setStyle(Paint.Style.FILL);
			canvas.drawCircle(selectedX, selectedY, mSelectedRadius, mSelectedPaint);
		}else if(calendar.isCurrentDay() && !calendar.equals(LocusCalenderFragment.clickDay) ){
			//当天日期，没有被选中，空心圆，黄色字体
			mCurDayTextPaint.setColor(colorYellow);
			mSelectedPaint.setStyle(Paint.Style.STROKE);
			canvas.drawCircle(selectedX, selectedY, mSelectedRadius, mSelectedPaint);
		}

		if(hasScheme){
			canvas.drawText(String.valueOf(calendar.getDay()), cx, baselineY, calendar.isCurrentDay() ? mCurDayTextPaint : calendar.isCurrentMonth() ? mSchemeTextPaint : mOtherMonthTextPaint);
		}else{
			canvas.drawText(String.valueOf(calendar.getDay()), cx, baselineY, calendar.isCurrentDay() ? mCurDayTextPaint : calendar.isCurrentMonth() ? mCurMonthTextPaint : mOtherMonthTextPaint);
		}
	}
