### ISSUE TITLE
日数字可以换成图片吗，源码还没看O(∩_∩)O

### ISSUE THREAD

**Issue by shoushuai** [huanghaibin-dev/CalendarView#74]
![calendar](https://user-images.githubusercontent.com/3511727/35791678-395cf44a-0a41-11e8-9def-88143609c487.png)

做个签到日历

**Comment by huanghaibin-dev** [comment]
请看README，在视图里面出现的，都是可以的，看你对canvas的理解了，你甚至可以绘制bitmap、阴影、五角星之类的
