### ISSUE TITLE
新版本的bug

### ISSUE THREAD

**Issue by zxfnicholas** [huanghaibin-dev/CalendarView#75]
1.最大年max_year 不能设为2099 ,
2.设置mCalendarView.setSchemeDate(schemes);有问题，第二次设置时不能update()

**Comment by huanghaibin-dev** [comment]
最大年份都是在2099以内的，setSchemeDate我马上改进，支持了multi schem部分地方忘记改了，谢谢提醒

**Comment by huanghaibin-dev** [comment]
@zxfnicholas 修复了

**Comment by zxfnicholas** [comment]
嗯，那最大年份不能设置2099吗？现在最大只支持2055

**Comment by huanghaibin-dev** [comment]
1901-2098

**Comment by zxfnicholas** [comment]
为什么不能设置到2099?

**Comment by KingsleyCheng** [comment]
方便加你QQ吗？想请教您点问题

**Comment by huanghaibin-dev** [comment]
临界年份目前不支持，如果显示到临界年份的前后一个月，当前的算法不支持到1899和2100年份，如果需要的话我之后做一下强制控制，范围在临界年份的，强制不显示其它月份

**Comment by huanghaibin-dev** [comment]
@KingsleyCheng 1505651581

**Comment by huanghaibin-dev** [comment]
@zxfnicholas 好吧，因为这个控件月视图有三种显示模式，如果要刚好支持临界值的话，只能强制使用mode_only_current_month了

**Comment by zxfnicholas** [comment]
没有值不填充不可以吗？

**Comment by huanghaibin-dev** [comment]
也可以的，只是要多判断多几层，我找个比较适合的方式好好改进一下

**Comment by zxfnicholas** [comment]
嗯，期待中!
