### ISSUE TITLE
切换月份不想有默认选中

### ISSUE THREAD

**Issue by ChloeSTC** [huanghaibin-dev/CalendarView#751]
我切换到下一月的时候可能我不想在下一月默认选中一个天，能否在`MonthViewPager`类中加一个字段，来控制onPageSelected方法中是否选中。

**Comment by ChloeSTC** [comment]
![image](https://user-images.githubusercontent.com/50316442/116047370-96388300-a6a6-11eb-850e-74b622b85c99.png)
已解决，之前对框架不了解

**Comment by mm46468648** [comment]
同问，怎么解决的啊
