### ISSUE TITLE
年视图的第一天 onDrawScheme 回调出现问题

### ISSUE THREAD

**Issue by skqszy123** [huanghaibin-dev/CalendarView#765]
![image](https://user-images.githubusercontent.com/19161874/123237260-17c65900-d510-11eb-8bb0-148888a56f6f.png)
第一次设置数据时回调是正常的
![image](https://user-images.githubusercontent.com/19161874/123237451-45130700-d510-11eb-9fa1-df88209a8880.png)

当我去更新数据时
![image](https://user-images.githubusercontent.com/19161874/123237227-0e3cf100-d510-11eb-9b8e-77f76193e673.png)
第一天在调用onDrawText前并没有执行onDrawScheme

用的版本是3.7.0

**Comment by huanghaibin-dev** [comment]
onDrawSelected return true

**Comment by skqszy123** [comment]
> onDrawSelected return true

thanks
