### ISSUE TITLE
请问加了scheme，没有效果，onDrawScheme没有调用，应该从哪里着手去查？

### ISSUE THREAD

**Issue by onunix** [huanghaibin-dev/CalendarView#768]
我在项目中加入了如下代码，并且单步跟踪确认其已经执行了
int year = mCalendarView.getCurYear();
        int month = mCalendarView.getCurMonth();

        Map<String, Calendar> map = new HashMap<>();
        map.put(getSchemeCalendar(year, month, 3, 0xFF40db25, "假").toString(),
                getSchemeCalendar(year, month, 3, 0xFF40db25, "假"));
        mCalendarView.setSchemeDate(map);

但是     @Override
    protected void onDrawScheme(Canvas canvas, Calendar calendar, int x, int y) {

        boolean isSelected = isSelected(calendar);
        if (isSelected) {
            mPointPaint.setColor(Color.WHITE);
        } else {
            mPointPaint.setColor(Color.GRAY);
        }

        canvas.drawCircle(x + mItemWidth / 2, y + mItemHeight - 3 * mPadding, mPointRadius, mPointPaint);
    }
却没有调用，界面上没有出现scheme那些点点，其他显示是正常的，请问这应该从哪里着手查？

**Comment by onunix** [comment]
明明在执行  mCalendarView.setSchemeDate(map); 之后，CalendarView的mDelegate.mSchemeDatesMap里面是有了日期的，为啥后边draw的时候，BaseView的mDelegate.mSchemeDatesMap又为null了，不知道问题出在哪，

**Comment by onunix** [comment]
查到错误处了。关闭

**Comment by BugMen** [comment]
@onunix 啥问题啊
