### ISSUE TITLE
【求助】样式修改

### ISSUE THREAD

**Issue by fantasyado** [huanghaibin-dev/CalendarView#79]
楼主你好，你的这个日历感觉不错，现在项目用到一个下标的日历，需要做一些修改，因为时间比较紧所以希望能给一些指导，一个是去掉日期下方的农历显示，我在demo里把 canvas.drawText里面的画农历的注释掉了但是他占用的高度还是存在这中方式应该不太对，另一个是能不能把星期天那一列移动到左右边，就是周一到周日依次排列，以上两个问题，谢谢了

**Comment by huanghaibin-dev** [comment]
@fantasyado 目前不支持修改周一到周日排列，其它的简单

**Comment by fantasyado** [comment]
那禁用农历是有api吗，我大概看了下没找到。。

**Comment by huanghaibin-dev** [comment]
UI是自行绘制的，demo下载下来就可以看到了，你可以不绘制农历就OK了，你可以直接用DEMO写好的UI

**Comment by fantasyado** [comment]
关于周日放在最后的，我试着改了一下，把MonthView中initCalendar（）方法计算preDiff的偏移量改一下，改成int mPreDiff = date.get(java.util.Calendar.DAY_OF_WEEK) - 2;然后把cv_week_bar里面的周日移到最后就可以了
