### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by liuhaoer** [huanghaibin-dev/CalendarView#8]
![screenshot_2017-05-05-10-50-27-991_com haibin cal](https://cloud.githubusercontent.com/assets/17039765/25732375/5c974c6a-3181-11e7-910d-76db7ba3a10c.png)
为什么五月份这么多假，是Bug吗？

**Comment by huanghaibin-dev** [comment]
@liuhaoer 您好，这个只是测试的标记，不影响正式使用的，这个是标记功能，具体可以看MainActivity

**Comment by dacaoyuan** [comment]
你好，这个标记功能，我怎么自定义指定呢？还有颜色我可以我怎么改变呢？我的项目需求大概是这样的：例如某几天我标记时正常的蓝色，某些天，我标记是异常的红色。希望您能提供一下说明文档，谢谢。

**Comment by huanghaibin-dev** [comment]
@dacaoyuan 你好，这个在项目的readme那里使用方法写的很详细
使用方法
 <com.haibin.calendarview.CalendarView
        android:id="@+id/calendarView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:min_year="2004"
        app:scheme_text="假"
        app:scheme_theme_color="@color/colorPrimary"
        app:selected_color="#30cfcfcf"
        app:selected_text_color="#333333"
        app:week_background="#fff"
        app:week_text_color="#111" />
attrs

<declare-styleable name="CalendarView">
        <attr name="week_background" format="color" /> 
        <attr name="week_text_color" format="color" /> 
        <attr name="scheme_theme_color" format="color" /> 
        <attr name="current_day_color" format="color" /> 
        <attr name="scheme_text" format="string" />  
        <attr name="lunar_text_color" format="color" /> 
        <attr name="selected_color" format="color" /> 
        <attr name="selected_text_color" format="color" />  
        <attr name="min_year" format="integer" />  
        <attr name="max_year" format="integer" /> 
</declare-styleable>
api

public int getCurDay(); //今天
public int getCurMonth(); //当前的月份
public int getCurYear(); //今年
public void showSelectLayout(final int year); //快速弹出年份选择月份
public void closeSelectLayout(final int position); //关闭选择年份并跳转日期
public void setOnDateChangeListener(OnDateChangeListener listener);//添加事件
public void setOnDateSelectedListener(OnDateSelectedListener listener);//日期选择事件
public void setSchemeDate(List<Calendar> mSchemeDate);//标记日期
public void setStyle(int schemeThemeColor, int selectLayoutBackground, int lineBg);
public void update();//动态更新

**Comment by liuhaoer** [comment]
@huanghaibin-dev  thanks
