### ISSUE TITLE
农历的显示与否是在哪里设置的

### ISSUE THREAD

**Issue by peterforme** [huanghaibin-dev/CalendarView#84]
没找到

**Comment by xiaominglei001** [comment]
解决了吗?哪里关闭

**Comment by huanghaibin-dev** [comment]
@xiaominglei001 UI是你自行控制绘制的，这个没有单独的参数控制，具体看demo simple版本风格，就是没有农历的

**Comment by peterforme** [comment]
@xiaominglei001 在drawText那里注释掉绘制农历就可以了

**Comment by huanghaibin-dev** [comment]
@hlgithub369 具体看demo simple版本风格，就是没有农历的，使用其他版本，单独注释掉就不是剧中对其的，总之都是由你自己绘制的，下载demo看一看就一目了然了
