### ISSUE TITLE
如何为每个周加入分割线

### ISSUE THREAD

**Issue by peterforme** [huanghaibin-dev/CalendarView#87]
就是月视图中每个周之间希望加一条横线，这个该怎么做比较方便呢

**Comment by huanghaibin-dev** [comment]
自行使用drawline就可以了，坐标都是在参数中给出的

发自我的 iPhone

**Comment by peterforme** [comment]
![2](https://user-images.githubusercontent.com/4645357/36639203-864f6cf4-1a42-11e8-942c-471618665f3b.jpg)
我希望的横线是这样的效果，貌似假如通过scheme的方式来画的话，那么非当前月份的那几个格子是没法出来横线的，有什么其他drawline的方法吗

**Comment by huanghaibin-dev** [comment]
在ondrawtext回调里面drawline即可

发自我的 iPhone

**Comment by peterforme** [comment]
在MODE_ONLY_CURRENT_MONTH的情况下，非当前月份的那几个日期是不会触发到ondrawtext的，所以会出现没画完整的情况，这样的情况如何处理呢

**Comment by huanghaibin-dev** [comment]
你用mode_fix模式即可，如果不是当前月就只drawline，否则也绘制文本，这个你就多一步判断，组合运用一下即可

发自我的 iPhone
