### ISSUE TITLE
grale引入后app名称变了

### ISSUE THREAD

**Issue by bingofan** [huanghaibin-dev/CalendarView#93]
添加了
`compile 'com.haibin:calendarview:3.2.6'`
然后App名称就变成了CalendarView。。。 。。

**Comment by huanghaibin-dev** [comment]
AS的毛病，如果资源名相同，会自动使用排序最前的libs的string，fix办法，你资源名换个，不使用app_name，或者application节点加入tools:ignore="AllowBackup,label"，我后续版本修正这个资源名，把命名都加上前缀

**Comment by bingofan** [comment]
好的多谢多谢！
