### ISSUE TITLE
怎么取消自动选中每月的一号

### ISSUE THREAD

**Issue by GavinSong91** [huanghaibin-dev/CalendarView#96]
跳转或者滑动切换月份会自动选中一号，怎么取消呢

**Comment by huanghaibin-dev** [comment]
https://github.com/huanghaibin-dev/CalendarView/issues/72  历史issue里面我给出了解决方案，目前框架没有支持这个，你可以自己简简单单就能实现

**Comment by rcj60560** [comment]
@huanghaibin-dev 
非常感谢！！！！！！！！！！！！！！！！！！
非常感谢！！！！！！！！！！！！！！！！！！
非常感谢！！！！！！！！！！！！！！！！！！
